### ISSUE TITLE
Exception: STATUS_PATH_NOT_COVERED

### ISSUE THREAD

**Issue by tony-ts** [hierynomus/smbj#152]
Hello.
I have share named "DFS" with folder "Resources". Folder Resources contains shortcut for folder "SomeFolder".
When i'm trying to access 

```java DiskShare share = (DiskShare) session.connectShare(fixPath(shareName));
Directory directory = share.openDirectory("Resources\\SomeFolder",
        EnumSet.of(AccessMask.FILE_LIST_DIRECTORY, AccessMask.FILE_READ_ATTRIBUTES),
                EnumSet.of(FileAttributes.FILE_ATTRIBUTE_DIRECTORY),
        SMB2ShareAccess.ALL,
        SMB2CreateDisposition.FILE_OPEN,
        EnumSet.of(SMB2CreateOptions.FILE_DIRECTORY_FILE));
```

i got exception

>  com.hierynomus.smbj.common.SMBApiException: STATUS_PATH_NOT_COVERED(3221226071/3221226071): Create failed for Resources\SomeFolder

In properties of folder "SomeFolder", DFS tab have link on another server  "\\SomeServer\\DFSData\\Resouces\\SomeFolder"

I found in documentation
>https://msdn.microsoft.com/en-us/library/cc227030.aspx 
To identify the DFS link targets that contain the required portion of the DFS namespace, the client MUST look up the path used for the I/O operation in ReferralCache. On a cache hit, the resulting ReferralCache entry MUST be used in further processing

But i can't find something helpful in FileIdBothDirectoryInformation.
How can i access this folder ("Resources\\SomeFolder")?

**Comment by hierynomus** [comment]
Hi @tony-ts,

DFS support is upcoming, but not merged yet. Hope to work on this tomorrow actually. So currently this error would be expected when you connect to a DFS share.

**Comment by hierynomus** [comment]
@tony-ts Can you try with the latest master? :)

Don't forget to set the `SmbConfig.withDfsEnabled(true)`. As I've disabled this by default for now, until we get some more practical experience with it.

**Comment by tony-ts** [comment]
@hierynomus Connect / open file works good. But i received exceptions (access denied) when tried  to mkfile/ mkdir / rmfile / rmdir  (i have rights for it).

> 21:08:38.191 [main] DEBUG com.hierynomus.smbj.connection.Connection - Granted 1 (out of 128) credits to SMB2_CREATE with message id << 159 >>
21:08:38.191 [main] DEBUG com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_CREATE with message id << 159 >>
21:08:38.192 [main] DEBUG com.hierynomus.protocol.commons.concurrent.Promise - Awaiting << 159 >>
21:08:38.202 [Packet Reader for 10.63.64.141] DEBUG com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_CREATE with message id << 159 >>
21:08:38.202 [Packet Reader for 10.63.64.141] DEBUG com.hierynomus.smbj.connection.Connection - Server granted us 1 credits for SMB2_CREATE with message id << 159 >>, now available: 128 credits
21:08:38.202 [Packet Reader for 10.63.64.141] DEBUG com.hierynomus.protocol.commons.concurrent.Promise - Setting << 159 >> to `SMB2_CREATE with message id << 159 >>`
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Create failed for Resources\SomeFolder\NewFolder
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DFSDiskShare.open(DFSDiskShare.java:48)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:78)
	at com.hierynomus.smbj.share.DiskShare.mkdir(DiskShare.java:174)
	at ru.esb.SMB.mkdir(SMB.java:130)
	at ru.esb.Application.main(Application.java:25)

**Comment by tony-ts** [comment]
@hierynomus When mkfile/ mkdir / rmfile / rmdir is called, dfs is not used.
Also rename after openFile with resolved dfs.

**Comment by Disablez** [comment]
With the last version I'm still getting a STATUS_PATH_NOT_COVERED if the whole FQDN is not used for the host, eg,

Accessing //test.mydomain/test... where test.mydomain resolves to IPS 1 2 and 3. Share "test" resides actually on IP 2.
client.connect("test.mydomain") -> DFS works fine
client.connect("test") -> Path not covered
client.connect("1") -> Path not covered
client.connect("2") -> Things work, but no DFS involved.

Anyway, used the proper way it works, so thanks.

**Comment by Disablez** [comment]
Nah, spoke too soon. It only works if by chance the FQDN is solved to the good IP. Otherwise this will fail.

SMB2TreeConnectResponse response = (SMB2TreeConnectResponse)Futures.get(send, this.connection.getConfig().getTransactTimeout(), TimeUnit.MILLISECONDS, TransportException.Wrapper);

and response.getCapabilities() is null in this case, same as when "wrong" ip is used as host.

Attaching a tcpdump, if it serves for anything.

[DFS3.zip](https://github.com/hierynomus/smbj/files/1281121/DFS3.zip)

**Comment by cliviu** [comment]
@Disablez , can you please try the https://github.com/cliviu/smbj  version, see if it works for you. Thanks !

**Comment by Disablez** [comment]
@cliviu Sorry, but it fails same way :(. Only works if by chance the hostname is internally resolved to the proper IP, with no need for redirection. So, still a lottery.

**Comment by cliviu** [comment]
ok, so it may be a network configuration problem. If the link always working under windoz ?

**Comment by Disablez** [comment]
It does work under windows (explorer / map to drive) with no issue.

**Comment by Disablez** [comment]
After sniffing a bit, it seems the current implementation works when the DFS folder points to several copies of the same data in different nodes, i.e. 
\\commonname\myfolder points to \\servera\myfolder and \\serverb\myfolder
\\commonname\myfolder2 points to \\servera\myfolder2 and \\serverb\\myfolder2

In this case smbj works properly .

However, if we "distribute" the folders among the nodes, e.g myfolder is physically only on servera and myfolder2 is physically only on serverb, smbj cannot resolve it. While windows does.

**Comment by vicnumberone** [comment]
hi all
The problem with 
STATUS_PATH_NOT_COVERED (0xc0000257): Cannot connect to resolved path \\QA-SRVCLIENT01\dfs_share
can you help me with this?

**Comment by kadirchisty** [comment]
Hi,
Below line is giving compile error when updated smbj jar to 0.10.0 version.

SMB2Echo responsePacket = new SMB2Echo();
responsePacket.getHeader().setStatus(NtStatus.STATUS_PATH_NOT_COVERED);

Compile error : The method setStatus(NtStatus) is undefined for the type SMB2Header

Trying to resolve below warnings:

WARNING:   An illegal reflective access operation has occurred     WARNING: Illegal reflective access by   com.hierynomus.security.jce.JceMessageDigest   (file:/C:/Users/s0wjvm/git/lhft/sr-lhft-parent/sr-lhft-web/webContent/WEB-INF/lib/smbj-0.6.0.jar)   to method sun.security.provider.MD4.getInstance()     WARNING: Please consider reporting this to the maintainers of   com.hierynomus.security.jce.JceMessageDigest     WARNING: Use --illegal-access=warn to enable warnings of further illegal   reflective access operations     WARNING: All illegal access operations will be denied in a future release

Please advice

**Comment by JozefDropco** [comment]
Hi All,
finally with version 0.11.1 I was able to remove all additional logic to work with DFS. Simply said It was enough for me to do the following.
`String uri="smb://dfs.share.com/dfs/Test/testFile.txt";
 URI uri = toURI(rootDirectory);
 SmbPath resolved;
    try {
        Connection connection = smbClient.connect(uri.getHost());
        Session session = connection.authenticate(authenticationContext);
        SmbPath resolved = SmbPath.parse(uri.getHost()+uri.getPath());
        try (DiskShare smbShare = session.connectShare(resolved.getShareName())) {
             return smbShare.fileExists(resolved.getPath());
         }
     } catch (SMBApiException e) {
        // translate exception
     }`

**Comment by ilia-dot-karelia** [comment]
> Hi All, finally with version 0.11.1 I was able to remove all additional logic to work with DFS. Simply said It was enough for me to do the following. `String uri="smb://dfs.share.com/dfs/Test/testFile.txt"; URI uri = toURI(rootDirectory); SmbPath resolved; try { Connection connection = smbClient.connect(uri.getHost()); Session session = connection.authenticate(authenticationContext); SmbPath resolved = SmbPath.parse(uri.getHost()+uri.getPath()); try (DiskShare smbShare = session.connectShare(resolved.getShareName())) { return smbShare.fileExists(resolved.getPath()); } } catch (SMBApiException e) { // translate exception }`

Have the similar issue with the latest lib version. Receive NPE on getAttributes, with 3221226071 status in the header, any ideas?
(so no error, normal response, but everything inside is null)

**Comment by JozefDropco** [comment]
hi @ilia-dot-karelia ,
I dont have any immediate idea why you got NPE, Can you share some snippet of the code. 

Thanks Jozef

**Comment by vvandre-ml** [comment]
> Hello. I have share named "DFS" with folder "Resources". Folder Resources contains shortcut for folder "SomeFolder". When i'm trying to access
> 
> ```java
> Directory directory = share.openDirectory("Resources\\SomeFolder",
>         EnumSet.of(AccessMask.FILE_LIST_DIRECTORY, AccessMask.FILE_READ_ATTRIBUTES),
>                 EnumSet.of(FileAttributes.FILE_ATTRIBUTE_DIRECTORY),
>         SMB2ShareAccess.ALL,
>         SMB2CreateDisposition.FILE_OPEN,
>         EnumSet.of(SMB2CreateOptions.FILE_DIRECTORY_FILE));
> ```
> 
> i got exception
> 
> > com.hierynomus.smbj.common.SMBApiException: STATUS_PATH_NOT_COVERED(3221226071/3221226071): Create failed for Resources\SomeFolder
> 
> In properties of folder "SomeFolder", DFS tab have link on another server "\SomeServer\DFSData\Resouces\SomeFolder"
> 
> I found in documentation
> 
> > https://msdn.microsoft.com/en-us/library/cc227030.aspx
> > To identify the DFS link targets that contain the required portion of the DFS namespace, the client MUST look up the path used for the I/O operation in ReferralCache. On a cache hit, the resulting ReferralCache entry MUST be used in further processing
> 
> But i can't find something helpful in FileIdBothDirectoryInformation. How can i access this folder ("Resources\SomeFolder")?

Hi!

Was this item implemented?

Thanks Vinicius

**Comment by dkocher** [comment]
Possibly related to #419 and resolved with #722?
