### ISSUE TITLE
STATUS_OBJECT_NAME_INVALID

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#169]
Hi, I have the following exception `Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_NAME_INVALID(3221225523/3221225523): Create failed for parentdir/xx
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:96)`

when I try to open a file "xx" in the remote directory "parentdir"

the directory "parentdir" does exist 
Here is the file creation 
` File newFile  = rootShare.openFile(relativePath,
                new HashSet<>(Arrays.asList(AccessMask.GENERIC_ALL)),
                null,
                SMB2ShareAccess.ALL,
                SMB2CreateDisposition.FILE_CREATE,
                null);`

Any hints ?

Thanks !

**Comment by cliviu** [comment]
the "xxx" file does not exist yet.

**Comment by cliviu** [comment]
Sorry, the problem was the file separator. it must have been  "parentdir\\xx"
