### ISSUE TITLE
STATUS_DELETE_PENDING

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#171]
Hi, I get the STATUS_DELETE_PENDING when trying to recursive delete a directory.
Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_DELETE_PENDING(3221225558/3221225558): 
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.rm(DiskShare.java:307)
	at com.hierynomus.smbj.share.DiskShare.rmdir(DiskShare.java:283)

 Does anybody have a hint for me,what am I doing wrong  ?

  Thanks !

**Comment by hierynomus** [comment]
`0xC0000056 STATUS_DELETE_PENDING`: A non-close operation has been requested of a file object that has a delete pending.

So you're calling `rm` when the file that you're trying to delete is already marked for deletion.

I will make that a succes response (ie. the file will already be deleted when close is called)

I have not seen this in integration tests. Can you provide an example of your code?

**Comment by cliviu** [comment]
I have tried to reproduce this using a simple program using only smbj clases and it works like a charm. The problem must be somewere in my boilerplate code. I delete first the file from directory "test/file.txt" and then I delete the directory "test". At the final operation I got the STATUS_DELETE_PENDING. I suspect that I have somewhere some not closed share/connection or something like this.
