### ISSUE TITLE
TransportException

### ISSUE THREAD

**Issue by atanuiitd** [hierynomus/smbj#178]
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.smbj.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow

I am encountering the above exception when trying to open a .tar.gz file by
sFile = smbjDiskShare.openFile(filename, accessMasks, null, shareAccesses, SMB2CreateDisposition.FILE_OPEN, null);

Where file name contains .tar.gz at the end . 

Any resolution for this ? Do I need to do something extra ?

**Comment by hierynomus** [comment]
Can you paste the entire stacktrace. And trace level logging of the attempt
in order to diagnose the problem.

Op 5 sep. 2017 7:49 a.m. schreef "atanuiitd" <notifications@github.com>:

**Comment by atanuiitd** [comment]
![exception in eclipse]
(https://user-images.githubusercontent.com/6488759/30048938-2f556e1a-9236-11e7-8a60-2b7f56c9f2fd.png)
Hi , Please see the attached .

**Comment by hierynomus** [comment]
Hi @atanuiitd, unfortunately a screenshot does not help. It does not show the required information.
In order to help you, I need the entire stacktrace as it is printed, and the trace level logging from the attempt to open the tar.gz file.

**Comment by atanuiitd** [comment]
![stacktrace](https://user-images.githubusercontent.com/6488759/30095782-58b903f4-92f2-11e7-8d74-f57b3782e537.png)
Hope this helps .

**Comment by pepijnve** [comment]
@atanuiitd e.printStackTrace and continu the stacktrace as text from the console is a more practical way of doing this. That way other developers can copy it into their development environment for further analysis.

**Comment by hierynomus** [comment]
@atanuiitd Please have a look at for instance #180 to see what information we're requesting. If you cannot provide us that information, it will be very hard for us to help you. The main question is where is the buffer underflow coming from. We need the _complete_ stacktrace to determine this.

If you're concerned with exposing private classes, feel free to snip off everything that is in your applications domain, but ensure that you give us the entire _caused by_ chain and pointers to the SMBJ code.

**Comment by atanuiitd** [comment]
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.smbj.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
	at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:97)
	at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88)
	at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:325)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:51)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hierynomus.smbj.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:61)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:67)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:45)
	... 1 more
Caused by: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.protocol.commons.buffer.Buffer.ensureAvailable(Buffer.java:184)
	at com.hierynomus.protocol.commons.buffer.Buffer.readRawBytes(Buffer.java:303)
	at com.hierynomus.protocol.commons.buffer.Buffer.readRawBytes(Buffer.java:290)
	at com.hierynomus.protocol.commons.buffer.Buffer.readRawBytes(Buffer.java:278)
	at com.hierynomus.protocol.commons.buffer.Endian$Little.readUInt32(Endian.java:196)
	at com.hierynomus.protocol.commons.buffer.Buffer.readUInt32(Buffer.java:463)
	at com.hierynomus.protocol.commons.buffer.Buffer.readUInt32(Buffer.java:452)
	at com.hierynomus.msdtyp.MsDataTypes.readFileTime(MsDataTypes.java:75)
	at com.hierynomus.mssmb2.messages.SMB2CreateResponse.readMessage(SMB2CreateResponse.java:52)
	at com.hierynomus.mssmb2.SMB2Packet.read(SMB2Packet.java:108)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:49)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:81)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:27)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader._readSMB2Packet(DirectTcpPacketReader.java:50)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:57)
	... 3 more

**Comment by hierynomus** [comment]
Which version of SMBJ are you using? I think what you're getting is a
non-success response. I've improved handling of those in the latest
versions.

2017-09-06 15:00 GMT+02:00 atanuiitd <notifications@github.com>:

**Comment by atanuiitd** [comment]
I am using smbj-0.2.0.jar along with the dependencies.
Which version should I use ?

**Comment by hierynomus** [comment]
Can you retry with 0.3.0?

2017-09-06 15:24 GMT+02:00 atanuiitd <notifications@github.com>:

**Comment by atanuiitd** [comment]
com.hierynomus.mssmb2.SMBApiException: STATUS_SHARING_VIOLATION(3221225539/3221225539): Create failed for abc.tar.gz
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:96)
	at com.dell.pg.spectre.integration.remotefileshare.RemoteFileShare.connectByCIFS(Unknown Source)
	at com.dell.pg.spectre.integration.remotefileshare.RemoteFileShare.connectToRemoteShare(Unknown Source)
	at com.dell.pg.spectre.integration.BackupRestoreDAO.downloadSharedFile(Unknown Source)
	at com.dell.pg.spectre.integration.BackupRestoreDAO.restoreDatabase(Unknown Source)
	at com.dell.pg.spectre.business.backuprestore.BackupRestoreServiceImpl.restoreDatabase(Unknown Source)
	at com.dell.pg.spectre.presentation.webservice.backuprestore.BackupRestoreEndPoint.restoreDatabase(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:246)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:146)
	at com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:257)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:95)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:629)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:588)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:573)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:470)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:295)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:515)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:285)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:143)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:155)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:189)
	at com.sun.xml.ws.transport.http.servlet.WSSpringServlet.doPost(WSSpringServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
] 

Getting this error using smbj-0.3.0.jar

**Comment by pepijnve** [comment]
That means the file has already been opened by someone else and they opened it in exclusive mode or you didn't specify the correct sharing mode. See the documentation of [CreateFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396), in particular the `dwShareMode` parameter for details.

**Comment by atanuiitd** [comment]
private static Session smbjSession = null;
 	private static Connection smbjConnection = null;
 	private static DiskShare smbjDiskShare = null;

com.hierynomus.smbj.share.File sFile = null;		 	
		 	SMBClient client = new SMBClient();	
		 	StringTokenizer st = new StringTokenizer(url,"\\"); 		 	
		 	String server=st.nextToken();
		 	String share=st.nextToken();
		 	smbjConnection = client.connect(server);		 	
		 	AuthenticationContext authenticationContext = new AuthenticationContext(username, pwd.toCharArray(), domain);		 			 	
		 	smbjSession = smbjConnection.authenticate(authenticationContext);	
			

smbjDiskShare = (DiskShare)smbjSession.connectShare(share);
Set<AccessMask> accessMasks = new HashSet<>();
Set<SMB2ShareAccess> shareAccesses= new HashSet<>();

accessMasks.add(AccessMask.FILE_READ_DATA);
		 		shareAccesses.add(SMB2ShareAccess.FILE_SHARE_READ);		 				 		
		 		**sFile = smbjDiskShare.openFile(filename, accessMasks, null, shareAccesses, SMB2CreateDisposition.FILE_OPEN, null);**

My code looks like above. 
The scenario is I need to read 2 file having .tar.gz.SUM & .tar.gz extension .
For .tar.gz.SUM it is successfully able to read but failing for .tar.gz 
I am creating individual connection & diskshare for each file read request  .

**Comment by pepijnve** [comment]
If you want the highest likelihood of being able to open the file you should pass `EnumSet.allOf(SMB2ShareAccess.class)` instead. Even if you specify that though, if there's a file handle still open somewhere that opened the file with shareAccess set to 0 (i.e., opened exclusively), you'll still get a sharing violation. There's nothing you can do about this except closing the other file handle.
For more details, please have a look at [Creating and Opening Files](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363874%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) on MSDN. That explains how these flags work in detail.

**Comment by atanuiitd** [comment]
I am encountering the same error after modifying 
shareAccesses.addAll(SMB2ShareAccess.ALL);

What else should I do ?

**Comment by pepijnve** [comment]
Not much besides figuring out who or which process has the file open and close it? Google ERROR_SHARING_VIOLATION or STATUS_SHARING_VIOLATION and you'll find similar recommendations.

**Comment by hierynomus** [comment]
There are applications that show which processes keep which files open. Once you figure that out, close the specific process and retry.

Also if you open the file using SMBJ and don't close it and call another open method it will in all likelihood fail also (unless you've specified the right `SMB2ShareAccess` level).

**Comment by atanuiitd** [comment]
What is that right SMB2ShareAccess  level? I have tried with shareAccesses.addAll(SMB2ShareAccess.ALL);
I am also closing the {smbjSession,smbjConnection ,smbjDiskShare } after each file read call .
But I have declared the "static" .
Can it have any impact ?

**Comment by atanuiitd** [comment]
Message[entering downloadSharedFile] 
Time[2017-09-07 05:30:34,664] ajp-bio-127.0.0.1-8009-exec-4 DEBUG xyz Message[the path is \\100.96.21.43\smb2\abc.tar.gz.sum] 
Time[2017-09-07 05:30:34,665] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[The filename is abc.tar.gz.sum] 
Time[2017-09-07 05:30:34,665] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[The path is \\100.96.21.43\smb2] 
Time[2017-09-07 05:30:34,665] ajp-bio-127.0.0.1-8009-exec-4 DEBUG xyz Message[In connectToRemoteShare] 
Time[2017-09-07 05:30:34,665] ajp-bio-127.0.0.1-8009-exec-4 DEBUG xyz Message[testing \\100.96.21.43\smb2] 
Time[2017-09-07 05:30:34,665] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Entering connectByCIFS ] 
Time[2017-09-07 05:30:34,667] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.connection.Connection Message[Successfully connected to: 100.96.21.43] 
Time[2017-09-07 05:30:34,677] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.connection.Connection Message[Successfully authenticated administrator on 100.96.21.43, session is 140737488355345] 
Time[2017-09-07 05:30:34,677] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Came here too ] 
Time[2017-09-07 05:30:34,677] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.session.Session Message[Connecting to \\100.96.21.43\smb2 on session 140737488355345] 
Time[2017-09-07 05:30:34,678] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Came here] 
Time[2017-09-07 05:30:34,678] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Came here also read] 
Time[2017-09-07 05:30:34,679] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Opening the remote file input stream.] 
Time[2017-09-07 05:30:34,690] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Successfully opened the remote file input stream.] 
Time[2017-09-07 05:30:34,690] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Start saving the file locally] 
Time[2017-09-07 05:30:34,690] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Loading the file to write] 
Time[2017-09-07 05:30:34,693] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.session.Session Message[Logging off session 140737488355345 from host 100.96.21.43] 
Time[2017-09-07 05:30:34,693] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.connection.Connection Message[Closed connection to 100.96.21.43] 
Time[2017-09-07 05:30:34,693] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.dell.pg.spectre.integration.remotefileshare.SmbRemoteFile Message[Closing SmbRemoteFile quietly] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[finished with dl the checksum file] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[entering downloadSharedFile] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 DEBUG xyz Message[the path is \\100.96.21.43\smb2\abc.tar.gz] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[The filename is abc.tar.gz] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[The path is \\100.96.21.43\smb2] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 DEBUG xyz Message[In connectToRemoteShare] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 DEBUG xyz Message[testing \\100.96.21.43\smb2] 
Time[2017-09-07 05:30:34,694] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Entering connectByCIFS ] 
Time[2017-09-07 05:30:34,693] Packet Reader for 100.96.21.43 INFO  com.hierynomus.smbj.transport.PacketReader Message[Thread[Packet Reader for 100.96.21.43,5,main] stopped.] 
Time[2017-09-07 05:30:34,700] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.connection.Connection Message[Successfully connected to: 100.96.21.43] 
Time[2017-09-07 05:30:34,708] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.connection.Connection Message[Successfully authenticated administrator on 100.96.21.43, session is 140737488355349] 
Time[2017-09-07 05:30:34,708] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Came here too ] 
Time[2017-09-07 05:30:34,708] ajp-bio-127.0.0.1-8009-exec-4 INFO  com.hierynomus.smbj.session.Session Message[Connecting to \\100.96.21.43\smb2 on session 140737488355349] 
Time[2017-09-07 05:30:34,709] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Came here] 
Time[2017-09-07 05:30:34,709] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[Came here also read] 
Time[2017-09-07 05:30:34,710] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[smbj exception::false] 
Time[2017-09-07 05:30:34,710] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[com.hierynomus.mssmb2.SMBApiException: STATUS_SHARING_VIOLATION(3221225539/3221225539): Create failed for abc.tar.gz] 
Time[2017-09-07 05:30:34,710] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[[Ljava.lang.StackTraceElement;@2d7bcd6f] 
Time[2017-09-07 05:30:34,711] ajp-bio-127.0.0.1-8009-exec-4 INFO  xyz Message[com.hierynomus.mssmb2.SMBApiException: STATUS_SHARING_VIOLATION(3221225539/3221225539): Create failed for abc.tar.gz
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:96)
	at xyz.connectByCIFS(Unknown Source)
	at xyz.connectToRemoteShare(Unknown Source)
	at xyz.downloadSharedFile(Unknown Source)
	at xyz.restoreDatabase(Unknown Source)	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:246)
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:146)
	at com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:257)
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:95)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:629)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:588)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:573)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:470)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:295)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:515)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:285)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:143)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:155)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:189)
	at com.sun.xml.ws.transport.http.servlet.WSSpringServlet.doPost(WSSpringServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by atanuiitd** [comment]
The above log might give a better picture . 
Look the first file.tar.gz.sum is fine . Problem occurs for 2nd file .tar.gz file .
Also I have closed connection before reading the 2nd file .

**Comment by pepijnve** [comment]
There is no 'right' share access value. Please read and make sure you understand the documentation I pointed you to.
Just to rule out that something is wrong in the smbj library, could you try mounting the SMB share and then opening tar.gz file in question manually in Windows' File Explorer or running `tar ztf` on it? Does that give you the same error (or something more user-friendly like 'file already in use')?

**Comment by atanuiitd** [comment]
I have failed to open the .tar.gz file using 7z  with error The process cannot access the file as it is being used by another process.
But what other process was using it ? I closed the connection after each file read or write .

**Comment by hierynomus** [comment]
Try to google for "which process has a file lock windows" or something
similar. There should be a number of applications that can show that.

Op 9 sep. 2017 6:38 p.m. schreef "atanuiitd" <notifications@github.com>:

**Comment by atanuiitd** [comment]
I did not close the file handle 
**com.hierynomus.smbj.share.File** sFile although I closed session,connection,diskshare .
Thats why the error occurred .
One more question :: 
How to compare the checksum in this smbj api ?
First I saved .tar.gz file using write operation & next I imported that .tar.gz file . 
Now I need to compare the checksum to avoid any corruption .

**Comment by pepijnve** [comment]
Checksum calculation is not something the SMB protocol provides. You'll have to implement this yourself by opening the file, reading it chunk by chunk and passing the data to whichever checksum algorithm you want to use. Something like this:

```
public static void calculateChecksum(DiskShare ds, String path, int bufferSize, String checksumAlgorithm) throws NoSuchAlgorithmException, IOException {
    try (File f = ds.openFile(
        path,
        EnumSet.of(AccessMask.GENERIC_READ),
        EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
        EnumSet.allOf(SMB2ShareAccess.class),
        SMB2CreateDisposition.FILE_OPEN,
        EnumSet.of(SMB2CreateOptions.FILE_NON_DIRECTORY_FILE))) {
        MessageDigest digest = MessageDigest.getInstance(checksumAlgorithm);
        byte[] buffer = new byte[bufferSize];
        try (InputStream in = f.getInputStream()) {
            int bytesRead;
            while ((bytesRead = in.read(buffer)) != -1) {
                digest.update(buffer, 0, bytesRead);
            }
            digest.digest();
        }
    }
}
```

**Comment by hierynomus** [comment]
Or you can use the `java.security.DigestInputStream` to wrap around the SMBJ inputstream. Then when reading the file, it will immediately calculate the digest.

**Comment by hierynomus** [comment]
Given that you've solved the problem, can we close the ticket?

**Comment by atanuiitd** [comment]
sure , Please close this ticket
