### ISSUE TITLE
NPE in writeDirectTcpPacketHeader

### ISSUE THREAD

**Issue by mtonina** [hierynomus/smbj#180]
Hello. I am trying to connect to a shared folder in Windows 10 with smbj 0.3.0. I have a successful DiskShare pointing to the target folder, but when I try to list/open/openFile/openDirectory I have a NullPointerException like this:

java.lang.NullPointerException
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.writeDirectTcpPacketHeader(DirectTcpTransport.java:132)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:67)
	at com.hierynomus.smbj.connection.Connection.send(Connection.java:240)
	at com.hierynomus.smbj.session.Session.send(Session.java:208)
	at com.hierynomus.smbj.share.Share.send(Share.java:324)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:318)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:78)	
	at myClass.java

I tried with directories, files and empty paths and I got always the same error, no matter which options I tried in the open sentence. Is there a bug? Or I am doing something wrong... This is one of the examples that is failing:

 diskShare.openDirectory(
					"output",
					EnumSet.of(AccessMask.GENERIC_ALL),
					EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
					EnumSet.of(SMB2ShareAccess.FILE_SHARE_WRITE),
					SMB2CreateDisposition.FILE_OVERWRITE_IF,
					EnumSet.of(SMB2CreateOptions.FILE_DIRECTORY_FILE)
			);

Thanks!

**Comment by hierynomus** [comment]
The NPE stems from the fact that the `OutputStream` is null. This is caused by a `disconnect` on the transport.

**Comment by mtonina** [comment]
Hm, It is strange because I am not doing a disconnect by code. My attempt is:

```
		SMBClient client = new SMBClient();
		try (Connection connection = client.connect(hostname)) {
			AuthenticationContext ac = this.getAuthenticationContext(user, password, domain);
			Session session = connection.authenticate(ac);
			try (DiskShare diskShare = (DiskShare) session.connectShare(path)) {
				DiskEntry file = diskShare.openDirectory(
					"output",
					EnumSet.of(AccessMask.GENERIC_ALL),
					EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
					EnumSet.of(SMB2ShareAccess.FILE_SHARE_WRITE),
					SMB2CreateDisposition.FILE_OVERWRITE_IF,
					EnumSet.of(SMB2CreateOptions.FILE_DIRECTORY_FILE)
			);
			}
		} catch (Throwable e){
			e.printStackTrace();
			return null;
		}

```
So I do not understand why there is a disconnect in the transport

**Comment by hierynomus** [comment]
What is the trace level logging you get when you run the code?

**Comment by mtonina** [comment]
It was in INFO but now, with DEBUG:

`SMC-4.0 2017-09-05 18:01:58.983 DEBUG [http-8088-exec-5] Connection.java:235   Granted 1 (out of 513) credits to SMB2_CREATE with message id << 7 >>
SMC-4.0 2017-09-05 18:01:58.984 DEBUG [http-8088-exec-5] DirectTcpTransport.java:65 Writing packet SMB2_CREATE with message id << 7 >>
java.lang.NullPointerException
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.writeDirectTcpPacketHeader(DirectTcpTransport.java:132)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:67)
	at com.hierynomus.smbj.connection.Connection.send(Connection.java:240)
	at com.hierynomus.smbj.session.Session.send(Session.java:208)
	at com.hierynomus.smbj.share.Share.send(Share.java:324)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:318)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:78)
	at smc.services.Impl.NetworkServiceImpl.getFile(NetworkServiceImpl.java:125)
	at smc.services.Impl.NetworkServiceImpl.getRemoteOutputStream(NetworkServiceImpl.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy62.getRemoteOutputStream(Unknown Source)
	at smc.broker.production.servlet.ProductionProxy.networkShare(ProductionProxy.java:1639)
	at smc.broker.production.servlet.ProductionProxy.processNotificationFinishedProductionTask(ProductionProxy.java:1123)
	at smc.broker.production.servlet.ProductionProxy.doService(ProductionProxy.java:558)
	at smc.broker.production.servlet.ProductionProxy.doPost(ProductionProxy.java:542)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:891)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:2290)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Do you need some previous messages?

**Comment by hierynomus** [comment]
Yes, from where it starts the connection attempt to the stacktrace.

**Comment by mtonina** [comment]
`MYAPP 2017-09-05 18:17:13.887 WARN  [http-8088-exec-1] HttpSessionSecurityContextRepository.java:374 Failed to create a session, as response has been committed. Unable to store SecurityContext.
MYAPP 2017-09-05 18:17:13.887 DEBUG [http-8088-exec-1] SecurityContextPersistenceFilter.java:97 SecurityContextHolder now cleared, as request processing completed
MYAPP 2017-09-05 18:17:16.475 DEBUG [http-8088-exec-3] ProxySocketFactory.java:86 Connecting to NOTEBOOK-MARCOS/10.0.75.1:445
MYAPP 2017-09-05 18:17:16.478 DEBUG [http-8088-exec-3] PacketReader.java:83  Starting PacketReader on thread: Packet Reader for NOTEBOOK-MARCOS
MYAPP 2017-09-05 18:17:16.491 DEBUG [http-8088-exec-3] Connection.java:270   Negotiating dialects [SMB_2_0_2, SMB_2_1] with server NOTEBOOK-MARCOS
MYAPP 2017-09-05 18:17:16.498 DEBUG [http-8088-exec-3] Connection.java:235   Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 0 >>
MYAPP 2017-09-05 18:17:16.506 DEBUG [http-8088-exec-3] DirectTcpTransport.java:65 Writing packet SMB2_NEGOTIATE with message id << 0 >>
MYAPP 2017-09-05 18:17:16.527 DEBUG [http-8088-exec-3] Promise.java:163      Awaiting << 0 >>
MYAPP 2017-09-05 18:17:16.545 DEBUG [Packet Reader for NOTEBOOK-MARCOS] PacketReader.java:70 Received packet SMB2_NEGOTIATE with message id << 0 >>
MYAPP 2017-09-05 18:17:16.545 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Connection.java:347 Server granted us 1 credits for SMB2_NEGOTIATE with message id << 0 >>, now available: 1 credits
MYAPP 2017-09-05 18:17:16.545 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Promise.java:78 Setting << 0 >> to `SMB2_NEGOTIATE with message id << 0 >>`
MYAPP 2017-09-05 18:17:16.546 DEBUG [http-8088-exec-3] Connection.java:285   Negotiated the following connection settings: ConnectionInfo{
  serverGuid=97ba8967-2607-443f-a674-e7faf6a74dc5,
  serverName='NOTEBOOK-MARCOS',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_2_1, maxTransactSize=8388608, maxReadSize=8388608, maxWriteSize=8388608},
  clientGuid=92b2a2ec-5299-42b6-a1c1-898b1480f7ee,
  clientCapabilities=[SMB2_GLOBAL_CAP_DFS],
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=0,
  serverSecurityMode=1,
  server='null'
}
MYAPP 2017-09-05 18:17:16.546 INFO  [http-8088-exec-3] Connection.java:108   Successfully connected to: NOTEBOOK-MARCOS
MYAPP 2017-09-05 18:17:16.659 DEBUG [http-8088-exec-3] NtlmAuthenticator.java:72 Initialized Authentication of marcos.tonina@outlook.com using NTLM
MYAPP 2017-09-05 18:17:16.712 DEBUG [http-8088-exec-3] Connection.java:235   Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 1 >>
MYAPP 2017-09-05 18:17:16.713 DEBUG [http-8088-exec-3] DirectTcpTransport.java:65 Writing packet SMB2_SESSION_SETUP with message id << 1 >>
MYAPP 2017-09-05 18:17:16.713 DEBUG [http-8088-exec-3] Promise.java:163      Awaiting << 1 >>
MYAPP 2017-09-05 18:17:16.716 DEBUG [Packet Reader for NOTEBOOK-MARCOS] PacketReader.java:70 Received packet SMB2_SESSION_SETUP with message id << 1 >>
MYAPP 2017-09-05 18:17:16.716 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Connection.java:347 Server granted us 1 credits for SMB2_SESSION_SETUP with message id << 1 >>, now available: 1 credits
MYAPP 2017-09-05 18:17:16.716 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Promise.java:78 Setting << 1 >> to `SMB2_SESSION_SETUP with message id << 1 >>`
MYAPP 2017-09-05 18:17:16.717 DEBUG [http-8088-exec-3] Connection.java:161   More processing required for authentication of marcos.tonina@outlook.com using com.hierynomus.smbj.auth.NtlmAuthenticator@3869df75
MYAPP 2017-09-05 18:17:16.719 DEBUG [http-8088-exec-3] NtlmAuthenticator.java:77 Received token: a1 82 01 0b 30 82 01 07 a0 03 0a 01 01 a1 0c 06 0a 2b 06 01 04 01 82 37 02 02 0a a2 81 f1 04 81 ee 4e 54 4c 4d 53 53 50 00 02 00 00 00 1e 00 1e 00 38 00 00 00 15 82 8a e2 f7 1a 9c 3f c6 c8 6e 49 00 00 00 00 00 00 00 00 98 00 98 00 56 00 00 00 0a 00 d7 3a 00 00 00 0f 4e 00 4f 00 54 00 45 00 42 00 4f 00 4f 00 4b 00 2d 00 4d 00 41 00 52 00 43 00 4f 00 53 00 02 00 1e 00 4e 00 4f 00 54 00 45 00 42 00 4f 00 4f 00 4b 00 2d 00 4d 00 41 00 52 00 43 00 4f 00 53 00 01 00 1e 00 4e 00 4f 00 54 00 45 00 42 00 4f 00 4f 00 4b 00 2d 00 4d 00 41 00 52 00 43 00 4f 00 53 00 04 00 1e 00 4e 00 4f 00 54 00 45 00 42 00 4f 00 4f 00 4b 00 2d 00 4d 00 41 00 52 00 43 00 4f 00 53 00 03 00 1e 00 4e 00 4f 00 54 00 45 00 42 00 4f 00 4f 00 4b 00 2d 00 4d 00 41 00 52 00 43 00 4f 00 53 00 07 00 08 00 d7 78 c3 59 8c 26 d3 01 00 00 00 00
MYAPP 2017-09-05 18:17:16.794 DEBUG [http-8088-exec-3] NtlmChallenge.java:114 Windows version = WindowsVersion[WINDOWS_MAJOR_VERSION_10, WINDOWS_MINOR_VERSION_0, 15063, NTLMSSP_REVISION_W2K3]
MYAPP 2017-09-05 18:17:16.800 DEBUG [http-8088-exec-3] NtlmAuthenticator.java:87 Received NTLM challenge from: NOTEBOOK-MARCOS
MYAPP 2017-09-05 18:17:16.851 DEBUG [http-8088-exec-3] Connection.java:235   Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 2 >>
MYAPP 2017-09-05 18:17:16.851 DEBUG [http-8088-exec-3] DirectTcpTransport.java:65 Writing packet SMB2_SESSION_SETUP with message id << 2 >>
MYAPP 2017-09-05 18:17:16.852 DEBUG [http-8088-exec-3] Promise.java:163      Awaiting << 2 >>
MYAPP 2017-09-05 18:17:16.857 DEBUG [Packet Reader for NOTEBOOK-MARCOS] PacketReader.java:70 Received packet SMB2_SESSION_SETUP with message id << 2 >>
MYAPP 2017-09-05 18:17:16.857 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Connection.java:347 Server granted us 511 credits for SMB2_SESSION_SETUP with message id << 2 >>, now available: 511 credits
MYAPP 2017-09-05 18:17:16.857 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Promise.java:78 Setting << 2 >> to `SMB2_SESSION_SETUP with message id << 2 >>`
MYAPP 2017-09-05 18:17:16.857 INFO  [http-8088-exec-3] Connection.java:173   Successfully authenticated marcos.tonina@outlook.com on NOTEBOOK-MARCOS, session is 87961064439825
MYAPP 2017-09-05 18:17:16.860 INFO  [http-8088-exec-3] Session.java:105      Connecting to \\NOTEBOOK-MARCOS\temporal on session 87961064439825
MYAPP 2017-09-05 18:17:16.863 DEBUG [http-8088-exec-3] Connection.java:235   Granted 1 (out of 511) credits to SMB2_TREE_CONNECT with message id << 3 >>
MYAPP 2017-09-05 18:17:16.864 DEBUG [http-8088-exec-3] DirectTcpTransport.java:65 Writing packet SMB2_TREE_CONNECT with message id << 3 >>
MYAPP 2017-09-05 18:17:16.866 DEBUG [http-8088-exec-3] Promise.java:163      Awaiting << 3 >>
MYAPP 2017-09-05 18:17:16.868 DEBUG [Packet Reader for NOTEBOOK-MARCOS] PacketReader.java:70 Received packet SMB2_TREE_CONNECT with message id << 3 >>
MYAPP 2017-09-05 18:17:16.868 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Connection.java:347 Server granted us 2 credits for SMB2_TREE_CONNECT with message id << 3 >>, now available: 512 credits
MYAPP 2017-09-05 18:17:16.868 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Promise.java:78 Setting << 3 >> to `SMB2_TREE_CONNECT with message id << 3 >>`
MYAPP 2017-09-05 18:17:16.892 DEBUG [http-8088-exec-3] Connection.java:235   Granted 1 (out of 512) credits to SMB2_TREE_DISCONNECT with message id << 4 >>
MYAPP 2017-09-05 18:17:16.893 DEBUG [http-8088-exec-3] DirectTcpTransport.java:65 Writing packet SMB2_TREE_DISCONNECT with message id << 4 >>
MYAPP 2017-09-05 18:17:16.894 DEBUG [http-8088-exec-3] Promise.java:163      Awaiting << 4 >>
MYAPP 2017-09-05 18:17:16.894 DEBUG [Packet Reader for NOTEBOOK-MARCOS] PacketReader.java:70 Received packet SMB2_TREE_DISCONNECT with message id << 4 >>
MYAPP 2017-09-05 18:17:16.894 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Connection.java:347 Server granted us 2 credits for SMB2_TREE_DISCONNECT with message id << 4 >>, now available: 513 credits
MYAPP 2017-09-05 18:17:16.895 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Promise.java:78 Setting << 4 >> to `SMB2_TREE_DISCONNECT with message id << 4 >>`
MYAPP 2017-09-05 18:17:16.900 DEBUG [http-8088-exec-3] Session.java:147      Notified of TreeDisconnected <<1>>
MYAPP 2017-09-05 18:17:16.901 INFO  [http-8088-exec-3] Session.java:154      Logging off session 87961064439825 from host NOTEBOOK-MARCOS
MYAPP 2017-09-05 18:17:16.902 DEBUG [http-8088-exec-3] Connection.java:235   Granted 1 (out of 513) credits to SMB2_LOGOFF with message id << 5 >>
MYAPP 2017-09-05 18:17:16.902 DEBUG [http-8088-exec-3] DirectTcpTransport.java:65 Writing packet SMB2_LOGOFF with message id << 5 >>
MYAPP 2017-09-05 18:17:16.903 DEBUG [http-8088-exec-3] Promise.java:163      Awaiting << 5 >>
MYAPP 2017-09-05 18:17:16.903 DEBUG [Packet Reader for NOTEBOOK-MARCOS] PacketReader.java:70 Received packet SMB2_LOGOFF with message id << 5 >>
MYAPP 2017-09-05 18:17:16.903 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Connection.java:347 Server granted us 2 credits for SMB2_LOGOFF with message id << 5 >>, now available: 514 credits
MYAPP 2017-09-05 18:17:16.904 DEBUG [Packet Reader for NOTEBOOK-MARCOS] Promise.java:78 Setting << 5 >> to `SMB2_LOGOFF with message id << 5 >>`
MYAPP 2017-09-05 18:17:16.904 DEBUG [http-8088-exec-3] Connection.java:423   Session << 87961064439825 >> logged off
MYAPP 2017-09-05 18:17:16.904 DEBUG [http-8088-exec-3] PacketReader.java:63  Stopping PacketReader...
MYAPP 2017-09-05 18:17:16.905 INFO  [http-8088-exec-3] Connection.java:136   Closed connection to NOTEBOOK-MARCOS
MYAPP 2017-09-05 18:17:16.905 INFO  [Packet Reader for NOTEBOOK-MARCOS] PacketReader.java:58 Thread[Packet Reader for NOTEBOOK-MARCOS,5,main] stopped.
MYAPP 2017-09-05 18:17:16.905 DEBUG [http-8088-exec-3] SMBClient.java:107    Connection to << NOTEBOOK-MARCOS:445 >> closed
MYAPP 2017-09-05 18:17:16.910 DEBUG [http-8088-exec-3] Connection.java:235   Granted 1 (out of 514) credits to SMB2_CREATE with message id << 6 >>
MYAPP 2017-09-05 18:17:16.911 DEBUG [http-8088-exec-3] DirectTcpTransport.java:65 Writing packet SMB2_CREATE with message id << 6 >>
java.lang.NullPointerException
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.writeDirectTcpPacketHeader(DirectTcpTransport.java:132)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:67)
	at com.hierynomus.smbj.connection.Connection.send(Connection.java:240)
	at com.hierynomus.smbj.session.Session.send(Session.java:208)
	at com.hierynomus.smbj.share.Share.send(Share.java:324)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:318)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:78)
	at smc.services.Impl.NetworkServiceImpl.getFile(NetworkServiceImpl.java:125)
	at smc.services.Impl.NetworkServiceImpl.getRemoteOutputStream(NetworkServiceImpl.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy62.getRemoteOutputStream(Unknown Source)
	at smc.broker.production.servlet.ProductionProxy.networkShare(ProductionProxy.java:1639)
	at smc.broker.production.servlet.ProductionProxy.processNotificationFinishedProductionTask(ProductionProxy.java:1123)
	at smc.broker.production.servlet.ProductionProxy.doService(ProductionProxy.java:558)
	at smc.broker.production.servlet.ProductionProxy.doPost(ProductionProxy.java:542)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:891)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:2290)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by hierynomus** [comment]
I've at least ensured that you don't get a nasty NPE now in fb96951. However the main question is why is it sending a SMB2_TREE_DISCONNECT / SMB2_LOGOFF, and only then the SMB2_CREATE.

Is that really the exact code you're using? Can you write a reproducible JUnit testcase?

**Comment by mtonina** [comment]
This is my exact code:

`	private com.hierynomus.smbj.share.File getFile(String user, String password, String domain, String remotePath)
			throws Exception {

		DiskShare diskShare = this.getDiskShare(user, password, domain, this.getHostname(remotePath),
				this.getPath(remotePath));
		try {
			DiskEntry file = diskShare.openDirectory(
					"output",
					EnumSet.of(AccessMask.GENERIC_ALL),
					EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
					EnumSet.of(SMB2ShareAccess.FILE_SHARE_WRITE),
					SMB2CreateDisposition.FILE_OVERWRITE_IF,
					EnumSet.of(SMB2CreateOptions.FILE_DIRECTORY_FILE)
			);
		} catch (Throwable e) {
			e.printStackTrace();
		}
		return null;
	}

	private DiskShare getDiskShare(String user, String password, String domain, String hostname, String path)
			throws Exception {
		SMBClient client = new SMBClient();
		try (Connection connection = client.connect(hostname)) {
			AuthenticationContext ac = this.getAuthenticationContext(user, password, domain);
			Session session = connection.authenticate(ac);
			try (DiskShare diskShare = (DiskShare) session.connectShare(path)) {
				return diskShare;
			}
		} catch (Throwable e){
			e.printStackTrace();
			return null;
		}
	}`

I will create a test in order to reproduce the error easily. The exception is thrown in the openDirectory sentence. The DiskShare is connected sucessfully.

**Comment by pepijnve** [comment]
@mtonina you can't use try-with-resources the way you're doing in `getDiskShare`. When you exact that method `close` is implicitly called on the DiskShare and the Connection object. So you end up returning a closed object which is effectively unusable.

**Comment by mtonina** [comment]
Oh Lord...

**Comment by pepijnve** [comment]
😄 happens to the best of us

**Comment by mtonina** [comment]
Well I think that this is called over-engineering.. thanks and I will close this issue and go to my mother's house in order to think in what I have done.

**Comment by pepijnve** [comment]
@hierynomus there is a lesson to be learned here. DiskShare keeps track of whether it's already closed or not. It's methods should fail-fast if that's the case with an exception stating that the object was closed. I'll make a PR for that.

**Comment by pepijnve** [comment]
Created PR #181. I added a check right before trying to send any request in Share. That should cover just about everything you can do with a Share object.

**Comment by hierynomus** [comment]
Yes, I added a similar check already to the transport. I'll merge yours as well.

**Comment by pepijnve** [comment]
Sorry if I came across a bit pedantic btw. I meant there's an opportunity for improvement of the library.
