### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Create failed for ITD\EKS_Test\MyDir\

### ISSUE THREAD

**Issue by gidravlic** [hierynomus/smbj#183]
Hi all!
In my test environment(FreeBsd10.3 + latest smbj + Windows 10) all work fine.
Other test environment(FreeBsd10.3 + latest smbj + Windows Server 2008) i got subject error. 
From Windows 10 connection to Windows Server 2008 passes normally + Far Manager have full functionality. I have full access to the folder ITD\EKS_Test in share PUBLIC. I can write, read, create and delete objects with the same user.
What am I doing wrong?
```java
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Create failed for ITD\EKS_Test\MyDir\
        at com.hierynomus.smbj.share.Share.receive(Share.java:335)
        at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
        at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
        at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
        at com.hierynomus.smbj.share.DiskShare.exists(DiskShare.java:121)
        at com.hierynomus.smbj.share.DiskShare.folderExists(DiskShare.java:117)
```
Thanks!

**Comment by gidravlic** [comment]
Hi all again!
Partially solved. If i check folder existence in share on Windows 10 (ITD\EKS_Test\MyDir\\) with a slash at the end of the string, all works file. However, we get an error in Windows Server 2008. If check folder existence without a slash, all works file on both machines.
Still there was a problem with **rename**  method on Windows Server 2008 (on Windows 10 work fine).
I have 
```java
public void rename(final String path, final String newName) {
        String fileName = transformPath(path);
        log.debug("Rename {} file to {}", fileName, newName);
        try (File file = diskShare.openFile(fileName, EnumSet.of(AccessMask.GENERIC_ALL), null, SMB2ShareAccess.ALL, FILE_OPEN, null)) {
            file.rename(newName);
        }
}
```
calling 
```java 
rename("ITD\EKS_Test\test.txt", "ITD\EKS_Test\MyDir\renamed.txt")
```
Output: 
Rename ITD\EKS_Test\test.txt file to ITD\EKS_Test\MyDir\renamed.txt

Source file exist, destination directory exist, but i have error:
```java
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Create failed for ITD\EKS_Test\test.txt
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:96)
	at org.test.smbclientex.SMBClientEx.rename(SMBClientEx.java:321)
```
Any suggestions?
Thanks

**Comment by gidravlic** [comment]
I answer myself. Instead of
```java
public void rename(final String path, final String newName) {
        String fileName = transformPath(path);
        log.debug("Rename {} file to {}", fileName, newName);
        try (File file = diskShare.openFile(fileName, EnumSet.of(AccessMask.GENERIC_ALL), null, SMB2ShareAccess.ALL, FILE_OPEN, null)) {
            file.rename(newName);
        }
}
```
we have to use other AccessMask
```java
public void rename(final String path, final String newName) {
        String fileName = transformPath(path);
        log.debug("Rename {} file to {}", fileName, newName);
        try (File file = diskShare.openFile(fileName, EnumSet.of(AccessMask.DELETE, AccessMask.GENERIC_WRITE), null, SMB2ShareAccess.ALL, FILE_OPEN, null)) {
            file.rename(newName);
        }
}
```
