### ISSUE TITLE
Can't connect to server: "java.io.EOFException: EOF while reading packet"

### ISSUE THREAD

**Issue by sovesky** [hierynomus/smbj#225]
Thread #168 addresses an issue trying to connect to a server that only supports smb v1.

At the moment I'm observing a similar behaviour in my tests of smbj v0.4.0 where I can't connect to a server, resulting in the stacktrace at the bottom.

I can confirm that the target server has min protocol = NT1 and max protocol SMB3, which I believe means it should accept connections using SMB2. Am I forced to establish min protocol = SMB2?

For testing purposes, I tried connecting to a server with min protocol = SMB2 and it worked fine.

com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:29)
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:23)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:43)
	at com.hierynomus.smbj.connection.Connection.smb2OnlyNegotiate(Connection.java:303)
	at com.hierynomus.smbj.connection.Connection.negotiateDialect(Connection.java:287)
	at com.hierynomus.smbj.connection.Connection.connect(Connection.java:114)
	at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:90)
	at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:68)
	at com.investec.java.SMBJTester.App.main(App.java:27)
Caused by: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:60)
	at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:84)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
	... 6 more
Caused by: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
	at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:95)
	at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88)
	at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:414)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:53)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:72)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
	... 1 more
Caused by: java.io.EOFException: EOF while reading packet
	... 6 more

**Comment by pepijnve** [comment]
Looks like the server is terminating the connection from its end. You could try enabling multi-protocol negotiation. Use `SmbConfig.builder().withMultiProtocolNegotiate(true).build()` as config.

**Comment by sovesky** [comment]
I tried doing that, getting the same response as in thread #168:
com.hierynomus.mssmb.SMB1NotSupportedException: SMBv1 is not supported by SMBJ

As mentioned in the original post, if we set up min protocol in that server to SMB2, the connection is successful. Is it safe to assume that SMBJ can't detect the min protocol established in the target server?

Thank you

**Comment by hierynomus** [comment]
@sovesky This is a server misconfiguration issue. If you enable the `withMultiProtocolNegotiate` as @pepijnve suggested, and you're getting a `SMBv1 is not supported` error, then the server does not accept SMBv2 connections, but forces SMBv1.
Which server OS/version are you connecting with?

**Comment by hierynomus** [comment]
@sovesky Do you need any more help? Is the issue fixed?

**Comment by sovesky** [comment]
Thank you for the help. Restricting the server to use SMB2 (and above), partially fixed it. It seems that now I'm back to: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet.

I was told the target server has mandatory client and server signing. The test application I'm using specifies the following builder, which I believe would be needed given the target server's config.

SmbConfig cfg = SmbConfig.builder().withMultiProtocolNegotiate(true).withSigningRequired(true).build();

The Stacktrace is very generic with the same EOF error. Any ideas on how I can get a more meaningful/detailed error?

**Comment by hierynomus** [comment]
Is the stacktrace exactly the same still? Can you post debug/trace logging and the complete stacktrace you're now getting?

**Comment by sovesky** [comment]
Hi,

This is the stacktrace I'm getting:

589 [Packet Reader for *server*] INFO com.hierynomus.smbj.transport.PacketReader - PacketReader error.
593 [Packet Reader for *server*] INFO com.hierynomus.smbj.connection.Connection - Closed connection to *server*
593 [main] ERROR com.hierynomus.protocol.commons.concurrent.Promise - << 0 >> woke to: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
594 [main] INFO com.hierynomus.smbj.connection.Connection - Closed connection to *server*
com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:29)
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:23)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:43)
	at com.hierynomus.smbj.connection.Connection.multiProtocolNegotiate(Connection.java:316)
	at com.hierynomus.smbj.connection.Connection.negotiateDialect(Connection.java:285)
	at com.hierynomus.smbj.connection.Connection.connect(Connection.java:114)
	at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:90)
	at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:68)
	at com.java.SMBJTester.App.main(App.java:20)
Caused by: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:60)
	at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:84)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
	... 6 more
Caused by: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
	at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:95)
	at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88)
	at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:414)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:53)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:72)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
	... 1 more
Caused by: java.io.EOFException: EOF while reading packet
	... 6 more

**Comment by hierynomus** [comment]
It just terminates the connection during the negotiate? That's really weird. A network packet capture (pcap file) would be useful to see whether anything comes back at all, or whether it just closes the connection.

**Comment by hierynomus** [comment]
@sovesky Any update, can you obtain a pcap file using WireShark?

**Comment by hierynomus** [comment]
@sovesky Any update? Else I'm closing this issue due to lack of information...

**Comment by sovesky** [comment]
Apologies for the delay. I'm currently working on getting the pcab file. Will update soon.

**Comment by sovesky** [comment]
The data capture does not include the reason why the server is closing the connection. I'm trying to retrieve samba logs from the target server, which I don't own.

**Comment by hierynomus** [comment]
Can you post the binary pcap file, including all the packets. I'm now not sure whether I'm looking at the request we're sending out or at the response we're getting back.

**Comment by sovesky** [comment]
Unfortunately I cannot publish the entire file as there is classified data in there. 

The block above represents the request sent to the server. No response is received given that the server is closing the connection immediately.

I'm trying to understand the reasoning behind this, but judging from the behaviour this seems to be a server problems instead of an issue with the library itself.

**Comment by hierynomus** [comment]
Does the server support multi-protocol negotiation? It might have disabled that when you disabled smb v1 support on the server.
What server is it?

**Comment by sovesky** [comment]
Possibly related, we're having problems using the library with another Linux box. In this case we are getting a Negotiate Protocol Response with the follow response:

SMB (Server Message Block Protocol)
    SMB Header
        Server Component: SMB
        SMB Command: Negotiate Protocol (0x72)
        NT Status: STATUS_SUCCESS (0x00000000)
        Flags: 0x88, Request/Response, Case Sensitivity
            1... .... = Request/Response: Message is a response to the client/redirector
            .0.. .... = Notify: Notify client only on open
            ..0. .... = Oplocks: OpLock not requested/granted
            ...0 .... = Canonicalized Pathnames: Pathnames are not canonicalized
            .... 1... = Case Sensitivity: Path names are caseless
            .... ..0. = Receive Buffer Posted: Receive buffer has not been posted
            .... ...0 = Lock and Read: Lock&Read, Write&Unlock are not supported
        Flags2: 0xc003, Unicode Strings, Error Code Type, Extended Attributes, Long Names Allowed
            1... .... .... .... = Unicode Strings: Strings are Unicode
            .1.. .... .... .... = Error Code Type: Error codes are NT error codes
            ..0. .... .... .... = Execute-only Reads: Don't permit reads if execute-only
            ...0 .... .... .... = Dfs: Don't resolve pathnames with Dfs
            .... 0... .... .... = Extended Security Negotiation: Extended security negotiation is not supported
            .... .0.. .... .... = Reparse Path: The request does not use a @GMT reparse path
            .... .... .0.. .... = Long Names Used: Path names in request are not long file names
            .... .... ...0 .... = Security Signatures Required: Security signatures are not required
            .... .... .... 0... = Compressed: Compression is not requested
            .... .... .... .0.. = Security Signatures: Security signatures are not supported
            .... .... .... ..1. = Extended Attributes: Extended attributes are supported
            .... .... .... ...1 = Long Names Allowed: Long file names are allowed in the response
        Process ID High: 0
        Signature: 0000000000000000
        Reserved: 0000
        Tree ID: 0
        Process ID: 0
        User ID: 0
        Multiplex ID: 0
    Negotiate Protocol Response (0x72)
        Word Count (WCT): 1
        Selected Index: -1, PC NETWORK PROGRAM 1.0 chosen
        Byte Count (BCC): 0

**Comment by hierynomus** [comment]
It seems that the server disagrees with that statement, it looks like it wants SMBv1 solely :)

**Comment by sovesky** [comment]
Thanks for the help. It seems that was exactly the case. I was betrayed here by a sys admin that failed to properly configure smb.config.

**Comment by hierynomus** [comment]
ok, closing this issue then!
