### ISSUE TITLE
Win 10 Fall Creators Update (build 1709) buffer underflow error in SMB2Error

### ISSUE THREAD

**Issue by tliebeck** [hierynomus/smbj#226]
I'm seeing an SMBRuntimeException which is wrapping a BufferException "Underflow" on mosts tasks with Windows 10, build 1709 ("Fall Creators Update").  

This appears to happen any time it sees a non-success status, which of course includes statuses like NO_MORE_FILES, or any time SMB2Packet.readError() is invoked.  

The underflow is occurring when the SMB2Error object attempts to skip over the ErrorData byte:

    SMB2Error read(SMB2Header header, SMBBuffer buffer) throws Buffer.BufferException {
        buffer.skip(2); // StructureSize (2 bytes)
        int errorContextCount = buffer.readByte(); // ErrorContextCount (1 byte)
        buffer.skip(1); // Reserved (1 byte)
        int byteCount = buffer.readUInt32AsInt(); // ByteCount (4 bytes)

        if (errorContextCount > 0) {
            readErrorContext(header, buffer, errorContextCount);
        } else if (byteCount > 0) {
            readErrorData(header, buffer);
        } else if (byteCount == 0) {
            buffer.skip(1); // ErrorData (1 byte)     <**** RIGHT HERE! *****
        }

        return this;
    }

I've been able to entirely workaround this underflow problem by simply adding an isAvailable() check before the skip() call:

    SMB2Error read(SMB2Header header, SMBBuffer buffer) throws Buffer.BufferException {
        buffer.skip(2); // StructureSize (2 bytes)
        int errorContextCount = buffer.readByte(); // ErrorContextCount (1 byte)
        buffer.skip(1); // Reserved (1 byte)
        int byteCount = buffer.readUInt32AsInt(); // ByteCount (4 bytes)

        if (errorContextCount > 0) {
            readErrorContext(header, buffer, errorContextCount);
        } else if (byteCount > 0) {
            readErrorData(header, buffer);
        } else if (byteCount == 0) {
            // Added to workaround Win10 1709
            if (buffer.available() > 0) {
                buffer.skip(1); // ErrorData (1 byte)
            }            
        }

        return this;
    }

Please bear in mind I am not particularly fluent with the inner workings of the SMB protocol, so I don't actually know what's out of spec here, i.e,. if that error code is supposed to be optional and SMBJ isn't processing the response correctly, or if MS is out of spec themselves.

Here is the full stack trace for a simple program that tries to do a DiskShare.list() call:  

FAIL:com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.smbj.share.Share.receive(Share.java:378)
	at com.hierynomus.smbj.share.Share.receive(Share.java:360)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:344)
	at com.hierynomus.smbj.share.Share.queryDirectory(Share.java:210)
	at com.hierynomus.smbj.share.Directory$DirectoryIterator.queryDirectory(Directory.java:173)
	at com.hierynomus.smbj.share.Directory$DirectoryIterator.prepareNext(Directory.java:154)
	at com.hierynomus.smbj.share.Directory$DirectoryIterator.next(Directory.java:145)
	at com.hierynomus.smbj.share.Directory$DirectoryIterator.next(Directory.java:119)
	at com.hierynomus.smbj.share.Directory.list(Directory.java:64)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:166)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:138)
	at Test.main(Test.java:26)
	Suppressed: com.hierynomus.smbj.common.SMBRuntimeException: DiskShare has already been closed
		at com.hierynomus.smbj.share.Share.send(Share.java:349)
		at com.hierynomus.smbj.share.Share.sendReceive(Share.java:343)
		at com.hierynomus.smbj.share.Share.closeFileId(Share.java:176)
		at com.hierynomus.smbj.share.DiskEntry.close(DiskEntry.java:48)
		at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:167)
		... 2 more
Caused by: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:29)
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:23)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:43)
	at com.hierynomus.smbj.share.Share.receive(Share.java:373)
	... 11 more
Caused by: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:60)
	at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:84)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
	... 12 more
Caused by: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
	at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:95)
	at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88)
	at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:413)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
	... 1 more
Caused by: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.protocol.commons.buffer.Buffer.ensureAvailable(Buffer.java:184)
	at com.hierynomus.protocol.commons.buffer.Buffer.skip(Buffer.java:732)
	at com.hierynomus.mssmb2.SMB2Error.read(SMB2Error.java:47)
	at com.hierynomus.mssmb2.SMB2Packet.readError(SMB2Packet.java:118)
	at com.hierynomus.mssmb2.SMB2Packet.read(SMB2Packet.java:112)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:79)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:52)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:85)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:26)
	at com.hierynomus.smbj.connection.Connection$DelegatingSMBMessageConverter.read(Connection.java:452)
	at com.hierynomus.smbj.connection.Connection$DelegatingSMBMessageConverter.read(Connection.java:441)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readPacket(DirectTcpPacketReader.java:42)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:49)
	... 3 more

**Comment by tliebeck** [comment]
As far as I can tell....they broke it.  Take this opinion with a grain of salt as it's the first time I've looked at the actual SMB2 specification.

I see that last byte that you're expecting is described here in the SMB spec:

>  If the ByteCount field is zero then the server MUST supply an ErrorData field that is one byte in
> length, and SHOULD set that byte to zero; the client MUST ignore it on receipt.

And the ByteCount field is zero.  I also checked the "StructureSize" field and it's set to 9, as per spec.

**Comment by hierynomus** [comment]
Indeed, it seems that they broke it. I already toyed with the idea of adding a Compatibility mode. This one would fit in nicely ;). I'll leave it open for now. Have you registered a bug with MS already?

**Comment by pepijnve** [comment]
@hierynomus perhaps smbj should apply [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle). A compatibility mode might be interesting when smbj needs to generate non-compliant requests. For responses it's much more convenient for users that it just works.
Or perhaps 'compatibility mode' should be on by default and allow it be switched off (or enable an optional strict mode) for people who really want to insist on their servers being spec compliant.

**Comment by pepijnve** [comment]
![screen shot 2017-10-23 at 13 02 59](https://user-images.githubusercontent.com/225326/31885932-86f515f8-b7f2-11e7-8b58-fb5bc0035533.png)

FWIW wireshark agrees. I tried connecting from macOS as well; that doesn't have the same issue, but it negotiates SMB dialect `0x0302`. So it seems like the SMB only some dialects (`0x0210` in my test case) are broken.

**Comment by tliebeck** [comment]
@hierynomus I've not reported it to MS yet, I'm not terribly familiar with MS development community.  Is there a means to report this as a developer rather than end-user/consumer?  Worried it will get lost among the noise of "my wifi router is blinking funny" type bug reports.

**Comment by hierynomus** [comment]
Fixed with #227
