### ISSUE TITLE
Defect. In case any 8 byte value has value more than 2^63 buffer.readUInt64() fails

### ISSUE THREAD

**Issue by ndimitry** [hierynomus/smbj#237]
Since buffer.readUInt64() reads unsigned int64 (long) value and tries to put it into the Java long value (which is signed), we have problems in case asyncId (or messageId) has a value more than 2^63.

Suggestion — I guess we may store 2 long values instead of 1 long value. Or just deal with the signed values (which, I hope, shouldn't be a problem since integer overflow should deal with this).

Stacktrace (appeared while trying to apply a watch on a directory, failed during an attempt to parse the asyncId inside the response header):

Caused by: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Cannot handle values > 9223372036854775807
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
	... 1 more
Caused by: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Cannot handle values > 9223372036854775807
	at com.hierynomus.protocol.commons.buffer.Endian$Little.readUInt64(Endian.java:244)
	at com.hierynomus.protocol.commons.buffer.Buffer.readUInt64(Buffer.java:506)
	at com.hierynomus.protocol.commons.buffer.Buffer.readUInt64(Buffer.java:495)
	at com.hierynomus.mssmb2.SMB2Header.readFrom(SMB2Header.java:175)
	at com.hierynomus.mssmb2.SMB2Packet.read(SMB2Packet.java:108)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:79)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:50)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:85)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:26)
	at com.hierynomus.smbj.connection.Connection$DelegatingSMBMessageConverter.read(Connection.java:453)
	at com.hierynomus.smbj.connection.Connection$DelegatingSMBMessageConverter.read(Connection.java:442)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readPacket(DirectTcpPacketReader.java:42)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:49)
	... 3 more

**Comment by pepijnve** [comment]
Overflow checking is actually harmful in this particular case. The numeric value of the ids doesn't really matter; it's not that you ever do arithmetic on them. The only thing that matters is that the 64-bits of the value are captured correctly. Rather than using two longs I would be inclined to use read/putInt32/64 instead in this code.

**Comment by ndimitry** [comment]
@pepijnve do you mean just read without checking the overflow? I.e. we get asyncId set to 2^64-1, we read this value into the long (signed 64-bit) and get simply -1. An this, actually, shouldn't matter much if we are able to write it correctly back to the buffer. Is this correct?
(If yes I may create a pull request soon)

**Comment by pepijnve** [comment]
> do you mean just read without checking the overflow

Indeed. Read/write it as a 64-bit signed value instead of an unsigned one. For ids, where binary equality is all that matters, this is not a problem. This is under the assumption that there's no need for ordering (greater/less than) on these ids and no need to do addition/subtraction/... on them. I'm pretty sure that's not the case.

**Comment by pepijnve** [comment]
Just did a quick check. As far as I can tell these ids are only ever used as keys in hash tables. Should be fine to read them as signed values.

**Comment by ndimitry** [comment]
Lets see tomorrow... (:
Thank you for a hint!

**Comment by hierynomus** [comment]
should be fixed now :)

**Comment by ndimitry** [comment]
Thanks for a fast reaction!
