### ISSUE TITLE
java.lang.NoSuchFieldError: microsoft

### ISSUE THREAD

**Issue by manasBelekar** [hierynomus/smbj#264]
I am trying to integrate smbj with my code. As a starter, I am trying to run a simple connect program, but could able to succeed. The execution showing connected to server. and fails there after. Although I am not sure about the connectivity as well.

.<img width="563" alt="code1" src="https://user-images.githubusercontent.com/23233930/33888397-44294478-dee0-11e7-9880-46f0efb50d23.png">

I am getting following error
Exception in thread "main" java.lang.NoSuchFieldError: microsoft
	at com.hierynomus.smbj.auth.NtlmAuthenticator.<clinit>(NtlmAuthenticator.java:46)
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:59)
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:50)
	at com.hierynomus.smbj.connection.Connection.getAuthenticator(Connection.java:220)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:159)
	at com.Sample.main(Sample.java:22)

Full stacktrace:
![stacktrace](https://user-images.githubusercontent.com/23233930/33888722-372768d0-dee1-11e7-8049-e696b21d1fd9.jpg)

**Comment by pepijnve** [comment]
PR #265 will fix this particular issue, but the root cause is probably a bouncycastle version mismatch. SMBJ is compiled against version `1.57`. Could you check which version you're using in your project?

**Comment by manasBelekar** [comment]
HI @pepijnve,

I am using the same version :- bcprov-jdk15on-1.57.jar

**Comment by manasBelekar** [comment]
Thanks
