### ISSUE TITLE
With smbj-0.5.0.jar, i am getting Could not initialize class com.hierynomus.smbj.auth.NtlmAuthenticator error while connection.authenticate(ac)

### ISSUE THREAD

**Issue by harisingh-highq** [hierynomus/smbj#269]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.hierynomus.smbj.auth.NtlmAuthenticator
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:59)
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:50)
	at com.hierynomus.smbj.connection.Connection.getAuthenticator(Connection.java:220)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:159)

**Comment by harisingh-highq** [comment]
Hi @hierynomus 
I have tried with below code
private Connection getSmbjRepoConn() throws Exception
	{
		SMBClient client = new SMBClient();
		Map<String,String> mapParam=repDBO.getParams();
		Connection connection = client.connect(mapParam.get(HybridConstants.SMBJ_HOST).trim());
		return connection;
	}
	private Session getSmbjConnectionSession(Connection connection) throws Exception
	{
		Map<String,String> mapParam=repDBO.getParams();
		AuthenticationContext ac = new AuthenticationContext(mapParam.get(HybridConstants.SMBJ_USERNAME).trim(), mapParam.get(HybridConstants.SMBJ_PASSWORD).toCharArray(), "");
		Session session = connection.authenticate(ac);
		return session;
	}
on execution of line Session session = connection.authenticate(ac); 
i got above error

**Comment by hierynomus** [comment]
What is the deepest `caused by` of the stacktrace. It says `NoClassDefFoundError`, which means a class is missing on your classpath.

**Comment by harisingh-highq** [comment]
One of the cause is
/-- Encapsulated exception ------------\
java.lang.NoSuchFieldError: microsoft
	at com.hierynomus.smbj.auth.NtlmAuthenticator.<clinit>(NtlmAuthenticator.java:46)
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:59)
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:50)
	at com.hierynomus.smbj.connection.Connection.getAuthenticator(Connection.java:220)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:159)
	at com.hybridintegration.repository.SMBJRepo.getSmbjConnectionSession(SMBJRepo.java:1015)

**Comment by pepijnve** [comment]
Sounds like #264. The issue there was incorrect versions of the bouncy castle jars in the class path.

**Comment by hierynomus** [comment]
My thoughts exactly. Please check you BC libraries. Also check your JDK. If in doubt try with a clean-slate JDK.

**Comment by harisingh-highq** [comment]
@pepijnve and @hierynomus 
Thanks for your help.
Yes, there was duplicate bouncy castle jars available in my project.

**Comment by harisingh-highq** [comment]
Closing this tikit.
