### ISSUE TITLE
StringIndexOutOfBoundsException when shareName or path are empty

### ISSUE THREAD

**Issue by mtamassia** [hierynomus/smbj#285]
Current  _SmbPath.toUncPath()_ code only checks for nulls and under certain conditions empty values can occur.  I will submit a PR later on changing the code to also check for empty values.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.hierynomus.smbj.common.SmbPath.toUncPath(SmbPath.java:56)
	at com.hierynomus.smbj.common.SmbPath.toString(SmbPath.java:69)
```

**Comment by mtamassia** [comment]
PR #286

**Comment by hierynomus** [comment]
Closing this as #286 has been merged.
