### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Jomme5** [hierynomus/smbj#293]
At instruction `SMBClient client = new SMBClient();` as example on github. Compiling works, solely error on runtime. 

1. Android Studio 3.0.1
2. Java version: 1.8.0_161
3. Device: Android 7.0

AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.cornmo.moprac.moprac, PID: 30722
                                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
                                                                              at com.hierynomus.smbj.SMBClient.<clinit>(SMBClient.java:124)
                                                                              at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:31)
                                                                              at android.view.View.performClick(View.java:5612)
                                                                              at android.view.View$PerformClick.run(View.java:22288)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "org.slf4j.LoggerFactory" on path: DexPathList[[zip file "/data/app/com.cornmo.moprac.moprac-1/base.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.cornmo.moprac.moprac-1/lib/arm, /system/lib, /vendor/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                              at com.hierynomus.smbj.SMBClient.<clinit>(SMBClient.java:124) 
                                                                              at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:31) 
                                                                              at android.view.View.performClick(View.java:5612) 
                                                                              at android.view.View$PerformClick.run(View.java:22288) 
                                                                              at android.os.Handler.handleCallback(Handler.java:751) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by swaechter** [comment]
smbj internally uses a logger that has to be provided (You can chose the implementation according to your needs).

You can use a normal one:

```
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-simple</artifactId>
	<version>1.7.25</version>
</dependency>
```
Or use the NOP (No operation) dummy implementation:

```
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-nop</artifactId>
	<version>1.7.25</version>
</dependency>
```
For more information take a look at https://www.slf4j.org/manual.html

**Comment by Jomme5** [comment]
1. Do I have to import slj4 manually in my android project? 
2. Do I have to change any of these in POM.xml?

  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.25</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <version>1.57</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>net.engio</groupId>
      <artifactId>mbassador</artifactId>
      <version>1.3.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>

**Comment by hierynomus** [comment]
slf4j-api is just an API, maven will fetch that as a transitive dependency.
However you also need an implementation such as slf4j-simple, logback etc.

2018-02-15 11:51 GMT+01:00 Jomme5 <notifications@github.com>:

**Comment by Jomme5** [comment]
Added this line to build.gradle: 
// https://mvnrepository.com/artifact/org.slf4j/slf4j-simple
testCompile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'

Got the same runtime error.

**Comment by hierynomus** [comment]
Correct, because the testCompile configuration is only  taken into account
during testing, not during production runtime.

Op 16 feb. 2018 12:14 a.m. schreef "Jomme5" <notifications@github.com>:

**Comment by Jomme5** [comment]
And now the simple, short and easy answer - add just those two lines in app/build.gradle:

```
    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
    implementation group: 'com.hierynomus', name: 'smbj', version: '0.6.0'
```
