### ISSUE TITLE
java.lang.ClassNotFoundException: sun.security.provider.MD4

### ISSUE THREAD

**Issue by Jomme5** [hierynomus/smbj#295]
Something about a JRE-whitelist it seems. What is the solution? Runtime error 
 on this line: 
`                    AuthenticationContext ac = new AuthenticationContext("user", "pass".toCharArray(), "");
                    Session session = connection.authenticate(ac);`
after successful connection to the server.

02-18 23:28:20.830 15375-15375/com.cornmo.moprac.moprac E/Verbose: com.hierynomus.ntlm.NtlmException: com.hierynomus.security.SecurityException: java.lang.ClassNotFoundException: sun.security.provider.MD4
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv1(NtlmFunctions.java:96)
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv2(NtlmFunctions.java:61)
                                                                       at com.hierynomus.smbj.auth.NtlmAuthenticator.authenticate(NtlmAuthenticator.java:94)
                                                                       at com.hierynomus.smbj.connection.Connection.processAuthenticationToken(Connection.java:200)
                                                                       at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:171)
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.onClick(Headof.java:42)
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.access$dispatch(Headof.java)
                                                                       at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:0)
                                                                       at android.view.View.performClick(View.java:5612)
                                                                       at android.view.View$PerformClick.run(View.java:22288)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                    Caused by: com.hierynomus.security.SecurityException: java.lang.ClassNotFoundException: sun.security.provider.MD4
                                                                       at com.hierynomus.security.jce.JceMessageDigest.tryMd4(JceMessageDigest.java:59)
                                                                       at com.hierynomus.security.jce.JceMessageDigest.<init>(JceMessageDigest.java:40)
                                                                       at com.hierynomus.security.jce.JceSecurityProvider.getDigest(JceSecurityProvider.java:44)
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv1(NtlmFunctions.java:92)
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv2(NtlmFunctions.java:61) 
                                                                       at com.hierynomus.smbj.auth.NtlmAuthenticator.authenticate(NtlmAuthenticator.java:94) 
                                                                       at com.hierynomus.smbj.connection.Connection.processAuthenticationToken(Connection.java:200) 
                                                                       at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:171) 
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.onClick(Headof.java:42) 
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.access$dispatch(Headof.java) 
                                                                       at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:0) 
                                                                       at android.view.View.performClick(View.java:5612) 
                                                                       at android.view.View$PerformClick.run(View.java:22288) 
                                                                       at android.os.Handler.handleCallback(Handler.java:751) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
                                                                    Caused by: java.lang.ClassNotFoundException: sun.security.provider.MD4
                                                                       at java.lang.Class.classForName(Native Method)
                                                                       at java.lang.Class.forName(Class.java:400)
                                                                       at java.lang.Class.forName(Class.java:326)
                                                                       at com.hierynomus.security.jce.JceMessageDigest.tryMd4(JceMessageDigest.java:56)
                                                                       at com.hierynomus.security.jce.JceMessageDigest.<init>(JceMessageDigest.java:40) 
                                                                       at com.hierynomus.security.jce.JceSecurityProvider.getDigest(JceSecurityProvider.java:44) 
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv1(NtlmFunctions.java:92) 
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv2(NtlmFunctions.java:61) 
                                                                       at com.hierynomus.smbj.auth.NtlmAuthenticator.authenticate(NtlmAuthenticator.java:94) 
                                                                       at com.hierynomus.smbj.connection.Connection.processAuthenticationToken(Connection.java:200) 
                                                                       at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:171) 
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.onClick(Headof.java:42) 
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.access$dispatch(Headof.java) 
                                                                       at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:0) 
                                                                       at android.view.View.performClick(View.java:5612) 
                                                                       at android.view.View$PerformClick.run(View.java:22288) 
                                                                       at android.os.Handler.handleCallback(Handler.java:751) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "sun.security.provider.MD4" on path: DexPathList[[zip file "/data/app/com.cornmo.moprac.moprac-2/base.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.cornmo.moprac.moprac-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.cornmo.moprac.moprac-2/lib/arm, /system/lib, /vendor/lib]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at java.lang.Class.classForName(Native Method) 
                                                                       at java.lang.Class.forName(Class.java:400) 
                                                                       at java.lang.Class.forName(Class.java:326) 
                                                                       at com.hierynomus.security.jce.JceMessageDigest.tryMd4(JceMessageDigest.java:56) 
                                                                       at com.hierynomus.security.jce.JceMessageDigest.<init>(JceMessageDigest.java:40) 
                                                                       at com.hierynomus.security.jce.JceSecurityProvider.getDigest(JceSecurityProvider.java:44) 
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv1(NtlmFunctions.java:92) 
                                                                       at com.hierynomus.ntlm.functions.NtlmFunctions.NTOWFv2(NtlmFunctions.java:61) 
                                                                       at com.hierynomus.smbj.auth.NtlmAuthenticator.authenticate(NtlmAuthenticator.java:94) 
                                                                       at com.hierynomus.smbj.connection.Connection.processAuthenticationToken(Connection.java:200) 
                                                                       at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:171) 
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.onClick(Headof.java:42) 
                                                                       at com.cornmo.moprac.moprac.Headof$1$override.access$dispatch(Headof.java) 
                                                                       at com.cornmo.moprac.moprac.Headof$1.onClick(Headof.java:0) 
                                                                       at android.view.View.performClick(View.java:5612) 
                                                                       at android.view.View$PerformClick.run(View.java:22288) 
                                                                       at android.os.Handler.handleCallback(Handler.java:751) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by hierynomus** [comment]
The Bouncycastle replacement for Android is 'Spongycastle'. You will need to implement your own SecurityProvider which uses Spongycastle, but that should be relatively straightforward.

**Comment by hierynomus** [comment]
The reason this happens with JCE is that MD4 has been deprecated for a long time, but unfortunately it is required by the NTLM protocol.

**Comment by Jomme5** [comment]
Does your library wraps jcifs? Otherwise I will turn tot that one.

**Comment by pepijnve** [comment]
> Does your library wraps jcifs?

No, they're two very different libraries. JCIFS supports SMB/CIFS 1.0 and earlier. SMBJ  supports SMB 2.x.

**Comment by pepijnve** [comment]
@hierynomus jcifs ships contains a custom MD4 implementation. Perhaps that should be considered for SMBJ as well?

**Comment by hierynomus** [comment]
Is there a public domain one somewhere? It would be a good option yes 👍

**Comment by pepijnve** [comment]
http://openwall.info/wiki/people/solar/software/public-domain-source-code/md4 ?

**Comment by pepijnve** [comment]
@hierynomus bouncy castle is MIT licensed, so I think it's okay to inline their implementation. Here's a standalone version I lifted from the library. Haven't had the time to test this thoroughly yet.

[MD4.txt](https://github.com/hierynomus/smbj/files/1736498/MD4.txt)

**Comment by hierynomus** [comment]
Judging from the license header it should be allowed indeed. Let's add it instead of relying on the sun internal class.

**Comment by pepijnve** [comment]
I put the license header there :) Based on the statement

> Except where otherwise stated, software produced by this site is covered by the [following license](http://bouncycastle.org/license.html).

at http://bouncycastle.org/java.html which points to http://bouncycastle.org/license.html

**Comment by Jomme5** [comment]
In the mean time: 
https://stackoverflow.com/questions/41494357/accessing-smb2-1-or-smb3-share-from-java

**Comment by hierynomus** [comment]
MD4 has been incorporated as a specific digest, closing this one.
