### ISSUE TITLE
DFS resolving fails when referral cache has expired

### ISSUE THREAD

**Issue by andershermansen** [hierynomus/smbj#310]
Opening files on a DFS share is working fine except until the referral cache has expired. In my case this happened after 5 minutes. Then I got an IllegalStateException.

Note that in the log below the line numbers in DFSPathResolver might be a bit off since I added some lines in step3 to use a targetPath from one item in the TargetList instead of from the TargetHint to work around issue #254 

```
11:21:43.581 [main] INFO  c.h.smbj.paths.DFSPathResolver - DFS Share myshare does not cover \\myserver.local\myshare\something\something\myfile.txt, resolve through DFS
11:21:43.581 [main] INFO  c.h.smbj.paths.DFSPathResolver - Starting DFS resolution for \\myserver.local\myshare\something\something\myfile.txt
11:21:43.584 [main] INFO  com.hierynomus.smbj.session.Session - Logging off session 4452203364769 from host myserver.local
11:21:43.588 [main] INFO  c.h.smbj.connection.Connection - Closed connection to myserver.local
java.lang.RuntimeException: java.lang.IllegalStateException: Could not find referral cache entry for DFSPath{[myserver.local, myshare]}
        at xxx.mycode.xxx
        at xxx.mycode.xxx
        at xxx.mycode.xxx
        at xxx.mycode.xxx
        at xxx.mycode.xxx
Caused by: java.lang.IllegalStateException: Could not find referral cache entry for DFSPath{[myserver.local, myshare]}
        at com.hierynomus.smbj.paths.DFSPathResolver.step9(DFSPathResolver.java:299)
        at com.hierynomus.smbj.paths.DFSPathResolver.step2(DFSPathResolver.java:128)
        at com.hierynomus.smbj.paths.DFSPathResolver.step1(DFSPathResolver.java:108)
        at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:95)
        at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:76)
        at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:82)
        at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:69)
        at xxx.mycode.xxx
        at xxx.mycode.xxx
        at xxx.mycode.xxx
        at xxx.mycode.xxx
        ... 3 more
11:21:43.598 [Packet Reader for myserver.local] INFO  c.h.smbj.transport.PacketReader - Thread[Packet Reader for myserver.local,5,main] stopped.
```

**Comment by hierynomus** [comment]
This was fixed with #474
