### ISSUE TITLE
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by misaghE** [hierynomus/smbj#317]
When I run the code on Android API level 18, I get the following exception:

`Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
                                                                             at com.hierynomus.mssmb.messages.SMB1ComNegotiateRequest.writeTo(SMB1ComNegotiateRequest.java:59)
                                                                             at com.hierynomus.mssmb.SMB1Packet.write(SMB1Packet.java:30)
                                                                             at com.hierynomus.mssmb.SMB1Packet.write(SMB1Packet.java:22)
                                                                             at com.hierynomus.smbj.connection.SMBPacketSerializer.write(SMBPacketSerializer.java:26)
                                                                             at com.hierynomus.smbj.connection.SMBPacketSerializer.write(SMBPacketSerializer.java:22)
                                                                             at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:71)
                                                                             at com.hierynomus.smbj.connection.Connection.multiProtocolNegotiate(Connection.java:326)
                                                                             at com.hierynomus.smbj.connection.Connection.negotiateDialect(Connection.java:298)
                                                                             at com.hierynomus.smbj.connection.Connection.connect(Connection.java:115)
                                                                             at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:102)
                                                                             at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:76)`

And this is because of `StandardCharsets` is added on API level 19.

The line that cause the problem is:
`Connection connection = client.connect(sambaIP);`

Is there any way that I can run the code on API level 18?

**Comment by pepijnve** [comment]
> Is there any way that I can run the code on API level 18?

Not without code changes in the library. API level 18 dates back to somewhere in 2013; not sure if there's any intrest in actually supporting this.

@hierynomus what's your pov regarding Android support? Is it something you would want to intentionally support? If so, which API version would you want to target?
If you want to support this, adding an Android configuration to the travis scripts might be a good starting point. That would at least catch this type of issue.

**Comment by hierynomus** [comment]
I know SMBJ is used by several Android apps already. I'm in favour of supporting Android as first class system. I would suggest we see what the minimum version is that we can support without code changes and work our way from there.

Are there animalsniffer definitions available for Android?

**Comment by pepijnve** [comment]
> Are there animalsniffer definitions available for Android?

Don't know. You could just try to compile against an API level and see if it succeeds or not. Travis seems to have pretty good Android support these days that allows you to do exactly that.

**Comment by hierynomus** [comment]
How is travis with mixing and matching android and java compilation/tests?
Never tried that actually.

2018-04-24 13:10 GMT+02:00 Pepijn Van Eeckhoudt <notifications@github.com>:

**Comment by pepijnve** [comment]
I'll make a PR for this to show how it could be done

**Comment by hierynomus** [comment]
I think with #327 we can now close this.
