### ISSUE TITLE
Throwing "Cannot write SMB2_SESSION_SETUP with message id << 1 >> as transport is disconnected" error while try to authenticate session with SMBJ server

### ISSUE THREAD

**Issue by harisingh-highq** [hierynomus/smbj#338]
Hi @hierynomus & @pepijnve 
I got below exception while test the smbj connection. It throws an error when try to run this lines of code:- `Session session = connection.authenticate(ac);`

**Below is a exception stack trace for more details**
`com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 1 >> as transport is disconnected
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:191)
	at com.hybridintegration.repository.SMBJRepo.getSmbjConnectionSession(SMBJRepo.java:1094)
	at com.hybridintegration.repository.SMBJRepo.testConnection(SMBJRepo.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.hybridintegration.servlet.FileUploadServlet.testConnection(FileUploadServlet.java:783)
	at com.hybridintegration.servlet.FileUploadServlet.uploadFileOpr(FileUploadServlet.java:738)
	at com.hybridintegration.servlet.FileUploadServlet.doPost(FileUploadServlet.java:563)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hqaHybrid.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:84)
	at org.springframework.web.filter.O`

**Comment by niravravalhighq** [comment]
Hi @jborza ,
This is regarding Windows Server.

**Comment by hierynomus** [comment]
@niravravalhighq What is the debug or trace level logging? Only the stacktrace provides no clue to me what is going wrong. Also what does your code look like?

**Comment by hierynomus** [comment]
Ahh that should've been @harisingh-highq.

**Comment by harisingh-highq** [comment]
@hierynomus 
I am not able to replicate it again.

As i came to know that it may be throwing due to some unexpected behavior in our api call flow.
So for now, you can close this tikit. If we get same error in future, then we will do investigate.

Thanks

**Comment by hierynomus** [comment]
Ok, closed the ticket.
