### ISSUE TITLE
IndexOutOfBoundsException when resolving DFS referral response

### ISSUE THREAD

**Issue by dwissk** [hierynomus/smbj#339]
Version: 0.7.0 from maven central

When [accessing the the first referral entry of a DFS root referral response](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/msdfsc/ReferralCache.java#L114) an `IndexOutOfBoundsException` is thrown.

Stacktrace:
`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.hierynomus.msdfsc.ReferralCache$ReferralCacheEntry.<init>(ReferralCache.java:114)
	at com.hierynomus.smbj.paths.DFSPathResolver.handleRootOrLinkReferralResponse(DFSPathResolver.java:434)
	at com.hierynomus.smbj.paths.DFSPathResolver.handleReferralResponse(DFSPathResolver.java:421)
	at com.hierynomus.smbj.paths.DFSPathResolver.getReferral(DFSPathResolver.java:402)
	at com.hierynomus.smbj.paths.DFSPathResolver.sendDfsReferralRequest(DFSPathResolver.java:390)
	at com.hierynomus.smbj.paths.DFSPathResolver.step6(DFSPathResolver.java:225)
	at com.hierynomus.smbj.paths.DFSPathResolver.step5(DFSPathResolver.java:186)
	at com.hierynomus.smbj.paths.DFSPathResolver.step2(DFSPathResolver.java:124)
	at com.hierynomus.smbj.paths.DFSPathResolver.step1(DFSPathResolver.java:107)
	at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:94)
	at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:75)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:82)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:92)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:70)
	at com.hierynomus.smbj.share.DiskShare.exists(DiskShare.java:173)
	at com.hierynomus.smbj.share.DiskShare.folderExists(DiskShare.java:169)
`

It seems to me a [simple return or else branch is missing](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/paths/DFSPathResolver.java#L433) as the array is checked for emptyness right before it is converted to a ReferralCacheEntry, but then again I don't have the big picture... Is the fix really as simple as it seems, or am I missing something?

Trace Log File (with lots of successful referral responses and the unsuccessful one at the bottom)
[smbj-0.7.0-referral-response-trace.log](https://github.com/hierynomus/smbj/files/2094237/smbj-0.7.0-referral-response-trace.log)

Any hints would be greatly appreciated

**Comment by hierynomus** [comment]
thanks for finding the bug. Fixed now on master!

**Comment by dwissk** [comment]
thanks @hierynomus for this quick reaction.

the customer meanwhile has reported that the affected referral link is *deactivated* in the DFS management console.

<img width="325" alt="screen shot 2018-06-13 at 17 28 04" src="https://user-images.githubusercontent.com/3786617/41361402-3f5d2588-6f2f-11e8-83d4-e9f8faed91d6.png">

Now, with the added return statement on the master branch, the problem is only moved (at least when listing directory contents)

`
java.lang.NullPointerException: null
	at com.hierynomus.smbj.share.DiskShare.getDiskEntry(DiskShare.java:112)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:71)
	at com.hierynomus.smbj.share.DiskShare.exists(DiskShare.java:173)
	at com.hierynomus.smbj.share.DiskShare.folderExists(DiskShare.java:169)
`

I think the proper way to handle this is to throw a `new PathResolveException(NtStatus.STATUS_OBJECT_PATH_NOT_FOUND)` because this is an acceptable exception code in [DiskShare.openDirectory](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L169) meaning the affected directory will simply not be listed

(Side note: the MacOS Finder SMB client DOES list the directory, but not its contents. However, I find not listing a *deactivated* referral link is fine)

I have opened PR #340 as a suggestion
