### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#359]
Hi,
  How can I set the timeout when reading from a connection ? 
Which are the defaults and which timeouts can be set  ?  

I got  this exception very soon when reading a file
com.hierynomus.protocol.transport.TransportException: java.net.SocketTimeoutException: Read timed out
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
	... 3 more

**Comment by pepijnve** [comment]
Should be possible using `SmbConfig.Builder#withReadTimeout`.

**Comment by cliviu** [comment]
What is the default behavior when nothing is set ?

**Comment by pepijnve** [comment]
https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/SmbConfig.java#L39

**Comment by cliviu** [comment]
Thanks !

**Comment by cliviu** [comment]
I get always these Exceptions, also when the application is idle
2018-07-17 15:15:03,399|Session             |ERROR|Caught exception while closing TreeConnect with id: 1
com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:29)
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:23)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:43)
	at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:66)
	at com.hierynomus.smbj.share.Share.close(Share.java:91)
	at com.hierynomus.smbj.session.Session.logoff(Session.java:211)
	at com.hierynomus.smbj.session.Session.close(Session.java:244)
	at com.hierynomus.smbj.connection.Connection.close(Connection.java:136)
	at com.hierynomus.smbj.connection.Connection.close(Connection.java:121)
	at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:428)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:53)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired
	at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:60)
	at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:84)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
	... 9 more
Caused by: com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
	at com.hierynomus.protocol.commons.concurrent.Promise.retrieve(Promise.java:136)
	at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:58)
	... 11 more
Caused by: java.util.concurrent.TimeoutException: Timeout expired
	... 13 more

**Comment by cliviu** [comment]
The problem occurs only when I set soTimeout to a value > 0.  Did anybody encountered such problems when setting the soTimeout ?

**Comment by hierynomus** [comment]
Yes, when `soTimeout` is `<0`, it will wait infinitely. Anything `>0` will actually make it time out eventually. The question is where is the `TimeoutException` coming from? Which operation was it doing when it was idling?

**Comment by cliviu** [comment]
hmm, it was doing nothing .... I have found no stack trace where any application thread was involved...

**Comment by hierynomus** [comment]
@cliviu is this one related to #365 or not?

**Comment by cliviu** [comment]
No

**Comment by xiaobeixingxing** [comment]
I also met the same problem. I set the timeout time to 60000, but there is still an exception.
