### ISSUE TITLE
NoClassDefFoundError related to ASN1ObjectIdentifier

### ISSUE THREAD

**Issue by LightLink12** [hierynomus/smbj#376]
Could you please suggest resolution for NoClassDefFoundError related to ASN1ObjectIdentifier.
I got the following error with smbj-0.8.0.jar

java.lang.NoClassDefFoundError: org/bouncycastle/asn1/ASN1ObjectIdentifier
	at com.hierynomus.smbj.auth.NtlmAuthenticator.<clinit>(NtlmAuthenticator.java:46)
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:58)
	at com.hierynomus.smbj.auth.NtlmAuthenticator$Factory.create(NtlmAuthenticator.java:1)
	at com.hierynomus.smbj.connection.Connection.getAuthenticator(Connection.java:240)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:160)
...
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.ASN1ObjectIdentifier
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

I use jdk1.8.0_152 on Windows7 (32bit).
And I set jar files on lib/ ...
 slf4j-api-1.7.25.jar
 slf4j-simple-1.7.25.jar
 bcprov-jdk15on-160.jar
 mbassador-1.3.2.jar

Of course I set the following messages on pom.xml
 <dependency>
	<groupId>com.hierynomus</groupId>
	<artifactId>smbj</artifactId>
	<version>0.8.0</version>
 </dependency>

The related src is as follows;

SmbConfig config = SmbConfig.builder() .build();
SMBClient client = new SMBClient(config);
Connection connection = null;
AuthenticationContext ac = null;
Session session = null;
try {
	connection = client.connect("serverIP");
	ac = new AuthenticationContext("username", "userpass".toCharArray(), null);

	session = connection.authenticate(ac);  <-- error occurring

	// Connect to Share
	try (DiskShare share = (DiskShare) session.connectShare("SHARENAME")) {
		...
	}
} catch (NoClassDefFoundError e) {
	e.printStackTrace();
} finally {
	try {
		if (connection != null)
			connection.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}

**Comment by LightLink12** [comment]
I resolved it.

I set "package" on Goals field of Maven Run Configuration dialog.
And then I did Maven clean and build again.
