### ISSUE TITLE
Buffer underflow exception

### ISSUE THREAD

**Issue by gillyx** [hierynomus/smbj#40]
After the initial negociation, it seems the GssNegotiateToken is empty - see trace below.
Any clue of what that means / how to trouble shoot ?

Thanks!

```
Publication error handlers can be added by IBusConfiguration.addPublicationErrorHandler()
Falling back to console logger.
18:00:01.630 [main] INFO  c.h.p.c.socket.ProxySocketFactory - Connecting to xxxx.file.net/x.y.z.w:445
18:00:01.637 [main] DEBUG c.h.smbj.transport.PacketReader - Starting PacketReader on thread: Packet Reader for xxxx.file.net
18:00:01.638 [main] INFO  c.h.smbj.connection.Connection - Negotiating dialects [SMB_2_0_2, SMB_2_1] with server xxxx.file.net
18:00:01.642 [main] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 0 >>
18:00:01.647 [main] DEBUG c.h.s.t.tcp.DirectTcpTransport - Writing packet << SMB2_NEGOTIATE >>, sequence number << 0 >>
18:00:01.650 [main] DEBUG c.hierynomus.smbj.connection.Request - Retrieving value for Future << 0 >>
18:00:01.650 [main] DEBUG c.h.p.commons.concurrent.Promise - Awaiting << 0 >>
18:00:01.657 [Packet Reader for xxxx.file.net] DEBUG c.h.smbj.transport.PacketReader - Received packet << com.hierynomus.mssmb2.messages.SMB2NegotiateResponse@79
668511 >>
18:00:01.657 [Packet Reader for xxxx.file.net] DEBUG c.h.smbj.connection.Connection - Server granted us 1 credits for message with sequence number << 0 >>, now a
vailable: 1 credits
18:00:01.658 [Packet Reader for xxxx.file.net] DEBUG c.h.p.commons.concurrent.Promise - Setting << 0 >> to `com.hierynomus.mssmb2.messages.SMB2NegotiateResponse@
79668511`
18:00:01.659 [main] INFO  c.h.smbj.connection.Connection - Negotiated the following connection settings: ConnectionInfo{
  serverGuid=ecf196d4-50f8-4bde-8e99-33210c279d0c,
  serverName='xxxx.file.net',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_2_1, maxTransactSize=1048576, maxReadSize=1048576, maxWriteSize=1048576},
  clientGuid=70559866-0c21-4ddd-82d4-f2f04fb8b4d8,
  clientCapabilities=null,
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=0,
  serverSecurityMode=3,
  server='null'
}
18:00:01.659 [main] INFO  c.h.smbj.connection.Connection - Successfully connected to: xxxx.file.net
18:00:01.659 [main] INFO  c.h.smbj.connection.Connection - GssNegotiateToken - len: 0
com.hierynomus.smbj.common.SMBRuntimeException: java.io.IOException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
        at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:146)
        at SmbjTest.testBasic(SmbjTest.java:88)
        at SmbjMain.main(SmbjMain.java:20)
Caused by: java.io.IOException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
        at com.hierynomus.protocol.commons.buffer.Buffer$1.read(Buffer.java:686)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
        at com.hierynomus.spnego.NegTokenInit.read(NegTokenInit.java:105)
        at com.hierynomus.spnego.NegTokenInit.read(NegTokenInit.java:100)
        at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:118)
        ... 2 more
Caused by: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
        at com.hierynomus.protocol.commons.buffer.Buffer.ensureAvailable(Buffer.java:183)
        at com.hierynomus.protocol.commons.buffer.Buffer.readByte(Buffer.java:252)
        at com.hierynomus.protocol.commons.buffer.Buffer$1.read(Buffer.java:684)
        ... 7 more
```

**Comment by hierynomus** [comment]
Which version of smbj are you running? And to what kind  of server are you
connecting?

Op 23 mrt. 2017 7:29 p.m. schreef "gillyx" <notifications@github.com>:

**Comment by gillyx** [comment]
I compiled from HEAD and it gives me smbj-0.0.8.
Server is Microsoft on Azure Files.

**Comment by gillyx** [comment]
I added some trace in `DirectTcpPacketReader.doRead` and see `_readTcpHeader()` always returns 128. 
That explains at least why the packet couldn't be fully read.

**Comment by hierynomus** [comment]
Actually the packet was fully read, else you would've gotten an exception
from the packet deserialization that it missed a few bytes.

However I think that the server you're connecting with triggers the
following case:

2.2.4 SMB2 NEGOTIATE Response  - Buffer
The buffer SHOULD contain a token as produced by the GSS protocol as
specified in section 3.3.5.4. If SecurityBufferLength is 0, this field is
empty and then client-initiated authentication, with an authentication
protocol of the client's choice, will be used instead of server-initiated
SPNEGO authentication as described in [MS-AUTHSOD] section 2.1.2.2.

I have not yet covered this case, but will have a look at it tomorrow if
time permits.

2017-03-23 23:36 GMT+01:00 gillyx <notifications@github.com>:

**Comment by hierynomus** [comment]
Can you try with the code from the PR? I _think_ this should fix it :)

**Comment by gillyx** [comment]
Thanks for the quick response and fix!

That worked.

The ```SmbjTest``` integration test is now running though I had to comment the code in the test dealing with DACL in security descriptor since it's null.
The Security descriptor looks as ```SecurityDescriptor{control=[PS, OD], ownerSid=S-1-1-0, groupSid=S-1-1-0, sacl=null, dacl=null}```

**Comment by gillyx** [comment]
Just a side note that maybe in ```com.hierynomus.smbj.transport.PacketReader``` the constructor should set the thread to be a daemon otherwise the JVM won't exit if the connection is not closed.

**Comment by hierynomus** [comment]
Yes, thanks for the suggestion. Missed that. Will fix

Op 24 mrt. 2017 5:42 p.m. schreef "gillyx" <notifications@github.com>:
