### ISSUE TITLE
NonDFS location throws ClassCast exception with 0.9 version

### ISSUE THREAD

**Issue by samrajcse** [hierynomus/smbj#400]
Hi @hierynomus 
Today I have upgraded the latest version and RAN the unit testcase and I am getting below exception with 0.9.0 version.

**Stack trace:**

Exception in thread "Packet Reader for <HostName>" java.lang.ClassCastException: com.hierynomus.smbj.session.PacketSignatory$SignedPacketWrapper cannot be cast to com.hierynomus.mssmb2.messages.SMB2IoctlRequest
	at com.hierynomus.mssmb2.SMB2MessageConverter.isSuccess(SMB2MessageConverter.java:104)
	at com.hierynomus.mssmb2.SMB2MessageConverter.readPacket(SMB2MessageConverter.java:78)
	at com.hierynomus.smbj.connection.Connection.handle(Connection.java:403)
	at com.hierynomus.smbj.connection.Connection.handle(Connection.java:70)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:72)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
	at java.lang.Thread.run(Unknown Source)

**Steps to reproduce:**
Provide the non dfs share location with 

> .withDfsEnabled(true).withMultiProtocolNegotiate(true)

 in SmbConfig for SMBClient class. 

Earlier, it will detect the DFS and non DFS share and it work wthout any intervention or configuration.

**Note**: Above exception is not thrown if we provide the valid DFS location.

**Comment by hierynomus** [comment]
Which unit test did you change? Can you give me the smallest reproducible sample testcase?

**Comment by demboos** [comment]
Got that too:

IntegrationTest.groovy, change the smb config to have .withDfsEnabled(true), run tests.
