### ISSUE TITLE
Smbj dependecy 'mbassador' runtime dependencies (el-api-2.2.jar, juel-spi-2.2.7.jar, juel-impl-2.2.7.jar) conflicting with Websphere Application Server el-api.

### ISSUE THREAD

**Issue by PrateepT** [hierynomus/smbj#407]
Hello,

Smbj dependency 'mbassador' runtime dependencies (el-api-2.2.jar, juel-spi-2.2.7.jar, juel-impl-2.2.7.jar) conflicting with Websphere Application Server el-api (JEE6)

Currently I'm working with smbj-0.7.0 in web application which runs on WebSphere Application Server 8.5.5.11. All the network file operations work normally but when we access PriceFaces application xhtml pages with Ajax listeners the below error is occurring:

**Exception stacktrace:**
_[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R [WebContainer : 2] ERROR colruyt.webutillib.exception.CustomExceptionHandler - /viewMetadata/categoryList.xhtml at line 9 and column 75 listener="#{categoryListBean.prepare }": Cannot find method 'prepare' in 'class colruyt.jeeframetrials.backing.CategoryListBean'
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R **javax.el.MethodNotFoundException: /viewMetadata/categoryList.xhtml at line 9 and column 75 listener="#{categoryListBean.prepare }": Cannot find method 'prepare' in 'class colruyt.jeeframetrials.backing.CategoryListBean'**
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at org.apache.myfaces.view.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:91)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at org.apache.myfaces.view.facelets.tag.jsf.core.EventHandler$Listener.processEvent(EventHandler.java:243)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at javax.faces.component.UIComponent$EventListenerWrapper.processEvent(UIComponent.java:1126)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:43)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at org.apache.myfaces.application.ApplicationImpl._traverseListenerList(ApplicationImpl.java:2230)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at org.apache.myfaces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:561)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at org.apache.myfaces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:591)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at org.apache.webbeans.jsf.OwbApplication.publishEvent(OwbApplication.java:484)
[20/11/18 15:15:26:736 CET] 000000a4 SystemErr     R 	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:72)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:240)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:191)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1233)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:782)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:481)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:97)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at colruyt.webutillib.filter.ResponseBufferFilter.doFilter(ResponseBufferFilter.java:35)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at colruyt.webutillib.session.SessionTimeoutFilter.doFilter(SessionTimeoutFilter.java:65)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at colruyt.webutillib.security.SecurityFilter.doFilter(SecurityFilter.java:147)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3980)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1016)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
[20/11/18 15:15:26:751 CET] 000000a4 SystemErr     R 	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)_

Found few below issues raised on PrimeFaces / Juel and there are workarounds to resolve, below are the links with issue and workaround:

http://juel.sourceforge.net/guide/advanced/index.html
https://github.com/beckchr/juel/issues/80
https://github.com/primefaces/primefaces/issues/1594

But at the same time I would like to use default el-api implementation provided by WebSphere to avoid other side effects in future like migrating to JEE7.

Looked at the features of Juel implementation - https://github.com/bennidi/mbassador, @Filter annotation feature is adding filtering to prevent certain messages from being published and this @Filter annotation feature is using el-api. I see that this (@Filter) annotation is not used in smbj-0.7.0. If I remove the libraries (el-api-2.2.jar, juel-spi-2.2.7.jar, juel-impl-2.2.7.jar) everything works normally and I see the issue is not occurring anymore, all my regression tests are successful. 

Could you please suggest or let me know if there could be any side effects of removing the dependencies?

Thanks,
Prateep.

**Comment by hierynomus** [comment]
@PrateepT We don't use the `@Filter` annotation from mbassador (at this moment). However that is of course no guarantee it will never be used. I would recommend filing an issue with the mbassador team, to see whether they can provide a good workaround.
