### ISSUE TITLE
STATUS_INTERNAL_ERROR (0xc00000e5): QueryInfo failed for SMB2FileId

### ISSUE THREAD

**Issue by nddipiazza** [hierynomus/smbj#410]
We are crawling an extremely massive windows DFS.

When opening a directory, one out of the 10 DFS throws this error:

```
Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_INTERNAL_ERROR (0xc00000e5): QueryInfo failed for SMB2FileId{persistentHandle=c2 b3 19 32 e4 e2 56 7d}
    at com.hierynomus.smbj.share.Share.receive(Share.java:366) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.Share.sendReceive(Share.java:346) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.Share.queryInfo(Share.java:188) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.DiskShare.getFileInformation(DiskShare.java:272) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.DiskEntry.getFileInformation(DiskEntry.java:65) ~[smbj-0.8.5.jar:0.8.5]
    at com.hierynomus.smbj.share.DiskEntry.getFileInformation(DiskEntry.java:61) ~[smbj-0.8.5.jar:0.8.5]
```

How can I figure out what the problem here is? 

Code:

```
try (Directory _folder = share.openDirectory(folderPath, of(GENERIC_READ), null, of(FILE_SHARE_READ), FILE_OPEN, null)) {
   _folder.getFileInformation();
}
```

**Comment by ecki** [comment]
Can you open it with explorer and are there more than one server serving the file?

**Comment by nddipiazza** [comment]
Good question! Will check.

**Comment by pepijnve** [comment]
Error codes like this are reported by the server, so you usually have to go digging in log files on the server side to figure out what's going wrong exactly.
`DiskEnty#getFileInformation` performs a query using the `[FILE_ALL_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_all_information)` info class. I've seen that cause problems on other servers as well. What you could try instead is to query the individual parts of 'all information' using the respective info classes and see which bit is failing.

**Comment by hierynomus** [comment]
Also check the server side logs. They might shed more light on what the cause of the `INTERNAL_ERROR` was.

**Comment by nddipiazza** [comment]
Can't get access to the server logs. not sure what to do here.

**Comment by hierynomus** [comment]
@nddipiazza Any luck obtaining more information? Or was it solved using @pepijnve 's comment?

**Comment by nddipiazza** [comment]
Waiting on wireshark to be installed. Thanks.

**Comment by angoori** [comment]
Were you able to resolve this issue?
