### ISSUE TITLE
exception when connecting to SMBv1

### ISSUE THREAD

**Issue by avi112211** [hierynomus/smbj#412]
Hi,

When I'm trying to connect to SMBv1 the following exception is printed to the console (which is fine):

```
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.mssmb.SMB1NotSupportedException: SMBv1 is not supported by SMBJ
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:95) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:432) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:53) ~[smbj-0.8.0.jar:0.8.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: com.hierynomus.mssmb.SMB1NotSupportedException: SMBv1 is not supported by SMBJ
	at com.hierynomus.mssmb.SMB1MessageConverter.read(SMB1MessageConverter.java:26) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.mssmb.SMB1MessageConverter.read(SMB1MessageConverter.java:23) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.connection.Connection$DelegatingSMBMessageConverter.read(Connection.java:471) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.connection.Connection$DelegatingSMBMessageConverter.read(Connection.java:460) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readPacket(DirectTcpPacketReader.java:42) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:49) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69) ~[smbj-0.8.0.jar:0.8.0]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47) ~[smbj-0.8.0.jar:0.8.0]
	... 1 common frames omitted
```

But, I'm surrounding the connection with try catch, the exception is caught but also printed to the console.
can assist? I don't want it to be printed.

Thanks

**Comment by pepijnve** [comment]
SMBJ itself does not print exceptions. Must be somewhere in your code.

**Comment by hierynomus** [comment]
The SMBv1NotSupportedException is wrapped in an SmbRuntimeException. Are you catching the right one?

**Comment by avi112211** [comment]
this is the code:

SmbConfig cfg = SmbConfig
				.builder()
					.withMultiProtocolNegotiate(true)
					.withDfsEnabled(true)
					.withNegotiatedBufferSize()
				.withSoTimeout(10, TimeUnit.MINUTES)
					.build();
		SMBClient client = new SMBClient(cfg);
		try {
			Connection connection = client.connect(smbIp);
		}catch(SMBRuntimeException | IOException e) {
			System.out.println("error");
		}

It enters the catch, but printing the exception above before "error".

Am I did something wrong?

**Comment by avi112211** [comment]
Can I do something in order to prevent it from printing?

**Comment by pepijnve** [comment]
Set the logging level for `com.hierynomus.smbj.transport.PacketReader` to warn or higher.

**Comment by avi112211** [comment]
@pepijnve I followed your line of thought and set `com.hierynomus.smbj.transport.PacketReader` and `com.hierynomus.protocol.commons.concurrent.Promise` logging level to 'off'. The combination of those two did the trick. Thanks.

**Comment by hierynomus** [comment]
@avi112211 I assume with your latest comment that your problem is solved. I cannot exactly follow why turning off those logger would fix it. As neither `Promise` nor `PacketReader` actually log the exception. Also the uncaught handler of the `PacketReader should not be called upon, as it is delivering the exception to the waiter (i.e. the client, as you can see in `Promise.deliverError`. But feel free to point me to an omission in my thinking.
