### ISSUE TITLE
NPE in DiskShare

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#415]
Hi,  Got NPE with 0.9.1 : Caused by: java.lang.NullPointerException
	at com.hierynomus.smbj.share.DiskShare.getDiskEntry(DiskShare.java:112)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:67)
	at com.hierynomus.smbj.share.DiskShare.exists(DiskShare.java:187)
	at com.hierynomus.smbj.share.DiskShare.folderExists(DiskShare.java:183) 

Last log lines before were : 
2018-12-12 16:47:59,443|DFSPathResolver               |INFO |DFS Share Net-... does not cover \\path1 resolve through DFS
2018-12-12 16:47:59,443|DFSPathResolver               |INFO |Starting DFS resolution for \\path1
2018-12-12 16:47:59,443|DFSPathResolver               |INFO |DFS resolved path1-> path2
   What can be the problem ? 
  Thanks !

**Comment by cliviu** [comment]
Any thoughts about this ? What can cause the problem ?  The NPE occurs in the "if" line : 
    SMB2CreateResponse response = responseContext.resp;
        if (response.getFileAttributes().contains(FILE_ATTRIBUTE_DIRECTORY)) {

Either "response" or the "fileAttributes"  must be null but I'm not sure what kind of external configuration can cause this problem ...

**Comment by cliviu** [comment]
I have another hint: the DFS Resolution returns the same URL when the NPE is thrown ....

**Comment by Disablez** [comment]
This could help...
https://github.com/hierynomus/smbj/pull/474

**Comment by throwinto2** [comment]
I seem to be getting the exact same exception at the exact same code lines. I have multiple DFS shares set up on various servers and it seems like only some encounter this problem. They are all in the same domain, same setup and all shares are set up in the same way.
I sadly cannot pinpoint the cause. At first it looked like the DFS shares on a domain controller were more stable, but this was seemingly fixed in 2017. What seemed to work to a certain extent is creating a new DFS namespace with new shares. Maybe the DFS namespace cache is the cause..
Did #474 and #342 resolve this problem? I'm hoping it will be available in the next version when it is released.

**Comment by davisnw** [comment]
I found that at least in my case, the `NullPointerException` only occurs if I reuse `SmbClient`.  See also #531
