### ISSUE TITLE
Error while connecting to an `IPC$` share

### ISSUE THREAD

**Issue by nddipiazza** [hierynomus/smbj#417]
I am having issues with DFS when there exists an `IPC$` share.

Steps to reproduce:

1. Create a windows share.
2. Enable give `Everyone` access to read the shared folder.
3. Enable DFS and try to list directories.
```
SmbConfig.builder()
      .withDfsEnabled(true)
      .withMultiProtocolNegotiate(true)
      .withTimeout(config.getLong(TIMEOUT_PROP, Long.valueOf(TIMEOUT_DEFAULT)), TimeUnit.SECONDS)
      .withSoTimeout(config.getLong(SOCKET_TIMEOUT_PROP, Long.valueOf(SOCKET_TIMEOUT_DEFAULT)), TimeUnit.SECONDS)
      .build();
```
4. Try to list all files in a share recursively and fetch their security contents too.
```
SecurityDescriptor descriptor = share.getSecurityInfo("", of(DACL_SECURITY_INFORMATION));
```

The problems I'm seeing are:

1. Notably these connecting messages spam in the logs over and over: `Connecting to \\10.100.10.10\IPC$ on session 171527840465321`
2. The exception here: 
```
2018-12-14T16:16:13,156 - ER2018-12-14T16:15:46,007 - INFO  smbj.paths.DFSPathResolver@104] - Starting DFS resolution for \\10.130.72.72\XXXXX\XXXXX\XXXXX\XXXXXX\XXXXXXXXXXX
2018-12-14T16:15:46,007 - INFO  smbj.session.Session@151] - Connecting to \\10.100.10.10\IPC$ on session 171531128800909
ROR [Packet Reader for 10.100.10.10:smbj.session.PacketSignatory@82] - {} - Signatures for packet SMB2_CREATE with message id << 1841 >> do not match (received: [-119, -29, -4, -122, -47, -83, 9, 97, -107, -118, -17, -93, 117, 79, -18, 105], calculated: [-104, -103, -15, 62, -114, 5, 103, 126, 1, 65, 68, 77, -15, -17, -48, 48, 0, 124, 99, -90, -52, 32, 42, -87, -35, -87, 13, -32, 41, -36, -41, 61])
2018-12-14T16:16:13,156 - ERROR [Packet Reader for 10.100.10.10:smbj.session.PacketSignatory@82] - {} - Signatures for packet SMB2_CREATE with message id << 1841 >> do not match (received: [-84, -94, -106, -121, -115, -66, 89, -3, 42, 38, -127, 26, 71, -7, -92, -116], calculated: [-102, 1, -128, 41, 21, 9, 42, -70, 0, -77, 69, 127, 119, -27, -116, 57, 36, 102, -4, -60, 65, -8, 22, -74, 98, 103, 68, -57, 59, -109, -108, 52])
2018-12-14T16:16:13,156 - WARN  [Packet Reader for 10.100.10.10:smbj.connection.Connection@432] - {} - Invalid packet signature for packet SMB2_CREATE with message id << 1841 >>
2018-12-14T16:16:13,156 - WARN  [Packet Reader for 10.100.10.10:smbj.connection.Connection@432] - {} - Invalid packet signature for packet SMB2_CREATE with message id << 1841 >>
2018-12-14T16:16:13,156 - INFO  [smb-fetcher-4:smbj.paths.DFSPathResolver@104] - {collectionId=test_dev, connectorType=smb2, datasourceId=smb, jobRunId=amkTJX6S0D} - Starting DFS resolution for \\10.100.10.10\XXXXX\XXXXXX\XX\XXX\XXXXXXXXXXXXXXXX
2018-12-14T16:16:13,156 - INFO  [smb-fetcher-4:smbj.session.Session@151] - {collectionId=test_dev, connectorType=smb2, datasourceId=smb, jobRunId=amkTJX6S0D} - Connecting to \\10.100.10.10\IPC$ on session 171527840465321
2018-12-14T16:16:13,156 - INFO  [Packet Reader for 10.100.10.10:smbj.transport.PacketReader@53] - {} - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: Packet signature for packet SMB2_CREATE with message id << 1841 >> was not correct
	at com.hierynomus.smbj.connection.Connection.verifyPacketSignature(Connection.java:434) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.connection.Connection.handle(Connection.java:422) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.connection.Connection.handle(Connection.java:70) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:72) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48) [smbj-0.9.1-patched.jar:0.9.1-patched]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
2018-12-14T16:16:13,156 - INFO  [Packet Reader for 10.100.10.10:smbj.transport.PacketReader@53] - {} - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: Packet signature for packet SMB2_CREATE with message id << 1841 >> was not correct
	at com.hierynomus.smbj.connection.Connection.verifyPacketSignature(Connection.java:434) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.connection.Connection.handle(Connection.java:422) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.connection.Connection.handle(Connection.java:70) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:72) ~[smbj-0.9.1-patched.jar:0.9.1-patched]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48) [smbj-0.9.1-patched.jar:0.9.1-patched]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```
3. The connections that are spamming related to `IPC$` eventually seem to cause a socket timeout and crash the program. 

Is there some problem with `IPC$` that might cause errors? What can I provide to help troubleshoot this? 

There are more smb2 create error messages, not sure if they are related: 

```
smbj.session.PacketSignatory@82] - {} - Signatures for packet SMB2_CREATE with message id << 3321 >> do not match (received: [79, -25, -126, 106, 63, -23, -90, 75, -53, -5, 70, -109, 23, 12, 92, 71], calculated: [12, 28, 45, -9, 39, -97, 120, -65, -123, 100, 72, -28, -1, 119, -70, 83, 81, -109, 97, -56, 52, -20, -107, 76, 114, -52, 110, -35, 59, -12, -92, 48])`
smbj.connection.Connection@432] - {} - Invalid packet signature for packet SMB2_CREATE with message id << 3321 >>
```

**Comment by nddipiazza** [comment]
i disabled DFS and the error showed to be https://github.com/hierynomus/smbj/issues/420
closing this issue.
