### ISSUE TITLE
Socket write errors during authentication?

### ISSUE THREAD

**Issue by nddipiazza** [hierynomus/smbj#418]
I am getting some socket write errors during authentication.

Environment: I am using the DFS enabled flag, I am on Windows 2012 R2.

Note: I do not think this is related to https://github.com/hierynomus/smbj/issues/365 which refers to the `.close` operation throwing unwanted error noise in the logs.

```
Caused by: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Software caused connection abort: socket write error
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:203)
	at com.lucidworks.connectors.smb2.client.DefaultSmbJClient.getSession(DefaultSmbJClient.java:243)
	at com.lucidworks.connectors.smb2.client.DefaultSmbJClient.getSession(DefaultSmbJClient.java:220)
	at com.lucidworks.connectors.smb2.client.DefaultSmbJClient.applyOnSession(DefaultSmbJClient.java:193)
	... 17 more
Caused by: com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Software caused connection abort: socket write error
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:78)
	at com.hierynomus.smbj.connection.Connection.send(Connection.java:277)
	at com.hierynomus.smbj.connection.Connection.sendAndReceive(Connection.java:285)
	at com.hierynomus.smbj.connection.Connection.initiateSessionSetup(Connection.java:232)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:169)
	... 20 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:75)
	... 24 more
```

I am on Windows operating system in this particular scenario. 

I have seen Windows run out of sockets.... could that be related? What typically causes this?

**Comment by nddipiazza** [comment]
This might actually be a side effect of whatever is causing this issue https://github.com/hierynomus/smbj/issues/420
