### ISSUE TITLE
SMBJ - SMB2_TREE_CONNECT  

### ISSUE THREAD

**Issue by shankaranselvaraj** [hierynomus/smbj#424]
I am trying to read the files from Samba server which is working fine and session is also not closed but getting below error. After restart the server it is working fine with TREE Disconnect issue. Is there anything related to opening of share path multiple time (as it is running in thread for more number of files) like this code session.connectShare(PATH) ?

11:29:42.255 [pool-13-thread-1] INFO  com.hierynomus.smbj.session.Session - Connecting to (HOST) on session 2988485184
11:29:42.255 [pool-13-thread-1] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 499) credits to SMB2_TREE_CONNECT with message id << 46770 >>
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_TREE_CONNECT with message id << 46770 >> as transport is disconnected
        at com.hierynomus.smbj.session.Session.connectTree(Session.java:197)
        at com.hierynomus.smbj.session.Session.connectShare(Session.java:144)
        at SambaFileAccess.getFileContents(SambaFileAccess.java:165)
        at ConfigManager.readConfigFile(ConfigManager.java:129)
        at ConfigManager.<init>(ConfigManager.java:42)
        at InstrumentElaborator.elaborate(NmrInstrumentElaborator.java:58)
        at InstrumentElaborator.elaborate(NmrInstrumentElaborator.java:23)
        at ElaboratorWorker.run(ElaboratorWorker.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_TREE_CONNECT with message id << 46770 >> as transport is disconnected
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68)
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:277)
        at com.hierynomus.smbj.session.Session.send(Session.java:285)
        at com.hierynomus.smbj.session.Session.connectTree(Session.java:155)
        ... 10 more

**Comment by shankaranselvaraj** [comment]
Any help would be appreciated. Pls
