### ISSUE TITLE
SMBJ TREE DISCONNECT while iterating thousand of files

### ISSUE THREAD

**Issue by shankaranselvaraj** [hierynomus/smbj#427]
I am trying to read the files from Samba server which is working fine and session is also not closed but getting below error. After restart the server it is working fine with TREE Disconnect issue. Is there anything related to opening of share path multiple time (as it is running in thread for more number of files) like this code session.connectShare(PATH) ?

11:29:42.255 [pool-13-thread-1] INFO com.hierynomus.smbj.session.Session - Connecting to (HOST) on session 2988485184
11:29:42.255 [pool-13-thread-1] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 499) credits to SMB2_TREE_CONNECT with message id << 46770 >>
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_TREE_CONNECT with message id << 46770 >> as transport is disconnected
at com.hierynomus.smbj.session.Session.connectTree(Session.java:197)
at com.hierynomus.smbj.session.Session.connectShare(Session.java:144)
at SambaFileAccess.getFileContents(SambaFileAccess.java:165)
at ConfigManager.readConfigFile(ConfigManager.java:129)
at ConfigManager.(ConfigManager.java:42)
at InstrumentElaborator.elaborate(NmrInstrumentElaborator.java:58)
at InstrumentElaborator.elaborate(NmrInstrumentElaborator.java:23)
at ElaboratorWorker.run(ElaboratorWorker.java:102)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_TREE_CONNECT with message id << 46770 >> as transport is disconnected
at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68)
at com.hierynomus.smbj.connection.Connection.send(Connection.java:277)
at com.hierynomus.smbj.session.Session.send(Session.java:285)
at com.hierynomus.smbj.session.Session.connectTree(Session.java:155)
... 10 more

**Comment by hierynomus** [comment]
You need to figure out for which reason the transport got disconnected. That will be in another part of the logging.

**Comment by shankaranselvaraj** [comment]
This is what i am getting in entire logs. it is not happening all the time it is happening intermittently. Need help on resolving. As of now , restarting application server resolving this issue., but need permanent fix 

14:24:23.356 [http-nio-8080-exec-2] DEBUG com.hierynomus.smbj.session.Session - Notified of TreeDisconnected <<8275268                                                                            43>>
14:24:23.357 [http-nio-8080-exec-2] ERROR com.hierynomus.smbj.session.Session - Caught exception while closing TreeCon                                                                            nect with id: 827526843
com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_TREE_DISCONNECT with message id << 72765 >> as                                                                             transport is disconnected
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68) ~[smbj-0.9.0.                                                                            jar:0.9.0]
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:277) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.session.Session.send(Session.java:285) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:66) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.share.Share.close(Share.java:115) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.session.Session.logoff(Session.java:226) ~[smbj-0.9.0.jar:0.9.0]
        atnmrexpsub.dataaccess.SambaAuthentication.renewAuth(SambaAuthentication.java:277) [classes/:                                                                            na]
        atnmrexpsub.dataaccess.SambaAuthentication.checkSessionStatus(SambaAuthentication.java:306) [                                                                            classes/:na]
        atnmrexpsub.web.ResultViewerServlet.doGet(ResultViewerServlet.java:154) [classes/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [servlet-api.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina                                                                            .jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0                                                                            .11]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina                                                                            .jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0                                                                            .11]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.11]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.11]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.11                                                                            ]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.11]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.11]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668) [catalina.jar:9.0                                                                            .11]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.11]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.11]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.11]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.11]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770) [tomcat-coyote.jar:                                                                            9.0.11]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-coyote.jar:9.0.                                                                            11]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.11]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.11]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
14:24:23.357 [http-nio-8080-exec-2] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 506) credits to SMB2_TREE                                                                            _DISCONNECT with message id << 72766 >>
14:24:23.357 [http-nio-8080-exec-2] DEBUG com.hierynomus.smbj.session.Session - Notified of TreeDisconnected <<4164055                                                                            947>>
14:24:23.357 [http-nio-8080-exec-2] ERROR com.hierynomus.smbj.session.Session - Caught exception while closing TreeCon                                                                            nect with id: 4164055947
com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_TREE_DISCONNECT with message id << 72766 >> as                                                                             transport is disconnected
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68) ~[smbj-0.9.0.                                                                            jar:0.9.0]
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:277) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.session.Session.send(Session.java:285) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:66) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.share.Share.close(Share.java:115) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.session.Session.logoff(Session.java:226) ~[smbj-0.9.0.jar:0.9.0]
        atnmrexpsub.dataaccess.SambaAuthentication.renewAuth(SambaAuthentication.java:277) [classes/:                                                                            na]
        atnmrexpsub.dataaccess.SambaAuthentication.checkSessionStatus(SambaAuthentication.java:306) [                                                                            classes/:na]
        atnmrexpsub.web.ResultViewerServlet.doGet(ResultViewerServlet.java:154) [classes/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [servlet-api.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina                                                                            .jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0                                                                            .11]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina                                                                            .jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0                                                                            .11]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.11]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.11]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.11                                                                            ]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.11]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.11]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668) [catalina.jar:9.0                                                                            .11]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.11]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.11]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.11]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.11]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770) [tomcat-coyote.jar:                                                                            9.0.11]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-coyote.jar:9.0.                                                                            11]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.11]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.11]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
14:24:23.358 [http-nio-8080-exec-2] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 505) credits to SMB2_TREE                                                                            _DISCONNECT with message id << 72767 >>
14:24:23.358 [http-nio-8080-exec-2] DEBUG com.hierynomus.smbj.session.Session - Notified of TreeDisconnected <<3338988                                                                            474>>
14:24:23.358 [http-nio-8080-exec-2] ERROR com.hierynomus.smbj.session.Session - Caught exception while closing TreeCon                                                                            nect with id: 3338988474
com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_TREE_DISCONNECT with message id << 72767 >> as                                                                             transport is disconnected
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68) ~[smbj-0.9.0.                                                                            jar:0.9.0]
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:277) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.session.Session.send(Session.java:285) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:66) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.share.Share.close(Share.java:115) ~[smbj-0.9.0.jar:0.9.0]
        at com.hierynomus.smbj.session.Session.logoff(Session.java:226) ~[smbj-0.9.0.jar:0.9.0]
        atnmrexpsub.dataaccess.SambaAuthentication.renewAuth(SambaAuthentication.java:277) [classes/:                                                                            na]
        atnmrexpsub.dataaccess.SambaAuthentication.checkSessionStatus(SambaAuthentication.java:306) [                                                                            classes/:na]
        atnmrexpsub.web.ResultViewerServlet.doGet(ResultViewerServlet.java:154) [classes/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [servlet-api.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina                                                                            .jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0                                                                            .11]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina                                                                            .jar:9.0.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0                                                                            .11]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.11]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.11]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.11                                                                            ]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.11]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.11]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668) [catalina.jar:9.0                                                                            .11]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.11]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.11]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.11]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.11]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770) [tomcat-coyote.jar:                                                                            9.0.11]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-coyote.jar:9.0.                                                                            11]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.11]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.11]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
14:24:23.358 [http-nio-8080-exec-2] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 504) credits to SMB2_LOGO                                                                            FF with message id << 72768 >>
14:24:23.359 [http-nio-8080-exec-2] DEBUG c.h.smbj.connection.Connection - Session << 1799839400 >> logged off
com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_LOGOFF with message id << 72768 >> as transpor                                                                            t is disconnected
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68)
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:277)
        at com.hierynomus.smbj.session.Session.send(Session.java:285)
        at com.hierynomus.smbj.session.Session.logoff(Session.java:240)
        atnmrexpsub.dataaccess.SambaAuthentication.renewAuth(SambaAuthentication.java:277)
        atnmrexpsub.dataaccess.SambaAuthentication.checkSessionStatus(SambaAuthentication.java:306)
        atnmrexpsub.web.ResultViewerServlet.doGet(ResultViewerServlet.java:154)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
The current ticket should be renewed now
Searching for: SN1064836422
14:24:23.360 [http-nio-8080-exec-2] INFO  com.hierynomus.smbj.session.Session - Connecting to \\host                                                                            net\sc on session 1799839400
14:24:23.360 [http-nio-8080-exec-2] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 503) credits to SMB2_TREE                                                                            _CONNECT with message id << 72769 >>
15:41:34.434 [http-nio-8080-exec-5] INFO  c.h.smbj.connection.Connection - Closed connection to samba                                                                           net
15:41:34.434 [http-nio-8080-exec-5] DEBUG com.hierynomus.smbj.SMBClient - Connection to << samba.net:4                                                                            45 >> closed
15:41:34.434 [http-nio-8080-exec-5] INFO  com.hierynomus.smbj.session.Session - Logging off session 1799839400 from ho                                                                            st samba.net
15:41:34.434 [http-nio-8080-exec-5] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 502) credits to SMB2_LOGO                                                                            FF with message id << 72770 >>
15:41:34.434 [http-nio-8080-exec-5] DEBUG c.h.smbj.connection.Connection - Session << 1799839400 >> logged off
com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_LOGOFF with message id << 72770 >> as transpor                                                                            t is disconnected
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68)
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:277)
        at com.hierynomus.smbj.session.Session.send(Session.java:285)
        at com.hierynomus.smbj.session.Session.logoff(Session.java:240)
        atnmrexpsub.dataaccess.SambaAuthentication.closeAll(SambaAuthentication.java:265)
        atnmrexpsub.dataaccess.SambaFileAccess.<init>(SambaFileAccess.java:125)
        atnmrexpsub.web.QueueViewerServlet.init(QueueViewerServlet.java:64)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1124)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1079)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
error wrtie----------------------------Cannot write SMB2_LOGOFF with message id << 72770 >> as transport is disconnect                                                                            ed
Exception:::::: java.lang.Exception: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_LOGOFF wi                                                                            th message id << 72770 >> as transport is disconnected
