### ISSUE TITLE
How connect in Android?

### ISSUE THREAD

**Issue by Kitsune2222** [hierynomus/smbj#435]
I'm try connect to 192.168.0.173 smb server, but get NetworkOnMainThreadException
val client = SMBClient()
Log.i(DEBUG_TAG, "Try connect to server")
val connection = client.connect("192.168.0.173")

`Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:333)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.Socket.connect(Socket.java:605)
        at com.hierynomus.protocol.commons.socket.ProxySocketFactory.createSocket(ProxySocketFactory.java:87)
        at com.hierynomus.protocol.commons.socket.ProxySocketFactory.createSocket(ProxySocketFactory.java:63)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.connect(DirectTcpTransport.java:88)
        at com.hierynomus.smbj.connection.Connection.connect(Connection.java:117)
        at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:103)
        at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:77)
...`

**Comment by ecki** [comment]
Android does not like network operations on the main thread, you have to start the activity in a new thread instead.

**Comment by Kitsune2222** [comment]
> Android does not like network operations on the main thread, you have to start the activity in a new thread instead.

Thanks, in new thread all works!
