### ISSUE TITLE
Unknown Object Tag 3 encountered exception while authenticating.

### ISSUE THREAD

**Issue by rlstehr** [hierynomus/smbj#44]
When I authenticate with Windows servers everything is fine.  When I try to authenticate with a multiprotocol file server that uses SMBv2.1, I get this exception.

com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.spnego.SpnegoException: Unknown Object Tag 3 encountered.
	at com.hierynomus.spnego.NegTokenInit.read(NegTokenInit.java:117)
	at com.hierynomus.spnego.NegTokenInit.read(NegTokenInit.java:100)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:117)
	at com.rls.smbj.Testsmb.main(Testsmb.java:89)
Caused by: com.hierynomus.spnego.SpnegoException: Unknown Object Tag 3 encountered.
	at com.hierynomus.spnego.NegTokenInit.parseTagged(NegTokenInit.java:136)
	at com.hierynomus.spnego.SpnegoToken.parseSpnegoToken(SpnegoToken.java:64)
	at com.hierynomus.spnego.NegTokenInit.read(NegTokenInit.java:115)
	... 3 more
Am I doing something wrong?

**Comment by hierynomus** [comment]
I think this is fixed in the current master. Take a look at that. I will try to cut a new release next week.

**Comment by niggemannmj** [comment]
I ran into the same issue and fixed it already. It should be on master.

**Comment by hierynomus** [comment]
Was fixed with bfffb2ad145891cc6f7d8c484724a6b5b64e36bb

**Comment by rlstehr** [comment]
When are you planning to the next release?

**Comment by hierynomus** [comment]
I'm finishing off #46 first, then I want to make a release. I hope this weekend.

**Comment by rlstehr** [comment]
Thanks

**Comment by rlstehr** [comment]
When is the next release planned?

From: Stehr, Robert (NIH/CC/DCRI) [E]
Sent: Wednesday, April 26, 2017 2:37 PM
To: 'hierynomus/smbj' <reply@reply.github.com>
Subject: RE: [hierynomus/smbj] Unknown Object Tag 3 encountered exception while authenticating. (#44)

Thanks
