### ISSUE TITLE
Upload smbj File to Cloud provider

### ISSUE THREAD

**Issue by fiasko131** [hierynomus/smbj#441]
I'm trying to upload a file from my desktop to a cloud provider.
The application is develloped on Android with your library.
It works with DropBox and Box. By cons I have problems with oneDrive and GoogleDrive.
Here's how I get the inputstream:
````java
 Set<SMB2CreateOptions> s = new HashSet<>();
 s.add(SMB2CreateOptions.FILE_RANDOM_ACCESS);
 com.hierynomus.smbj.share.File remoteSmbjFile =  smbItem.getDiskShare()
                        .openFile(smbItem.getPath()+"\\"+smbItem.getFileName()+"."+smbItem.getExt()
                                , EnumSet.of(AccessMask.FILE_READ_DATA)
                                , null
                                , SMB2ShareAccess.ALL
                                , SMB2CreateDisposition.FILE_OPEN
                                , s);              

 in = remoteSmbjFile.getInputStream();
````
In the case of GoogleDrive processing the inputstream I get this type of error:

> java.net.ProtocolException: unexpected end of stream
    at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:406)
    at okio.Buffer.writeAll(Buffer.java:1005)
    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:107)
    at okhttp3.ResponseBody.bytes(ResponseBody.java:136)
    at dm.com.downloadmanager.MainActivity$3.onResponse(MainActivity.java:273)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)

In the case of OneDrive it seems that the upload remains blocked on the last bytes unfortunately without warning of the onedrive API.

I tried with different configurations of clients by playing on the size of the buffer so that it corresponds to the chunk size of the downloader of onedrive for example 320 * 1024, but nothing changes. The upload is blocked on the last bytes.
````java
SmbConfig cfg = SmbConfig.builder().
                    withMultiProtocolNegotiate(true).
                    withSecurityProvider(new JceSecurityProvider(new BouncyCastleProvider())).
                    withReadBufferSize(320*1024).
                    build();
````
It seems that there is a concern about the negotiation of the last bytes.
It should be noted that I have no problem during an upload with jcifs.

Any ideas?

**Comment by hierynomus** [comment]
Are you flushing the stream and closing it?

**Comment by fiasko131** [comment]
I can not because in the second case (for OneDrive) the downloader remains blocked and the last bytes of the inputstream seem inaccessible.
