### ISSUE TITLE
STATUS_REQUEST_NOT_ACCEPTED (0xc00000d0)?

### ISSUE THREAD

**Issue by fiasko131** [hierynomus/smbj#443]
I get this error randomly when browsing the folders:

> Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_REQUEST_NOT_ACCEPTED (0xc00000d0): Authentication failed for 'steph' using com.hierynomus.smbj.auth.NtlmAuthenticator@89446ed
                                                                              at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:182)
                                                                              at com.techniwork.explorer.explorateur.FragmentNetworks$ListSmb2Shares.doInBackground(FragmentNetworks.java:3335)
                                                                              at com.techniwork.explorer.explorateur.FragmentNetworks$ListSmb2Shares.doInBackground(FragmentNetworks.java:3266)
                                                                              at com.techniwork.util.AsyncTask$2.call(AsyncTask.java:313)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                              at com.techniwork.util.AsyncTask$SerialExecutor$1.run(AsyncTask.java:256) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                              at java.lang.Thread.run(Thread.java:764) 

I can not repeat it with certainty.

**Comment by hierynomus** [comment]
Looking at the documentation, there are 3 possible scenarios for this status. Without knowing your code and environment, I cannot say which one it is for you.

**Comment by hierynomus** [comment]
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/e545352b-9f2b-4c5e-9350-db46e4f6755e

**Comment by ceremo** [comment]
I've had a similar problem with `STATUS_REQUEST_NOT_ACCEPTED` as a result, and in my case occurs when there are too many sessions opened in the same connection, I'm doing this because I don't want to close the connection in order to reuse it and try to improve performance. I solved the problem closing sessions after being used `try (Session session = connection.authenticate(ac))`.

**Comment by ndimitry** [comment]
Windows (not the server edition) allows only 20 sessions, so in case someone tries to establish the 21st session, one will get `STATUS_REQUEST_NOT_ACCEPTED`.
This also might be the reason.
