### ISSUE TITLE
SMBApiException: STATUS_OTHER (0xffffffff): Could not connect to DFS root 

### ISSUE THREAD

**Issue by anandsirt** [hierynomus/smbj#446]
I am getting below issue sometimes, it works for most of time.

com.hierynomus.mssmb2.SMBApiException: STATUS_OTHER (0xffffffff): Could not connect to DFS root \\SVWIORA.admin.company.int\shares
      at com.hierynomus.smbj.session.Session.buildNestedSession(Session.java:208)
      at com.hierynomus.smbj.session.Session.connectTree(Session.java:162)
      at com.hierynomus.smbj.session.Session.connectShare(Session.java:144)
      at com.framelib.file.JcifsNetworkFileServiceImpl.getSMBContext(JcifsNetworkFileServiceImpl.java:742)
      at com.framelib.file.JcifsNetworkFileServiceImpl.exists(JcifsNetworkFileServiceImpl.java:557)
      at com.framelib.file.FileService.exists(FileService.java:93)
      at com.framelib.file.FileService.copy(FileService.java:550)
      at com.liblocal.service.TranslationService.createFile(TranslationService.java:1206)

**Comment by andershermansen** [comment]
This exception has a nested IOException with the reason. You should log the nested exception as well to see the root cause.
