### ISSUE TITLE
STATUS_ACCESS_DENIED(3221225506/3221225506): Close failed for SMB2FileId

### ISSUE THREAD

**Issue by RomanKarpliak96** [hierynomus/smbj#459]
Hi all,
I am receiving the following error when closing file:
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Close failed for SMB2FileId{persistentHandle=43 5d c6 00 00 00 00 00}
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.closeFileId(Share.java:151)
	at com.hierynomus.smbj.share.DiskEntry.close(DiskEntry.java:48)
	at com.hierynomus.smbj.share.DiskShare.rm(DiskShare.java:316)
It happens only for Qumulo file server. 
For other types of share it works well.
Could you please help me with this problem?
Thanks in advance.

**Comment by RomanKarpliak96** [comment]
Is it possible to check if file is already closed?
