### ISSUE TITLE
Cannot list files on a non-windows docker smb server - DiskShare has already been closed

### ISSUE THREAD

**Issue by nddipiazza** [hierynomus/smbj#467]
Hi @hierynomus do you write any integration tests against a dockerized smb such as https://github.com/dperson/samba ?

The latest master branch throws errors against this container. Just wondering if you see the same thing.

For example here is a directory list operation:

```
Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_NETWORK_NAME_DELETED (0xc00000c9): Query directory failed for SMB2FileId{persistentHandle=68 d3 3c c5 00 00 00 00}
  at com.hierynomus.smbj.share.Share.receive(Share.java:371)
  at com.hierynomus.smbj.share.Share.sendReceive(Share.java:351)
  at com.hierynomus.smbj.share.Share.queryDirectory(Share.java:217)
  at com.hierynomus.smbj.share.Directory$DirectoryIterator.queryDirectory(Directory.java:173)
  at com.hierynomus.smbj.share.Directory$DirectoryIterator.prepareNext(Directory.java:154)
  at com.hierynomus.smbj.share.Directory$DirectoryIterator.next(Directory.java:145)
  at com.hierynomus.smbj.share.Directory$DirectoryIterator.next(Directory.java:119)
  at com.hierynomus.smbj.share.Directory.list(Directory.java:64)
  at com.hierynomus.smbj.share.Directory.list(Directory.java:51)
  at com.hierynomus.smbj.share.Directory.list(Directory.java:42)
  at com.lucidworks.connectors.smb2.client.share.DiskShares.createFolder(DiskShares.java:180)
  ... 22 more
  Suppressed: com.hierynomus.smbj.common.SMBRuntimeException: DiskShare has already been closed
    at com.hierynomus.smbj.share.Share.send(Share.java:356)
    at com.hierynomus.smbj.share.Share.sendReceive(Share.java:350)
    at com.hierynomus.smbj.share.Share.closeFileId(Share.java:178)
    at com.hierynomus.smbj.share.DiskEntry.close(DiskEntry.java:45)
    at com.xxxxxxxx.share.DiskShares.createFolder(DiskShares.java:187)
    ... 22 more
```

**Comment by hierynomus** [comment]
There are integration tests, just run `gradle integrationTest`

**Comment by nddipiazza** [comment]
I am no longer getting this error. It must have been a user issue. Closing!
