### ISSUE TITLE
Authentication failed with STATUS_OTHER (0xc0000205)

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#506]
Hi,

  I have got the following exception  (wrong credentials are excluded): 

  Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_OTHER (0xc0000205): Authentication failed for 'user' using com.hierynomus.smbj.auth.NtlmAuthenticator@b10f57
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:182)
	at com.hierynomus.smbj.session.Session.buildNestedSession(Session.java:204)
	at com.hierynomus.smbj.share.DiskShare.rerouteIfNeeded(DiskShare.java:88)
	at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:78)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:148)

I can see a lot of nested Sessions in the log. 
According with https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/8f11e0f3-d545-46cc-97e6-f00569e3e1bc   the error status 0xC0000205 is STATUS_INSUFF_SERVER_RESOURCES

   Do you have any idea what can be wrong ? 
 
  Thanks !

**Comment by hierynomus** [comment]
My guess is that because the nested sessions aren't reused yet, you're going over some limit in the server.

**Comment by cliviu** [comment]
Yes, this is my guess also. Is there any release candidate that I can use to test this ?

**Comment by hierynomus** [comment]
None yet, I would suggest for now to not reuse smbclient when using dfs... Will try to find some time this month to work on it.

**Comment by cliviu** [comment]
> None yet, I would suggest for now to not reuse smbclient when using dfs... 
How do you mean this ?
>Will try to find some time this month to work on it.
Thanks !

**Comment by hierynomus** [comment]
@cliviu I meant that between requests you should close the SmbClient, this will ensure that all nested sessions are cleaned up

**Comment by hierynomus** [comment]
i.e. I know this is a stop-gap measure, but it will in the short run at least fix the problem

**Comment by cliviu** [comment]
ok, thanks

**Comment by samrajcse** [comment]
Hi All,

Any interim update about this fix?
