### ISSUE TITLE
After creating a file using smbj, it is not accessible up till sometime

### ISSUE THREAD

**Issue by coolpk34** [hierynomus/smbj#507]
Hello Team,

I am creating and writing a file onto a network shared location. Once its done, it won't be accessible for couple of minutes. I see below multiple exceptions in the logs. After some time newly created files can be opened and read. When tried to open as soon as file is created, it says 'file is opened and in use'.

Can you please help me in getting this resolved?

07:00:58,747 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,748 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,748 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,748 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,748 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,748 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,748 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 0: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,747 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:00:58,753 INFO  [Connection] Closed connection to CMHP-DFS02
07:00:58,752 INFO  [Connection] Closed connection to CMHP-DFS02
07:00:58,752 INFO  [Connection] Closed connection to CMHP-DFS02
07:00:58,751 INFO  [Connection] Closed connection to CMHP-DFS02
07:00:58,750 INFO  [Connection] Closed connection to CMHP-DFS02
07:00:58,749 INFO  [Connection] Closed connection to CMHP-DFS02
07:00:58,749 INFO  [Connection] Closed connection to CMHP-DFS02
07:00:58,753 INFO  [Connection] Closed connection to CMHP-DFS02
07:02:02,617 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:02:02,623 INFO  [Connection] Closed connection to CMHP-DFS02
07:10:55,847 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:10:55,847 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:10:55,847 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:10:55,847 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:10:55,847 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:10:55,847 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
07:10:55,847 INFO  [Session] Logging off session 105778132287597 from host gcdomain.local
07:10:55,847 INFO  [Session] Logging off session 105777863852145 from host gcdomain.local
07:10:55,847 INFO  [Session] Logging off session 105778870485081 from host gcdomain.local
07:10:55,847 INFO  [Session] Logging off session 105777125654545 from host gcdomain.local
07:10:55,847 INFO  [Session] Logging off session 105774239973397 from host gcdomain.local
07:10:55,863 ERROR [Session] Caught exception while closing TreeConnect with id: 1
07:10:55,863 ERROR [Session] Caught exception while closing TreeConnect with id: 1
07:10:55,863 ERROR [Session] Caught exception while closing TreeConnect with id: 1
07:10:55,863 ERROR [Session] Caught exception while closing TreeConnect with id: 1
07:10:55,863 INFO  [Session] Logging off session 105773099122813 from host gcdomain.local
07:10:55,863 INFO  [Session] Logging off nested session 136357829674005 for session 105778132287597
07:10:55,863 INFO  [Session] Logging off nested session 228716672190473 for session 105777863852145
07:10:55,863 INFO  [Session] Logging off nested session 228715732667013 for session 105778870485081
07:10:55,863 INFO  [Session] Logging off nested session 228718685457541 for session 105777125654545
07:10:55,863 ERROR [Session] Caught exception while closing TreeConnect with id: 1
07:10:55,863 INFO  [Session] Logging off session 228718685457541 from host CMHP-DFSIMG4
07:10:55,863 INFO  [Session] Logging off session 228715732667013 from host CMHP-DFSIMG4
07:10:55,863 INFO  [Session] Logging off session 228716672190473 from host CMHP-DFSIMG4
07:10:55,863 INFO  [Session] Logging off session 136357829674005 from host CMHP-DFS01
07:10:55,863 ERROR [Session] Caught exception while closing TreeConnect with id: 1
07:10:55,863 INFO  [Session] Logging off nested session 136361654879249 for session 105774239973397
07:10:55,863 INFO  [Session] Logging off nested session 228715262902357 for session 105773099122813
07:10:55,863 INFO  [Session] Logging off session 136361654879249 from host CMHP-DFS01
07:10:55,863 INFO  [Session] Logging off session 228715262902357 from host CMHP-DFSIMG4
07:10:55,987 WARN  [Connection] Exception while closing session 105778870485081
07:10:55,987 WARN  [Connection] Exception while closing session 105777863852145
07:10:55,987 WARN  [Connection] Exception while closing session 105777125654545
07:10:55,987 WARN  [Connection] Exception while closing session 105778132287597
07:10:55,987 INFO  [Connection] Closed connection to gcdomain.local
07:10:55,987 INFO  [Connection] Closed connection to gcdomain.local
07:10:55,987 WARN  [Connection] Exception while closing session 105773099122813
07:10:55,987 INFO  [Connection] Closed connection to gcdomain.local
07:10:55,987 INFO  [Connection] Closed connection to gcdomain.local
07:10:55,987 WARN  [Connection] Exception while closing session 105774239973397
07:10:55,987 INFO  [Connection] Closed connection to gcdomain.local
07:10:56,003 INFO  [Connection] Closed connection to gcdomain.local
07:12:03,380 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset

**Comment by hierynomus** [comment]
Are you correctly closing the File/streams/share etc?

**Comment by coolpk34** [comment]
Yes you are right streams which were opened were not closed and which is why we were facing issue accessing those files immediately after they were created. Thanks for pointing that out.

I have made sure resources wherever are are opened (File\share\connection\streams\session), that have been closed and yet after some idle time, I see below exception logs in the server back logs.

Can you throw some light on this issue please?

05:44:37,999 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
05:44:38,001 INFO  [Connection] Closed connection to CMHP-DFSIMG4
05:57:14,697 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        ... 3 more
05:57:14,697 INFO  [PacketReader] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
.
.
.
.

**Comment by hierynomus** [comment]
No only streams need to be closed, also `File`, `Share`, `Session`, `Connection` and `SmbClient` have `close()` methods attached to them to clean up.

**Comment by coolpk34** [comment]
Even after closing the said elements, in idle time I am seeing those exceptions on server logs. Anyway that is not causing any problem with the functionality of the application. Is there any way that we can disable those kind of logs?
