### ISSUE TITLE
BufferException:underflow when trying to read, the  excel file that is opened in write mode.

### ISSUE THREAD

**Issue by kvk484** [hierynomus/smbj#509]
Caused by: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow
	at com.hierynomus.protocol.commons.buffer.Buffer.ensureAvailable(Buffer.java:184)
	at com.hierynomus.protocol.commons.buffer.Buffer.readRawBytes(Buffer.java:303)
	at com.hierynomus.protocol.commons.buffer.Buffer.readRawBytes(Buffer.java:290)
	at com.hierynomus.protocol.commons.buffer.Buffer.readRawBytes(Buffer.java:278)
	at com.hierynomus.protocol.commons.buffer.Endian$Little.readUInt32(Endian.java:196)
	at com.hierynomus.protocol.commons.buffer.Buffer.readUInt32(Buffer.java:463)
	at com.hierynomus.protocol.commons.buffer.Buffer.readUInt32(Buffer.java:452)
	at com.hierynomus.msdtyp.MsDataTypes.readFileTime(MsDataTypes.java:75)
	at com.hierynomus.mssmb2.messages.SMB2CreateResponse.readMessage(SMB2CreateResponse.java:52)
	at com.hierynomus.mssmb2.SMB2Packet.read(SMB2Packet.java:108)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:49)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:81)
	at com.hierynomus.mssmb2.messages.SMB2MessageConverter.read(SMB2MessageConverter.java:27)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader._readSMB2Packet(DirectTcpPacketReader.java:50)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:57)
	... 3 more

getting the above error, if i try to read the excel file that is opened in write mode from explorer. (Locked). But I should be able to read right?

**Comment by kvk484** [comment]
Can some one , help on the above issue of opened excel file.
