### ISSUE TITLE
Exception occurred when trying to read the drive which has 200K files

### ISSUE THREAD

**Issue by iamnani** [hierynomus/smbj#515]
Hi 
I am new to working with this library, using 0.9.1 version. When I try to scan a  network folder which has 200K files on it. It reads for 30K files and gives the following exception.

[c.h.p.commons.concurrent.Promise].tryRetrieve - << 23 >> woke to: {}
com.hierynomus.smbj.common.SMBRuntimeException: java.nio.channels.ClosedChannelException
        at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
        at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
        at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:95)
        at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88)
        at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:454)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport$1.failed(AsyncDirectTcpTransport.java:141)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
        at sun.nio.ch.Invoker$2.run(Invoker.java:218)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:366)
        at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:399)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport.startAsyncWrite(AsyncDirectTcpTransport.java:124)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport.writeOrEnqueue(AsyncDirectTcpTransport.java:82)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport.write(AsyncDirectTcpTransport.java:75)
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:286)
        at com.hierynomus.smbj.session.Session.send(Session.java:285)
        at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:66)
        at com.hierynomus.smbj.share.Share.close(Share.java:115)
        
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
       
        ... 1 common frames omitted

My SMBConfig looks as,

SmbConfig smbConfig = SmbConfig
                .builder()
                .withTimeout(12000000, TimeUnit.MILLISECONDS)
                .withSoTimeout(12000000)
                .withDfsEnabled(true)
                .withMultiProtocolNegotiate(true)
                .withTransportLayerFactory(new AsyncDirectTcpTransportFactory<>())
                .withSigningRequired(true).build();

Any thoughts ?

**Comment by iamnani** [comment]
next exception after the above exception trace is 
com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.nio.channels.ClosedChannelException
        at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:29)
        at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:23)
        at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:43)
        at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:67)
        at com.hierynomus.smbj.share.Share.close(Share.java:115)
        at com.jpmc.sdsu.services.SDSUService.prepareFileMapByFileTypeExtension(SDSUService.java:145)
        at com.jpmc.sdsu.services.SDSUService.startPersistProcess(SDSUService.java:311)
        at com.jpmc.sdsu.services.SDSUService.runInProgressOrPendingScans(SDSUService.java:350)
        at com.jpmc.sdsu.services.SDSUService$$FastClassBySpringCGLIB$$9e7a33c8.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at com.jpmc.sdsu.services.SDSUService$$EnhancerBySpringCGLIB$$bc35d6a.runInProgressOrPendingScans(<generated>)
        at com.jpmc.sdsu.SharedDriveScanUtilityApplication.lambda$run$0(SharedDriveScanUtilityApplication.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.nio.channels.ClosedChannelException
        at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:60)
        at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:84)
        at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
        ... 11 common frames omitted
Caused by: com.hierynomus.smbj.common.SMBRuntimeException: java.nio.channels.ClosedChannelException
        at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
        at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
        at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:95)
        at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88)
        at com.hierynomus.smbj.connection.Connection.handleError(Connection.java:454)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport$1.failed(AsyncDirectTcpTransport.java:141)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
        at sun.nio.ch.Invoker$2.run(Invoker.java:218)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted
Caused by: java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:366)
        at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:399)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport.startAsyncWrite(AsyncDirectTcpTransport.java:124)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport.writeOrEnqueue(AsyncDirectTcpTransport.java:82)
        at com.hierynomus.smbj.transport.tcp.async.AsyncDirectTcpTransport.write(AsyncDirectTcpTransport.java:75)
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:286)
        at com.hierynomus.smbj.session.Session.send(Session.java:285)
        at com.hierynomus.smbj.share.TreeConnect.close(TreeConnect.java:66)
        at com.hierynomus.smbj.share.Share.close(Share.java:115)

**Comment by hierynomus** [comment]
Without the code to see, and a tcpdump of the session it is impossible to say what's going wrong.

**Comment by iamnani** [comment]
worked after changing the implementation of reading huge files directory.
