### ISSUE TITLE
SMB v2 authentication fails  - Unrecognized Windows Sockets error: 0: recv failed

### ISSUE THREAD

**Issue by SubhasishDey** [hierynomus/smbj#525]
SMBJ is failing to authenticate with valid credentials using NTLM Authenticator.
WE are trying to connect to a windows 2016 SMB server
Can anyone please help me understand, the reason for this failure ?

```
2020-01-22 14:50:22,196 INFO  [com.w.p.s.c.i.ClusterProvider                               ] - Initializing components of: cluster
2020-01-22 14:50:22,199 WARN  [com.w.p.s.c.i.ClusterProvider                               ] - UM reload invoked, but URL is the same
2020-01-22 14:50:23,214 ERROR [com.w.p.b.c.r.h.HttpRemoteCommandTransport                  ] - Remote command failed with: java.net.ConnectException, Reason: Connection refused: connect
2020-01-22 14:50:24,228 ERROR [com.w.p.b.c.r.h.HttpRemoteCommandTransport                  ] - Remote command failed with: java.net.ConnectException, Reason: Connection refused: connect
2020-01-22 14:50:25,797 DEBUG [com.h.p.c.s.ProxySocketFactory                              ] - Connecting to VR-GS0121/10.130.246.154:445
2020-01-22 14:50:26,003 DEBUG [com.h.s.t.PacketReader                                      ] - Starting PacketReader on thread: Packet Reader for VR-GS0121
2020-01-22 14:50:26,003 DEBUG [com.h.s.c.Connection                                        ] - Negotiating dialects [SMB_2_0_2, SMB_2_1] with server VR-GS0121
2020-01-22 14:50:26,003 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB_COM_NEGOTIATE >>
2020-01-22 14:50:26,003 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB_COM_NEGOTIATE
2020-01-22 14:50:26,003 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB_COM_NEGOTIATE sent, lock released.
2020-01-22 14:50:26,003 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 0 >>
2020-01-22 14:50:26,280 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@154961a2
2020-01-22 14:50:26,280 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@154961a2, now available: 1 credits
2020-01-22 14:50:26,280 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@154961a2 took << 277 ms >>
2020-01-22 14:50:26,280 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 0 >> to `SMB2_NEGOTIATE with message id << 0 >>`
2020-01-22 14:50:26,280 DEBUG [com.h.s.c.Connection                                        ] - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 1 >>
2020-01-22 14:50:26,280 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB2_NEGOTIATE with message id << 1 >> >>
2020-01-22 14:50:26,280 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB2_NEGOTIATE with message id << 1 >>
2020-01-22 14:50:26,280 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB2_NEGOTIATE with message id << 1 >> sent, lock released.
2020-01-22 14:50:26,280 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 1 >>
2020-01-22 14:50:26,557 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@1b8e9d7b
2020-01-22 14:50:26,557 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@1b8e9d7b, now available: 1 credits
2020-01-22 14:50:26,557 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@1b8e9d7b took << 277 ms >>
2020-01-22 14:50:26,557 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 1 >> to `SMB2_NEGOTIATE with message id << 1 >>`
2020-01-22 14:50:26,558 DEBUG [com.h.s.c.Connection                                        ] - Negotiated the following connection settings: ConnectionInfo{
  serverGuid=7c045953-293e-4c47-ba6c-42f775564209,
  serverName='VR-GS0121',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_2_1, maxTransactSize=8388608, maxReadSize=8388608, maxWriteSize=8388608},
  clientGuid=0b39c5b1-1158-4c05-a16f-1d278b3684fa,
  clientCapabilities=[SMB2_GLOBAL_CAP_DFS],
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=0,
  serverSecurityMode=1,
  server='null'
}
2020-01-22 14:50:26,558 INFO  [com.h.s.c.Connection                                        ] - Successfully connected to: VR-GS0121
2020-01-22 14:50:26,558 DEBUG [com.h.s.a.NtlmAuthenticator                                 ] - Initialized Authentication of vr-gs0121 using NTLM
2020-01-22 14:50:26,558 DEBUG [com.h.s.c.Connection                                        ] - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 2 >>
2020-01-22 14:50:26,558 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB2_SESSION_SETUP with message id << 2 >> >>
2020-01-22 14:50:26,558 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB2_SESSION_SETUP with message id << 2 >>
2020-01-22 14:50:26,558 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB2_SESSION_SETUP with message id << 2 >> sent, lock released.
2020-01-22 14:50:26,558 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 2 >>
2020-01-22 14:50:26,835 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@1fb10ad2
2020-01-22 14:50:26,835 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@1fb10ad2, now available: 1 credits
2020-01-22 14:50:26,835 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@1fb10ad2 took << 277 ms >>
2020-01-22 14:50:26,835 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 2 >> to `SMB2_SESSION_SETUP with message id << 2 >>`
2020-01-22 14:50:26,835 DEBUG [com.h.s.c.Connection                                        ] - More processing required for authentication of vr-gs0121 using com.hierynomus.smbj.auth.NtlmAuthenticator@9a1dc5f
2020-01-22 14:50:26,836 DEBUG [com.h.s.a.NtlmAuthenticator                                 ] - Received token: a1 81 ce 30 81 cb a0 03 0a 01 01 a1 0c 06 0a 2b 06 01 04 01 82 37 02 02 0a a2 81 b5 04 81 b2 4e 54 4c 4d 53 53 50 00 02 00 00 00 12 00 12 00 38 00 00 00 15 82 8a e2 7b 35 58 08 70 2a 22 ba 00 00 00 00 00 00 00 00 68 00 68 00 4a 00 00 00 0a 00 39 38 00 00 00 0f 56 00 52 00 2d 00 47 00 53 00 30 00 31 00 32 00 31 00 02 00 12 00 56 00 52 00 2d 00 47 00 53 00 30 00 31 00 32 00 31 00 01 00 12 00 56 00 52 00 2d 00 47 00 53 00 30 00 31 00 32 00 31 00 04 00 12 00 76 00 52 00 2d 00 47 00 53 00 30 00 31 00 32 00 31 00 03 00 12 00 76 00 52 00 2d 00 47 00 53 00 30 00 31 00 32 00 31 00 07 00 08 00 e3 4c 5f 2a 05 d1 d5 01 00 00 00 00
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 206
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,CONSTRUCTED,16]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 203
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 3
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0],<unknown>]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 12
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 181
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2],<unknown>]
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1Sequence[[ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0],<unknown>], ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>], ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2],<unknown>]]]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,PRIMITIVE,10]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 1
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1Enumerated[1]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,PRIMITIVE,6]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 10
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1ObjectIdentifier[1.3.6.1.4.1.311.2.2.10]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,PRIMITIVE,4]
2020-01-22 14:50:26,836 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 178
2020-01-22 14:50:26,836 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1OctetString[[78, 84, 76, 77, 83, 83, 80, 0, 2, 0, 0, 0, 18, 0, 18, 0, 56, 0, 0, 0, 21, -126, -118, -30, 123, 53, 88, 8, 112, 42, 34, -70, 0, 0, 0, 0, 0, 0, 0, 0, 104, 0, 104, 0, 74, 0, 0, 0, 10, 0, 57, 56, 0, 0, 0, 15, 86, 0, 82, 0, 45, 0, 71, 0, 83, 0, 48, 0, 49, 0, 50, 0, 49, 0, 2, 0, 18, 0, 86, 0, 82, 0, 45, 0, 71, 0, 83, 0, 48, 0, 49, 0, 50, 0, 49, 0, 1, 0, 18, 0, 86, 0, 82, 0, 45, 0, 71, 0, 83, 0, 48, 0, 49, 0, 50, 0, 49, 0, 4, 0, 18, 0, 118, 0, 82, 0, 45, 0, 71, 0, 83, 0, 48, 0, 49, 0, 50, 0, 49, 0, 3, 0, 18, 0, 118, 0, 82, 0, 45, 0, 71, 0, 83, 0, 48, 0, 49, 0, 50, 0, 49, 0, 7, 0, 8, 0, -29, 76, 95, 42, 5, -47, -43, 1, 0, 0, 0, 0]]
2020-01-22 14:50:26,836 DEBUG [com.h.n.m.NtlmChallenge                                     ] - Windows version = WindowsVersion[WINDOWS_MAJOR_VERSION_10, WINDOWS_MINOR_VERSION_0, 14393, NTLMSSP_REVISION_W2K3]
2020-01-22 14:50:26,836 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvNdDomainName(2) TargetInfo
2020-01-22 14:50:26,836 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvNbComputerName(1) TargetInfo
2020-01-22 14:50:26,837 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvDnsDomainName(4) TargetInfo
2020-01-22 14:50:26,837 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvDnsComputerName(3) TargetInfo
2020-01-22 14:50:26,837 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvTimestamp(7) TargetInfo
2020-01-22 14:50:26,837 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvEOL(0) TargetInfo
2020-01-22 14:50:26,837 DEBUG [com.h.s.a.NtlmAuthenticator                                 ] - Received NTLM challenge from: VR-GS0121
2020-01-22 14:50:26,837 DEBUG [com.h.s.c.Connection                                        ] - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 3 >>
2020-01-22 14:50:26,837 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB2_SESSION_SETUP with message id << 3 >> >>
2020-01-22 14:50:26,837 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB2_SESSION_SETUP with message id << 3 >>
2020-01-22 14:50:26,837 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB2_SESSION_SETUP with message id << 3 >> sent, lock released.
2020-01-22 14:50:26,838 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 3 >>
2020-01-22 14:50:27,115 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@5ab39740
2020-01-22 14:50:27,115 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@5ab39740, now available: 1 credits
2020-01-22 14:50:27,115 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@5ab39740 took << 278 ms >>
2020-01-22 14:50:27,115 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 3 >> to `SMB2_SESSION_SETUP with message id << 3 >>`
2020-01-22 14:51:00,584 INFO  [com.h.s.t.PacketReader                                      ] - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53) ~[smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70) ~[smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48) [smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_222]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_222]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70) ~[smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59) ~[smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48) ~[smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	... 3 more
2020-01-22 14:51:00,585 DEBUG [com.h.s.t.PacketReader                                      ] - Stopping PacketReader...
2020-01-22 14:51:00,588 INFO  [com.h.s.c.Connection                                        ] - Closed connection to VR-GS0121
2020-01-22 14:51:00,589 DEBUG [com.h.s.SMBClient                                           ] - Connection to << VR-GS0121:445 >> closed
2020-01-22 14:51:22,203 INFO  [com.w.p.s.c.i.ClusterProvider                               ] - Initializing components of: cluster
2020-01-22 14:51:22,215 WARN  [com.w.p.s.c.i.ClusterProvider                               ] - UM reload invoked, but URL is the same
2020-01-22 14:51:23,232 ERROR [com.w.p.b.c.r.h.HttpRemoteCommandTransport                  ] - Remote command failed with: java.net.ConnectException, Reason: Connection refused: connect
```

**Comment by hierynomus** [comment]
It seems that the server disconnected the connection. Is there any logging on the server side that points to the problem?

**Comment by SubhasishDey** [comment]
Hi Hierynomous,

I got the below log, it seems we are asking for extra permission, like WRITE_DAC, WRITE_OWNER, DeleteChild. This is send although I am opening the file using AccessMask.MAXIMUM_ALLOWED.

Can you please suggest on this.


Share Information:
	Share Name:		\\*\grpdata
	Share Path:		\??\D:\grpdata
	Relative Target Name:	DORY exchange\QUAL\Error\testfile.txt

Access Request Information:
	Access Mask:		0x1F01FF
	Accesses:		DELETE
				READ_CONTROL
				WRITE_DAC
				WRITE_OWNER
				SYNCHRONIZE
				ReadData (or ListDirectory)
				WriteData (or AddFile)
				AppendData (or AddSubdirectory or CreatePipeInstance)
				ReadEA
				WriteEA
				Execute/Traverse
				DeleteChild
				ReadAttributes
				WriteAttributes
				
Access Check Results:
	DELETE:	Granted by	D:(A;;0x1301bf;;;AU)
				READ_CONTROL:	Granted by	D:(A;;0x1301bf;;;AU)
				WRITE_DAC:	Not granted
				WRITE_OWNER:	Not granted
				SYNCHRONIZE:	Granted by	D:(A;;0x1301bf;;;AU)
				ReadData (or ListDirectory):	Granted by	D:(A;;0x1301bf;;;AU)
				WriteData (or AddFile):	Granted by	D:(A;;0x1301bf;;;AU)
				AppendData (or AddSubdirectory or CreatePipeInstance):	Granted by	D:(A;;0x1301bf;;;AU)
				ReadEA:	Granted by	D:(A;;0x1301bf;;;AU)
				WriteEA:	Granted by	D:(A;;0x1301bf;;;AU)
				Execute/Traverse:	Granted by	D:(A;;0x1301bf;;;AU)
				DeleteChild:	Not granted
				ReadAttributes:	Granted by	D:(A;;0x1301bf;;;AU)
				WriteAttributes:	Granted by	D:(A;;0x1301bf;;;AU)

**Comment by ecki** [comment]
Hm, the maximum_allowed constant seems to be correct. Maybe you see the result of shareaccess.ALL? (And this should not be related to refused authentications?)

https://github.com/hierynomus/smbj/blob/1494c5ca68912c9d58331f0461c30ca16af65a59/src/main/java/com/hierynomus/msdtyp/AccessMask.java#L56

**Comment by SubhasishDey** [comment]
Hi @ecki ...this solution worked for me closing the issue

**Comment by ecki** [comment]
Thanks for,the follow up, can you confirm you changed SMB2ShareAccess.ALL to FILE_SHARE_READ? Any idea why the server terminates without a proper error answer? Is that Win10?

Gruss
Bernd
--
http://bernd.eckenfels.net
________________________________
Von: SubhasishDey ***@***.***>
Gesendet: Thursday, May 20, 2021 11:37:24 AM
An: hierynomus/smbj ***@***.***>
Cc: Bernd ***@***.***>; Mention ***@***.***>
Betreff: Re: [hierynomus/smbj] SMB v2 authentication fails - Unrecognized Windows Sockets error: 0: recv failed (#525)


Hi @ecki<https://github.com/ecki> ...this solution worked for me closing the issue

**Comment by SubhasishDey** [comment]
Hi @ecki 

It was a windows 2016 SMB server and when I give AccessMask.GENERIC_READ instead of AccessMask.MAXIMUM_ALLOWED, the scenario worked.

The below code worked:
getShare().openFile(smbPathDetail.cwdPath, EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, 	null);

Thanks and Regards,
Subhasish
