### ISSUE TITLE
Call to DiskShare.list hangs indefinitely

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#528]
Hi,
  this call hangs indefinitely. Isn't any timeout set somewhere ? 
"Thread-444756" Id=533756 in WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@9304f9
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at com.hierynomus.protocol.commons.concurrent.Promise.tryRetrieve(Promise.java:167)
    at com.hierynomus.protocol.commons.concurrent.Promise.retrieve(Promise.java:122)
    at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:49)
    at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:79)
    at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:27)
    at com.hierynomus.smbj.paths.DFSPathResolver.getReferral(DFSPathResolver.java:414)
    at com.hierynomus.smbj.paths.DFSPathResolver.sendDfsReferralRequest(DFSPathResolver.java:403)
    at com.hierynomus.smbj.paths.DFSPathResolver.step6(DFSPathResolver.java:238)
    at com.hierynomus.smbj.paths.DFSPathResolver.step5(DFSPathResolver.java:199)
    at com.hierynomus.smbj.paths.DFSPathResolver.step2(DFSPathResolver.java:137)
    at com.hierynomus.smbj.paths.DFSPathResolver.step1(DFSPathResolver.java:120)
    at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:107)
    at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:95)
    at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:77)
    at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
    at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:130)
    at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:231)
    at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:204)

**Comment by cliviu** [comment]
Line 414 in DFSPathResolver is    SMB2IoctlResponse response = Futures.get(ioctl, TransportException.Wrapper); which means NO timeout. Am  I right ?  Would it be necessary tu introduce a timeout from the application side  ?

**Comment by hierynomus** [comment]
Makes sense

**Comment by SubhasishDey** [comment]
Hi,

      I have set the timeout and socket timeouts at the SmbConfig.Builder, but still the tread remains stuck.
      Any other way to handle this.
 
      @cliviu  did timeout work for you ?

 Thanks and Regards,
Subhasish
