### ISSUE TITLE
SMB server connection exception while session setup

### ISSUE THREAD

**Issue by SubhasishDey** [hierynomus/smbj#535]
Hi,

We are trying to connect to a SMB server, which fails with below error, the SMB server has enabled NTLMv2.

The exception happens while `Setting << 3 >> to SMB2_SESSION_SETUP with message id << 3 >>`

Can anyone please help me in understanding the reason ?

```
2020-02-23 19:02:18,301 DEBUG [com.h.p.c.s.ProxySocketFactory                              ] - Connecting to topsql278/10.12.11.18:445
2020-02-23 19:02:18,308 DEBUG [com.h.s.t.PacketReader                                      ] - Starting PacketReader on thread: Packet Reader for topsql278
2020-02-23 19:02:18,312 DEBUG [com.h.s.c.Connection                                        ] - Negotiating dialects [SMB_2_0_2, SMB_2_1] with server topsql278
2020-02-23 19:02:18,314 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB_COM_NEGOTIATE >>
2020-02-23 19:02:18,315 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB_COM_NEGOTIATE
2020-02-23 19:02:18,317 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB_COM_NEGOTIATE sent, lock released.
2020-02-23 19:02:18,318 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 0 >>
2020-02-23 19:02:18,325 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@2e54d697
2020-02-23 19:02:18,325 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@2e54d697, now available: 1 credits
2020-02-23 19:02:18,326 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@2e54d697 took << 13 ms >>
2020-02-23 19:02:18,328 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 0 >> to `SMB2_NEGOTIATE with message id << 0 >>`
2020-02-23 19:02:18,329 DEBUG [com.h.s.c.Connection                                        ] - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 1 >>
2020-02-23 19:02:18,329 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB2_NEGOTIATE with message id << 1 >> >>
2020-02-23 19:02:18,329 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB2_NEGOTIATE with message id << 1 >>
2020-02-23 19:02:18,329 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB2_NEGOTIATE with message id << 1 >> sent, lock released.
2020-02-23 19:02:18,330 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 1 >>
2020-02-23 19:02:18,334 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@353e1636
2020-02-23 19:02:18,334 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@353e1636, now available: 1 credits
2020-02-23 19:02:18,334 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@353e1636 took << 5 ms >>
2020-02-23 19:02:18,334 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 1 >> to `SMB2_NEGOTIATE with message id << 1 >>`
2020-02-23 19:02:18,335 DEBUG [com.h.s.c.Connection                                        ] - Negotiated the following connection settings: ConnectionInfo{
  serverGuid=d4510688-e222-4e48-a155-9d8baf4da801,
  serverName='topsql278',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_2_1, maxTransactSize=8388608, maxReadSize=8388608, maxWriteSize=8388608},
  clientGuid=e6ed1066-5a98-4461-bb50-f8a58d43c602,
  clientCapabilities=[SMB2_GLOBAL_CAP_DFS],
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=0,
  serverSecurityMode=1,
  server='null'
}
2020-02-23 19:02:18,335 INFO  [com.h.s.c.Connection                                        ] - Successfully connected to: topsql278
2020-02-23 19:02:18,351 DEBUG [com.h.s.a.NtlmAuthenticator                                 ] - Initialized Authentication of xswmata using NTLM
2020-02-23 19:02:18,357 DEBUG [com.h.s.c.Connection                                        ] - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 2 >>
2020-02-23 19:02:18,357 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB2_SESSION_SETUP with message id << 2 >> >>
2020-02-23 19:02:18,357 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB2_SESSION_SETUP with message id << 2 >>
2020-02-23 19:02:18,357 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB2_SESSION_SETUP with message id << 2 >> sent, lock released.
2020-02-23 19:02:18,358 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 2 >>
2020-02-23 19:02:18,362 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@42235631
2020-02-23 19:02:18,362 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@42235631, now available: 1 credits
2020-02-23 19:02:18,362 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@42235631 took << 5 ms >>
2020-02-23 19:02:18,363 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 2 >> to `SMB2_SESSION_SETUP with message id << 2 >>`
2020-02-23 19:02:18,363 DEBUG [com.h.s.c.Connection                                        ] - More processing required for authentication of xswmata using com.hierynomus.smbj.auth.NtlmAuthenticator@3ac5604e
2020-02-23 19:02:18,363 DEBUG [com.h.s.a.NtlmAuthenticator                                 ] - Received token: a1 81 e0 30 81 dd a0 03 0a 01 01 a1 0c 06 0a 2b 06 01 04 01 82 37 02 02 0a a2 81 c7 04 81 c4 4e 54 4c 4d 53 53 50 00 02 00 00 00 04 00 04 00 38 00 00 00 15 82 89 e2 33 4c 95 94 e7 0f 03 96 00 00 00 00 00 00 00 00 88 00 88 00 3c 00 00 00 0a 00 39 38 00 00 00 0f 4e 00 41 00 02 00 04 00 4e 00 41 00 01 00 14 00 48 00 4f 00 45 00 53 00 51 00 4c 00 31 00 31 00 37 00 38 00 04 00 14 00 4e 00 41 00 2e 00 58 00 4f 00 4d 00 2e 00 63 00 6f 00 6d 00 03 00 2a 00 68 00 6f 00 65 00 73 00 71 00 6c 00 31 00 31 00 37 00 38 00 2e 00 4e 00 41 00 2e 00 58 00 4f 00 4d 00 2e 00 63 00 6f 00 6d 00 05 00 0e 00 58 00 4f 00 4d 00 2e 00 63 00 6f 00 6d 00 07 00 08 00 d7 63 88 0f ae ea d5 01 00 00 00 00
2020-02-23 19:02:18,366 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1]
2020-02-23 19:02:18,366 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 224
2020-02-23 19:02:18,367 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>]
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,CONSTRUCTED,16]
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 221
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0]
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 3
2020-02-23 19:02:18,367 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0],<unknown>]
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1]
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 12
2020-02-23 19:02:18,367 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>]
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2]
2020-02-23 19:02:18,367 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 199
2020-02-23 19:02:18,367 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2],<unknown>]
2020-02-23 19:02:18,368 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1Sequence[[ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0],<unknown>], ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>], ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2],<unknown>]]]
2020-02-23 19:02:18,368 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,PRIMITIVE,10]
2020-02-23 19:02:18,368 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 1
2020-02-23 19:02:18,368 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1Enumerated[1]
2020-02-23 19:02:18,368 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,PRIMITIVE,6]
2020-02-23 19:02:18,368 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 10
2020-02-23 19:02:18,368 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1ObjectIdentifier[1.3.6.1.4.1.311.2.2.10]
2020-02-23 19:02:18,368 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 tag ASN1Tag[UNIVERSAL,PRIMITIVE,4]
2020-02-23 19:02:18,368 TRACE [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object length: 196
2020-02-23 19:02:18,368 DEBUG [com.h.a.ASN1InputStream                                     ] - Read ASN.1 object: ASN1OctetString[[78, 84, 76, 77, 83, 83, 80, 0, 2, 0, 0, 0, 4, 0, 4, 0, 56, 0, 0, 0, 21, -126, -119, -30, 51, 76, -107, -108, -25, 15, 3, -106, 0, 0, 0, 0, 0, 0, 0, 0, -120, 0, -120, 0, 60, 0, 0, 0, 10, 0, 57, 56, 0, 0, 0, 15, 78, 0, 65, 0, 2, 0, 4, 0, 78, 0, 65, 0, 1, 0, 20, 0, 72, 0, 79, 0, 69, 0, 83, 0, 81, 0, 76, 0, 49, 0, 49, 0, 55, 0, 56, 0, 4, 0, 20, 0, 78, 0, 65, 0, 46, 0, 88, 0, 79, 0, 77, 0, 46, 0, 99, 0, 111, 0, 109, 0, 3, 0, 42, 0, 104, 0, 111, 0, 101, 0, 115, 0, 113, 0, 108, 0, 49, 0, 49, 0, 55, 0, 56, 0, 46, 0, 78, 0, 65, 0, 46, 0, 88, 0, 79, 0, 77, 0, 46, 0, 99, 0, 111, 0, 109, 0, 5, 0, 14, 0, 88, 0, 79, 0, 77, 0, 46, 0, 99, 0, 111, 0, 109, 0, 7, 0, 8, 0, -41, 99, -120, 15, -82, -22, -43, 1, 0, 0, 0, 0]]
2020-02-23 19:02:18,370 DEBUG [com.h.n.m.NtlmChallenge                                     ] - Windows version = WindowsVersion[WINDOWS_MAJOR_VERSION_10, WINDOWS_MINOR_VERSION_0, 14393, NTLMSSP_REVISION_W2K3]
2020-02-23 19:02:18,371 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvNdDomainName(2) TargetInfo
2020-02-23 19:02:18,371 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvNbComputerName(1) TargetInfo
2020-02-23 19:02:18,371 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvDnsDomainName(4) TargetInfo
2020-02-23 19:02:18,371 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvDnsComputerName(3) TargetInfo
2020-02-23 19:02:18,372 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvDnsTreeName(5) TargetInfo
2020-02-23 19:02:18,372 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvTimestamp(7) TargetInfo
2020-02-23 19:02:18,372 TRACE [com.h.n.m.NtlmChallenge                                     ] - NTLM channel contains MsvAvEOL(0) TargetInfo
2020-02-23 19:02:18,372 DEBUG [com.h.s.a.NtlmAuthenticator                                 ] - Received NTLM challenge from: NA
2020-02-23 19:02:18,381 DEBUG [com.h.s.c.Connection                                        ] - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 3 >>
2020-02-23 19:02:18,381 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Acquiring write lock to send packet << SMB2_SESSION_SETUP with message id << 3 >> >>
2020-02-23 19:02:18,381 DEBUG [com.h.s.t.t.d.DirectTcpTransport                            ] - Writing packet SMB2_SESSION_SETUP with message id << 3 >>
2020-02-23 19:02:18,382 TRACE [com.h.s.t.t.d.DirectTcpTransport                            ] - Packet SMB2_SESSION_SETUP with message id << 3 >> sent, lock released.
2020-02-23 19:02:18,382 DEBUG [com.h.p.c.c.Promise                                         ] - Awaiting << 3 >>
2020-02-23 19:02:18,387 DEBUG [com.h.s.t.PacketReader                                      ] - Received packet com.hierynomus.mssmb2.SMB2PacketData@14166838
2020-02-23 19:02:18,387 DEBUG [com.h.s.c.Connection                                        ] - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@14166838, now available: 1 credits
2020-02-23 19:02:18,387 TRACE [com.h.s.c.Connection                                        ] - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@14166838 took << 6 ms >>
2020-02-23 19:02:18,387 DEBUG [com.h.p.c.c.Promise                                         ] - Setting << 3 >> to `SMB2_SESSION_SETUP with message id << 3 >>`
2020-02-23 19:02:52,648 INFO  [com.h.s.t.PacketReader                                      ] - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
	... 3 more
2020-02-23 19:02:52,648 DEBUG [com.h.s.t.PacketReader                                      ] - Stopping PacketReader...
2020-02-23 19:02:52,650 INFO  [com.h.s.c.Connection                                        ] - Closed connection to topsql278
2020-02-23 19:02:52,652 DEBUG [com.h.s.SMBClient                                           ] - Connection to << topsql278:445 >> closed
```

**Comment by SubhasishDey** [comment]
This server gets connected by a Linux mount and functions without any issues, using below command

//<Windows2016Server/<SharedWindowsfolder> <localDirectoryonLinuxserver> cifs credentials=<credentialstoConnecttoWindowsServer>,_netdev,users,rw,noauto,uid=<localLinuxID>,gid=<LinuxID>,soft,nocase,sec=ntlmv2 0 0
//topsql278/Silversands_Shared /opt/wm/wmfs/topsql278_mnt cifs credentials=/opt/wm/cifs.credentials,_netdev,users,rw,noauto,uid=wmadm,gid=wmadm,soft,nocase,sec=ntlmv2 0 0

this entry needs to be added to /etc/fstab

**Comment by hierynomus** [comment]
Have you checked the server logs? The server is disconneting the socket while smbj is setting up the session.

**Comment by SubhasishDey** [comment]
Somehow it is not possible for us to get the thirdparty server logs, but as per our admin team we need to explicitly set sec=ntlmv2 0 in the mount to get it work.

Is there any way we can specify it in the library ?

**Comment by ecki** [comment]
The NTLMAuthenticator uses NTMLv2. It even should support singing (enhanced security) but maybe that part is untested (https://github.com/hierynomus/smbj/blob/a8c74679c977946ff99a68cd19e69c6b20cf93d6/src/main/java/com/hierynomus/smbj/auth/NtlmAuthenticator.java#L121)

**Comment by SubhasishDey** [comment]
Hi ecki,

       Thanks for your reply. Just to add, this server works fine for other smb clients with the same configuration, and also we as a client are able to communicate to other SMB servers.

I have attached a winshark screenshot from a different instance having the same issue.
Here 10.60.30.158 is the server.
![WiresharkSnapshot](https://user-images.githubusercontent.com/16436150/77138176-041f7d80-6a97-11ea-873b-9726a1d2adf0.png)

**Comment by ecki** [comment]
Th empty domain in packet 423 looks rather strange, can you compare that with a working client?

**Comment by SubhasishDey** [comment]
Hi ecki,

The success scenario also has an empty domain from the same client but a different server (10.60.31.231)

![image](https://user-images.githubusercontent.com/16436150/77139169-fe2b9b80-6a9a-11ea-8588-60c32c17bd31.png)

**Comment by ecki** [comment]
Do you have a non smbj client which can connect to the failing server? What is the difference between the two servers? (I think Windows is a bit less restrictive than samba or NAS software).

**Comment by SubhasishDey** [comment]
Hi,

     I have got another such instance where it is failing for authentication in the Second Session Setup request at line 107 with STATUS_NOT_SUPPORTED. Can anyone please help me understand why am I getting this error.
Just to remind that the server is NTLM v2 and when mounted in a Linux server, it works fine.

Thanks again for your attention.

![AnotherNetworkTrace](https://user-images.githubusercontent.com/16436150/79122121-8bb98d00-7db4-11ea-977e-d8a8b04eacb3.png)

**Comment by SubhasishDey** [comment]
The issue was actually on the network side. So closing this issue.
Thanks @ecki @hierynomus  for your valuable inputs
