### ISSUE TITLE
com.hierynomus.smbj.event.SMBEventBus - PublicationError

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#536]
> ERROR com.hierynomus.smbj.event.SMBEventBus - PublicationError{
	cause=java.lang.reflect.InvocationTargetException
	message='Error during invocation of message handler. There might be an access rights problem. Do you use non public inner classes?'
	handler=private void com.hierynomus.smbj.connection.Connection.sessionLogoff(com.hierynomus.smbj.event.SessionLoggedOff)
	listener=com.hierynomus.smbj.connection.Connection@7714f57d
	publishedMessage=com.hierynomus.smbj.event.SessionLoggedOff@30000c38}
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29) [mbassador-1.3.0.jar:?]
	at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30) [mbassador-1.3.0.jar:?]
	at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42) [mbassador-1.3.0.jar:?]
	at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72) [mbassador-1.3.0.jar:?]
	at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49) [mbassador-1.3.0.jar:?]
	at net.engio.mbassy.bus.SyncMessageBus.publish(SyncMessageBus.java:48) [mbassador-1.3.0.jar:?]
	at com.hierynomus.smbj.event.SMBEventBus.publish(SMBEventBus.java:60) [smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.session.Session.logoff(Session.java:261) [smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.session.Session.close(Session.java:292) [smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.connection.Connection.close(Connection.java:155) [smbj-0.1.0.jar:0.1.0-SNAPSHOT]
	at com.hierynomus.smbj.connection.Connection.close(Connection.java:140) [smbj-0.1.0.jar:0.1.0-SNAPSHOT]

Hi I got the above exception, May I know why am I getting that exception. The code is as follows

`    public long getFileSize() {
        try (Connection connection = smbClient.connect(getUserCredentials().get("HOSTNAME")))
        {
            AuthenticationContext ac = new AuthenticationContext(getUserCredentials().get("USERNAME"), getUserCredentials().get("PASSWORD").toCharArray(), getUserCredentials().get("DOMAIN"));

            Session session = connection.authenticate(ac);

            DiskShare diskShare = (DiskShare) session.connectShare(getShareInfo().get("SHARENAME"));

            Long fileSize = diskShare.getFileInformation(getShareInfo().get("EXTRACTEDFILEPATH")).getStandardInformation().getEndOfFile();//No I18N
            return fileSize;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return 0;
    }`

**Comment by ecki** [comment]
It looks like the NPE happens in your code (your FilteredMessageDispatcher calls a subscriber which is accessing a null field. Note that [SessionLoggedOff only has a sessionid member set](https://github.com/hierynomus/smbj/blob/600b4e1e651f513e0bf16559d1bd32b98323a5c1/src/main/java/com/hierynomus/smbj/session/Session.java#L153), not sure if that can be null. You should find it by logging all access to that event. 

BTW is the 0.1.0 Version correct? Don't think anybody can provide answers for that ancient code.

**Comment by felixRajkumar** [comment]
> It looks like the NPE happens in your code (your FilteredMessageDispatcher calls a subscriber which is accessing a null field. Note that [SessionLoggedOff only has a sessionid member set](https://github.com/hierynomus/smbj/blob/600b4e1e651f513e0bf16559d1bd32b98323a5c1/src/main/java/com/hierynomus/smbj/session/Session.java#L153), not sure if that can be null. You should find it by logging all access to that event.
> 
> BTW is the 0.1.0 Version correct? Don't think anybody can provide answers for that ancient code. Your shown code is not relevant to the exception.

This is the latest version. I built the code and currently using it for AES encryption. Can you explain this a little more of why the error has occured

**Comment by hierynomus** [comment]
`[smbj-0.1.0.jar:0.1.0-SNAPSHOT]` I'm pretty sure is not the latest released version.
