### ISSUE TITLE
Proguard configuration?

### ISSUE THREAD

**Issue by 3c71** [hierynomus/smbj#538]
Hello,

After building the APK for release (with R8/proguard), I noticed smb support fails I keep getting an exception when calling list() and no other logs that could help determine the missing classes.

Any help appreciated.

g has already been closed
        at com.hierynomus.smbj.share.Share.send(Share.java:356)
        at com.hierynomus.smbj.share.Share.ioctlAsync(Share.java:346)
        at com.hierynomus.smbj.share.Share.ioctlAsync(Share.java:326)
        at com.hierynomus.smbj.paths.DFSPathResolver.getReferral(DFSPathResolver.java:413)
        at com.hierynomus.smbj.paths.DFSPathResolver.sendDfsReferralRequest(DFSPathResolver.java:403)
        at com.hierynomus.smbj.paths.DFSPathResolver.step6(DFSPathResolver.java:238)
        at com.hierynomus.smbj.paths.DFSPathResolver.step5(DFSPathResolver.java:199)
        at com.hierynomus.smbj.paths.DFSPathResolver.step2(DFSPathResolver.java:137)
        at com.hierynomus.smbj.paths.DFSPathResolver.step1(DFSPathResolver.java:120)
        at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:107)
        at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:95)
        at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:77)
        at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
        at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:130)
        at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:237)
        at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:210)

**Comment by ecki** [comment]
Does it work without proguard?

Closing the objects at the wrong time is a common cause of problems, but that should not be related to proguard. Also the connection reuse, reconnect for DFS is an open point. Or actually was discussed, maybe check back in the other issues and also provide your code with an repeatable example.

**Comment by 3c71** [comment]
yes it works with proguard, otherwise I wouldn't ask.

**Comment by ecki** [comment]
You mean it works or it doesn't work?

**Comment by 3c71** [comment]
sorry typo, it works perfect without proguard. it fails as soon as I "proguard" the apk.

In the mean time I tried to enable logs, but it doesn't work and I suspect proguard to remove some classes for that too. Bummer, hoped to get some error or message that could help figure out which classes are missing, but nope.

**Comment by ecki** [comment]
It is probably easiest to Instrument the client, connection, session and so on and println or debug the close() (or finalizer) invocations

**Comment by 3c71** [comment]
Easiest if I pull the whole source code and modify locally. 

For now I've added these to proguard, it still fails but I got some logs:
-keep class com.hierynomous.**{ *; }
-keep class org.slf4j.**{*;}

The logs shows it fails just after this:
2020-03-10 22:34:08.204 24927-25094/? I/3c.smbj:a: Starting DFS resolution for \\xx.yy.z.zzz\data

So I removed withDfsEnabled(true), and now it works!

Why would it work with DFS enabled in debug mode and not release/proguard ? Maybe here it's no proguard but simply debug/release ? There is however no logs to indicate so?

I'll revert proguard changes and see how it works without now and let you know.

**Comment by 3c71** [comment]
Ok, my bad, there seems to be no need for specific proguard rules. At least without DFS enabled. Not sure if proguard or release mode breaks it, haven't digged further, as I've had enough sync+build delays for the day.
