### ISSUE TITLE
Logs show a lot of connexions leaked

### ISSUE THREAD

**Issue by 3c71** [hierynomus/smbj#540]
It seems response bodies are never closed and I get many of those similar logs:

A connection to xxxxxxxxx was leaked. Did you forget to close a response body?
2020-03-21 12:39:07.457 28144-29092/xxxx W/OkHttp: java.lang.Throwable: response.body().close()
2020-03-21 12:39:07.457 28144-29092/xxxx W/OkHttp:     at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.kt:134)
2020-03-21 12:39:07.457 28144-29092/xxxx W/OkHttp:     at okhttp3.internal.connection.RealCall.callStart(RealCall.kt:166)
2020-03-21 12:39:07.457 28144-29092/xxxx W/OkHttp:     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:145)

**Comment by hierynomus** [comment]
SMBJ does not use or rely on OkHttp. You might want to check your own code, this does not seem to have anything to do with SMBJ.

**Comment by 3c71** [comment]
OMG, I'm sorry, posted this to the wrong git.
