### ISSUE TITLE
Thread getting stuck for more than 10 minutes during login

### ISSUE THREAD

**Issue by SubhasishDey** [hierynomus/smbj#578]
Hi,

  We are finding that the SMBJ client stucks during connect for a period of 10 mins or more even if the socket timeouts are set in the SMBConfig.

  We see the below thread dump, any hint from anyone will be deeply appreciated.

Id=488 in TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	- waiting on <0x08e6d37d> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at com.hierynomus.protocol.commons.concurrent.Promise.tryRetrieve(Promise.java:170)
	at com.hierynomus.protocol.commons.concurrent.Promise.retrieve(Promise.java:134)
	at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:58)
	at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:84)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
	at com.hierynomus.smbj.connection.Connection.multiProtocolNegotiate(Connection.java:340)
	at com.hierynomus.smbj.connection.Connection.negotiateDialect(Connection.java:310)
	at com.hierynomus.smbj.connection.Connection.connect(Connection.java:120)
	at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:103)
	- locked <0x04f57371> (a com.hierynomus.smbj.SMBClient)

**Comment by ecki** [comment]
Can you show the other threads as well?

Without looking too deep into it, my experience in this area are broken DFS scenarios with dangling Server references. Did you try to target a server directly and turn DFS of?

**Comment by SubhasishDey** [comment]
Hi ecki,

     Thanks for your reply, I have not set the dfs explicitly so I think it is false by default.
      But I will explicitly set it false and retry and look for any occurrence as this issue doesnot happen always.

Thanks and Regards,
Subhasish

**Comment by hierynomus** [comment]
@SubhasishDey Any update on this?

**Comment by SubhasishDey** [comment]
Hi @hierynomus / @ecki ,

I toggled the dfs setting for different server and dfs shares and then figured that the actual issue occurs when we try to connect to a non DFS server with DFS enabled in the smbj client.
We have set the timeout, but we still see this thread stack.
This  hangs forever.

`"HTTP Handler 127.0.0.1" Id=21030 in WAITING
	at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	- waiting on <0x7273ba4c> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at com.hierynomus.protocol.commons.concurrent.Promise.tryRetrieve(Promise.java:167)
	at com.hierynomus.protocol.commons.concurrent.Promise.retrieve(Promise.java:122)
	at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:49)
	at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:79)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:27)
	at com.hierynomus.smbj.paths.DFSPathResolver.getReferral(DFSPathResolver.java:414)
	at com.hierynomus.smbj.paths.DFSPathResolver.sendDfsReferralRequest(DFSPathResolver.java:403)
	at com.hierynomus.smbj.paths.DFSPathResolver.step6(DFSPathResolver.java:238)
	at com.hierynomus.smbj.paths.DFSPathResolver.step5(DFSPathResolver.java:199)
	at com.hierynomus.smbj.paths.DFSPathResolver.step2(DFSPathResolver.java:137)
	at com.hierynomus.smbj.paths.DFSPathResolver.step1(DFSPathResolver.java:120)
	at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:107)
	at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:95)
	at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:77)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
	at com.hierynomus.smbj.share.DiskShare.getFileInformation(DiskShare.java:261)
	at com.hierynomus.smbj.share.DiskShare.getFileInformation(DiskShare.java:254)
	at com.softwareag.mft.client.SMBClientV2p.stat(SMBClientV2p.java:182)
	at com.softwareag.mft.client.SMBClientV2p.doCWD(SMBClientV2p.java:696)`
	
Thanks and Regards,
Subhasish

**Comment by hierynomus** [comment]
@SubhasishDey Current master contains a fix for the hanging of the `getReferral` call. I'm not sure why your server does not respond.

**Comment by SubhasishDey** [comment]
Thanks @hierynomus …I will take the update. 
Our suspect on why the server doesnot respond was because its not  a DFS server in a network restricted area. 

Anyways.. thanks again...I will test wit your inputs.

**Comment by hierynomus** [comment]
I'm adding one additional fix, should be ready end of day today.

**Comment by hierynomus** [comment]
Additional fix is also merged. Good luck testing.

**Comment by shanthankumar24** [comment]
Hi @hierynomus 

The fix is working fine for us , will it be part of the official release of 0.11.2? If so when can we expect it to be released?

**Comment by hierynomus** [comment]
Yes, it will be part of the next release.
