### ISSUE TITLE
Connec to server :  SMB2_SESSION_SETUP with message id << 1 >> as transport is disconnected

### ISSUE THREAD

**Issue by MilosSvrcek** [hierynomus/smbj#596]
Hi,
I am connecting to the Linux server, but some times i have issue below. It is happening by the second connect, first connect is right but second not. 
Another connections to the server is right (over 200 connections).

The app is a java service running on Linux, which is connecting to another servers.

Thank you for help or some information about Error logs.

Error :

Session session = dstCon.authenticate(ac2);
ERROR 1 :
[Packet Reader for srv1] INFO com.hierynomus.smbj.transport.PacketReader - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:72)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: EOF while reading packet
	... 6 more

ERROR 2 : 
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 1 >> as transport is disconnected
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:215)
	at test.service.runJob(jobs.java:115)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 1 >> as transport is disconnected
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68)
	at com.hierynomus.smbj.connection.Connection.send(Connection.java:297)
	at com.hierynomus.smbj.connection.Connection.sendAndReceive(Connection.java:305)
	at com.hierynomus.smbj.connection.Connection.initiateSessionSetup(Connection.java:244)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:181)
	... 4 more

**Comment by hierynomus** [comment]
Are you reusing clients/connections/sessions?

**Comment by MilosSvrcek** [comment]
What do you mean reusing?
Example:    
I create connection on the server and do some things, then I close connection. After one hour I have to create connection and do some things again and close connection.
So after every time I close connection, I have to create them again.
SMB2 have some cache, which one has information about connection?

**Comment by Higurashi-kagome** [comment]
My case is, I closed the connnection before my operation (authenticate or connectShare) finish.
