### ISSUE TITLE
Unable to establish session "withEncryptData" for "KDF/Counter/HMACSHA256" 

### ISSUE THREAD

**Issue by pranaysharmamanulife** [hierynomus/smbj#608]
getDerivationFunction fails with parameter - "KDF/Counter/HMACSHA256"
`
Exception in thread "main" java.lang.UnsupportedOperationException
        at com.hierynomus.security.jce.JceSecurityProvider.getDerivationFunction(JceSecurityProvider.java:64)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:290)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:173)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:142)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
        at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:192)
        at com.example.demo.DemoApplication.main(DemoApplication.java:49)
`
Config -

`
		SmbConfig config = SmbConfig.builder().withDfsEnabled(true	)
		.withEncryptData(true)		
		.withDialects(SMB2Dialect.SMB_3_0_2)
		.withNegotiatedBufferSize()
                .build();

`
Same call with "withEncryptData(false)" is successful.

**Comment by pranaysharmamanulife** [comment]
Adding 
`
		.withSecurityProvider(new BCSecurityProvider())
`
fixes above error, but then results in 
`
Exception in thread "main" com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Message signing is required, but no signing key is negotiated
        at com.hierynomus.smbj.session.Session.connectTree(Session.java:175)
`

Adding 

`
		.withSigningRequired(true)
`
creates error - "Message signing is required, but no signing key is negotiated"

**Comment by pranaysharmamanulife** [comment]
.withSigningRequired(true) and 		.withEncryptData(true)	 fix the issue
