### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException: STATUS_OTHER (0xc0000205)

### ISSUE THREAD

**Issue by SShnoodles** [hierynomus/smbj#611]
Query directory failed for SMB2FileId{persistentHandle=15 44 03 00 60 02 00 00}

```text
com.hierynomus.mssmb2.SMBApiException: STATUS_OTHER (0xc0000205): Query directory failed for SMB2FileId{persistentHandle=15 44 03 00 60 02 00 00}
	at com.hierynomus.smbj.share.Share.receive(Share.java:371)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:351)
	at com.hierynomus.smbj.share.Share.queryDirectory(Share.java:217)
	at com.hierynomus.smbj.share.Directory$DirectoryIterator.queryDirectory(Directory.java:173)
	at com.hierynomus.smbj.share.Directory$DirectoryIterator.<init>(Directory.java:129)
	at com.hierynomus.smbj.share.Directory.iterator(Directory.java:107)
	at com.hierynomus.smbj.share.Directory.list(Directory.java:62)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:241)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:210)
```

```text
DiskShare share = (DiskShare) session.connectShare(shareDir);
List<FileIdBothDirectoryInformation> fileList = share.list("receive");  // query the directory error
```

The "receive" directory is exist, and more than 20 files in the folder.
I can't find the reason.

**Comment by hierynomus** [comment]
The server has insufficient resources. An `STATUS_OTHER` status code means this one is not mapped yet. Looking it up in [MS-ERREF](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) gives:

```
0xC0000205   STATUS_INSUFF_SERVER_RESOURCES | Insufficient server resources exist to complete the request.
```

You will need to look up how to configure the server to have more resources available to your request.

**Comment by hierynomus** [comment]
I've added the enum to the NtStatus enum. Other than that, smbj cannot do anything else for this status, the server should get more resources.

I'm closing this ticket.
