### ISSUE TITLE
Message signing is required using SMB 3_0_2, Similar to issue 243

### ISSUE THREAD

**Issue by vrr6** [hierynomus/smbj#618]
aused by: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Message signing is required, but no signing key is negotiated
        at com.hierynomus.smbj.session.Session.connectTree(Session.java:175)
        at com.hierynomus.smbj.session.Session.connectShare(Session.java:113)
        at org.apache.camel.component.smbj.SmbFileOperations.createShare(SmbFileOperations.java:442)
        at org.apache.camel.component.smbj.SmbFileOperations.invokeOnDiskShare(SmbFileOperations.java:542)
        at org.apache.camel.component.smbj.SmbFileOperations.listFiles(SmbFileOperations.java:331)
        ... 11 common frames omitted
        Suppressed: com.hierynomus.protocol.transport.TransportException: Message signing is required, but no signing key is negotiated
                at com.hierynomus.smbj.session.Session.send(Session.java:296)
                at com.hierynomus.smbj.session.Session.logoff(Session.java:256)
                at com.hierynomus.smbj.session.Session.close(Session.java:279)
                at org.apache.camel.component.smbj.SmbFileOperations.invokeOnDiskShare(SmbFileOperations.java:545)
                ... 12 common frames omitted

**Comment by hierynomus** [comment]
Which version of SMBJ are you using?

**Comment by vrr6** [comment]
I am using latest Master Branch

**Comment by vrr6** [comment]
Team this is a duplicate of https://github.com/hierynomus/smbj/issues/617 please feel free to close it.
