### ISSUE TITLE
Unable to access NFS Share from Linux machine using SMBJ

### ISSUE THREAD

**Issue by vrr6** [hierynomus/smbj#619]
Hi Team,

getting below exception when trying to connect to NFS share using SMBJ 

I am using latest Master branch and version 3_1_1.

y: org.apache.camel.component.file.GenericFileOperationFailedException: Could not create connection
        at org.apache.camel.component.smbj.SmbFileOperations.createConnection(SmbFileOperations.java:418)
        at org.apache.camel.component.smbj.SmbFileOperations.invokeOnDiskShare(SmbFileOperations.java:540)
        at org.apache.camel.component.smbj.SmbFileOperations.listFiles(SmbFileOperations.java:331)
        ... 11 common frames omitted
Caused by: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
        at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:30)

**Comment by neoxpert** [comment]
If it really is a pure NFS share, SMBJ is not the proper solution, as this is a totally different protocol.

Maybe have a look at https://github.com/raisercostin/yanfs or https://github.com/EMCECS/nfs-client-java .

**Comment by hierynomus** [comment]
@vrr6 Does the answer from @neoxpert answer your question? If not, please elaborate.

**Comment by hierynomus** [comment]
Any update on this @vrr6?

**Comment by vrr6** [comment]
Please close the ticket,  yes answer fulfilled my request.

Thank you

**Comment by hierynomus** [comment]
ok, closing, thanks!
