### ISSUE TITLE
Message signing is required, but no signing key is negotiated on current master

### ISSUE THREAD

**Issue by mseleng** [hierynomus/smbj#633]
Hi,

I've decided to give the newest master a try in order to use SMBv3.x. However, I quite stumbled upon this exception. The full trace:

        com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Message signing is required, but no signing key is negotiated
        at com.hierynomus.smbj.session.Session.connectTree(Session.java:175)
        at com.hierynomus.smbj.session.Session.connectShare(Session.java:113)
        at com.example.SambaHelper.listFiles(App.kt:62)
        at com.example.App$onCreate$1.invoke(App.kt:38)
        at com.example.App$onCreate$1.invoke(App.kt:37)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
     Caused by: com.hierynomus.protocol.transport.TransportException: Message signing is required, but no signing key is negotiated
        at com.hierynomus.smbj.session.Session.send(Session.java:296)
        at com.hierynomus.smbj.session.Session.connectTree(Session.java:124)
        at com.hierynomus.smbj.session.Session.connectShare(Session.java:113) 
        at com.example.SambaHelper.listFiles(App.kt:62) 
        at com.example.App$onCreate$1.invoke(App.kt:38) 
        at com.example.App$onCreate$1.invoke(App.kt:37) 
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) 

It's obvious that my simple config is missing something. Could you please point me in the correct direction? (In debugger, I can see, that The negotiated dialect is SMB 3.0.2, which should be fine, but somehow I don't know what to do next).

I am using basic client with no config as well as plain `AuthenticationContext`. Thanks for any advices!

**Comment by hierynomus** [comment]
This should be fixed by #631

**Comment by mseleng** [comment]
That works, thanks. This can be closed.
