### ISSUE TITLE
STATUS_OTHER (0xc0000001): Create failed

### ISSUE THREAD

**Issue by chbushan** [hierynomus/smbj#634]
Hi, 

This was working fine and all of sudden these errors; Nothing changed either to security or the SMB shares.
Could you please help?

2021-05-18 18:01:55.699     85 com.hierynomus.mssmb2.SMBApiException: STATUS_OTHER (0xc0000001): Create failed for
2021-05-18 18:01:55.700     85  at com.hierynomus.smbj.share.Share.receive(Share.java:366)
2021-05-18 18:01:55.700     85  at com.hierynomus.smbj.share.Share.sendReceive(Share.java:346)
2021-05-18 18:01:55.700     85  at com.hierynomus.smbj.share.Share.createFile(Share.java:159)
2021-05-18 18:01:55.700     85  at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:97)
2021-05-18 18:01:55.700     85  at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:79)
2021-05-18 18:01:55.700     85  at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
2021-05-18 18:01:55.700     85  at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:148)

**Comment by yin19941005** [comment]
Looking it up in [MS-ERREF](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) gives:
```
0xC0000001   STATUS_UNSUCCESSFUL | {Operation Failed} The requested operation was unsuccessful.
```

I guess we need more info to figure out what's happening.

**Comment by hierynomus** [comment]
I've added the status to the NtStatus enum. I think you should be able to find in the server log what's going wrong. Any NtStatus code is generated by the server, so in its logging you should be able to find more information.

**Comment by chbushan** [comment]
Thanks for the reply; I will get in touch with network admins to check for the smb logs and report back.

**Comment by chbushan** [comment]
The windows team claims no logs.  I see the connections are successful but it only fails when trying to pull data. 

com.hierynomus.mssmb2.SMBApiException: STATUS_OTHER (0xc0000001): Create failed for \\server.com\group1$\source\DV\\001\\Inx1.taraa

I see this [Thread-57] INFO com.hierynomus.smbj.session.Session - Connecting to \\server.com\group1$ on session 4696691461546950240 
The windows support team cannot find anything with the session ID's either.

Thanks for your help.

**Comment by hierynomus** [comment]
I have no idea either. The status code indicates that "something" caused it to be unsuccessful. What are the parameters you're passing to the `DiskShare.openFile(...)`?
