### ISSUE TITLE
com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired

### ISSUE THREAD

**Issue by gturri** [hierynomus/smbj#646]
Hi,

(this is going to look like #636 , but since this other bug report doesn't have more context than a stacktrace, I guess it's more relevant to open a new one).

I'm using smbj to copy a small file to some Windows nodes but on some of them I'm experiencing failures that I don't understand (in particular because all nodes are provisioned in the same way). Here is my code:

```
try {
  SmbConfig config = SmbConfig.builder()
          .withSigningRequired(false)
          .withTransportLayerFactory(new DirectTcpTransportFactory<SMBPacket<?>>())
          .withSecurityProvider(new BCSecurityProvider())
          .build();
  SMBClient client = new SMBClient(config);
  Connection connection = client.connect("myNodeAdress", 445);
  String domain = "myDomain";

  Session session = connection.authenticate(new AuthenticationContext("my-user", "myPassword".toCharArray(), domain));
  DiskShare share = (DiskShare) session.connectShare("C$");

  String path = "WINDOWS\\TEMP\\SomeFile.txt";
  com.hierynomus.smbj.share.File file = share.openFile(path, EnumSet.of(AccessMask.GENERIC_WRITE), null, EnumSet.of(SMB2ShareAccess.FILE_SHARE_WRITE), SMB2CreateDisposition.FILE_OVERWRITE_IF, null);
  OutputStream destStream = file.getOutputStream();
  IOUtils.copy(inputStream, destStream);

  destStream.close();
  file.close();
  connection.close();
} catch (Exception e){
    // handle exception 
}

```

What I observe with this code is that:
- it works succesfully on most of my nodes. ie: my file is correctly copied and it takes less than 1s
- however on some nodes it fails, and when it does then it fails 100% of the time of those nodes. What I mean by fail is that:
- the call to `destStream.close()` hangs for 1 minute and then it throws thise exception

```
Exception com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired	at com.hierynomus.smbj.share.Share.receive(Share.java:349)
	at com.hierynomus.smbj.share.Share.receive(Share.java:331)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.write(Share.java:196)
	at com.hierynomus.smbj.share.File.write(File.java:86)
	at com.hierynomus.smbj.share.FileOutputStream.sendWriteRequest(FileOutputStream.java:91)
	at com.hierynomus.smbj.share.FileOutputStream.close(FileOutputStream.java:98)
```

- also I observe that my remote file is actually created, but it is empty.

I must admit I'm a bit lost at this point:
- since my code works on most nodes then I guess my code is somewhat correct
- since it usually makes the copy in less than 1s then I guess it wouldn't help to just increase the timeout
- since, even when my code fails, it creates my remote file (though it is left empty) then it means that my code can actually connect to the remote host (eg: it's not some credential issue then)

So my questions are:
- does it look like a known behavior?
- would you have advice to help me understand why I'm experiencing those issues and to fix it?

(note that if it ends up being some bug in smbj, then I would be happy to try to submit a patch))

Thanks in advance!

Nb: note sure if it's an important information, but I'm using smbj 0.3.0

**Comment by hierynomus** [comment]
Hi Guillaume,

I'm not sure, but I would at least advise you to upgrade to the latest version (0.11.1) of smbj. A lot has been fixed since 0.3.0

**Comment by gturri** [comment]
Thanks for this fast feedback!

I just gave 0.11.1 a try (with the same code as above, I just had to turn the line `.withTransportLayerFactory(new DirectTcpTransportFactory<SMBPacket<?>>())` into `.withTransportLayerFactory(new DirectTcpTransportFactory<SMBPacketData<?>, SMBPacket<?, ?>>()` to get it to build). 

I get a this stacktrace
```
Exception com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired	at com.hierynomus.smbj.share.Share.receive(Share.java:411)
	at com.hierynomus.smbj.share.Share.receive(Share.java:393)
	at com.hierynomus.smbj.share.Share.write(Share.java:221)
	at com.hierynomus.smbj.share.SMB2Writer.write(SMB2Writer.java:103)
	at com.hierynomus.smbj.share.FileOutputStream.sendWriteRequest(FileOutputStream.java:90)
	at com.hierynomus.smbj.share.FileOutputStream.close(FileOutputStream.java:97)
	at com.dtolabs.rundeck.plugin.overthere.OTWinRMFileCopier.myCopyFileStream(OTWinRMFileCopier.java:150)
```
which is pretty similar to the one I had before (the line numbers are different, the reference to SMB2Writer is new, but besides this it looks pretty much like the previous one).

I'll dig into smbj code in order to try to get a better understanding of this issue. If you have any pointers or advice to go on with this, I'll be glad to here it! :)

**Comment by arunans23** [comment]
@gturri Did you solve the issue?

**Comment by gturri** [comment]
I'm afraid my issue was solved because my company migrated their servers to Linux, so, no more dealing with smb for us.
I'm sorry, I don't have any useful information for you  @arunans23  😕
