### ISSUE TITLE
Why libs in pom have runtime scope?

### ISSUE THREAD

**Issue by ndimitry** [hierynomus/smbj#648]
Now for each module that uses smbj it is required to plainly add all the dependencies, because otherwise they are not found (because of marked runtime). This also means that each time smbj will have a new license on the list... all who update smbj version will face errors, probably somewhere deep during runtime. This is super uncomfortable...

**Comment by ndimitry** [comment]
I see that there is only a gradle build data, so pom seems to be automatically created (for backwards compatibility). And the way it is formed contains scope "runtime" with all described above problems.

**Comment by ndimitry** [comment]
And now I also have this stacktrace on startup (while previously was able to work)
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.hierynomus.security.jce.JceSecurityProvider.getDerivationFunction(JceSecurityProvider.java:64)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:302)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:270)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:162)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:142)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:192)
```
