### ISSUE TITLE
Possible bug. Cannot connect a share with default configuration (default provider doesn't allow that)

### ISSUE THREAD

**Issue by ndimitry** [hierynomus/smbj#649]
While connecting I'm getting this exception:
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.hierynomus.security.jce.JceSecurityProvider.getDerivationFunction(JceSecurityProvider.java:64)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:302)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKeys(SMBSessionBuilder.java:270)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:162)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:142)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:192)
        ...
```
The reason is that even though BouncyCastle is on the classpath smbj uses its default provider (when is used not on Android).

**Comment by ndimitry** [comment]
Ok, got it.

**Comment by hierynomus** [comment]
The current master already contains a better exception message, including the right thing to do:

https://github.com/hierynomus/smbj/blob/42ea7ff632f7d48c4fb6a8b9409a696328470579/src/main/java/com/hierynomus/security/jce/JceSecurityProvider.java#L64

**Comment by ndimitry** [comment]
Ok, I guess that is exactly what I'm about to do : )
Thanks!
