### ISSUE TITLE
Unable to open folder on share

### ISSUE THREAD

**Issue by Spookyguy** [hierynomus/smbj#655]
Hi there, i got the following problem while trying to open a subfolder of a folder on a share while i can access the folder itself. First my working code:

`SmbConfig cfg = SmbConfig.builder()
                .withSecurityProvider(new BCSecurityProvider())
                .build();

        SMBClient client = new SMBClient(cfg);

        try (Connection connection = client.connect("myserver.mynet.de")) {
            AuthenticationContext ac = new AuthenticationContext("username", "password".toCharArray(), "DOMAIN");
            Session session = connection.authenticate(ac);

            try (DiskShare share = (DiskShare) session.connectShare("share")) {
                for (FileIdBothDirectoryInformation f : share.list("aaa\\bbb")) {
                    System.out.println("File : " + f.getFileName());
                }
            }
        }`

This works fine and the list shows ccc as a subfolder of bbb.

Now if I change the folder parameter of the list method to

`share.list("aaa\\bbb\\ccc')`

the code throws following exception:

`com.hierynomus.mssmb2.SMBApiException: STATUS_PATH_NOT_COVERED (0xc0000257): Create failed for \\myserver.mynet.de\share\aaa\bbb\ccc
	at com.hierynomus.smbj.share.Share.receive(Share.java:397)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:377)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:159)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:75)
	at com.hierynomus.smbj.share.DiskShare.access$100(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare$2.apply(DiskShare.java:109)
	at com.hierynomus.smbj.share.DiskShare$2.apply(DiskShare.java:105)
	at com.hierynomus.smbj.paths.PathResolver$1.resolve(PathResolver.java:32)
	at com.hierynomus.smbj.paths.SymlinkPathResolver.resolve(SymlinkPathResolver.java:62)
	at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:105)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:65)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:151)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:258)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:231)
	at Test.test(Test.java:52)`

If I add

`.withDfsEnabled(true)`

to the configuration, I get another exception:

`java.lang.NullPointerException
	at com.hierynomus.smbj.share.DiskShare.getDiskEntry(DiskShare.java:133)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:151)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:258)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:231)
	at Test.test(Test.java:52)`

I am working with OpenJDK 11 and version 0.11.1 of SMBJ.

Does anyone have a clue why this is not working? Access to all folders works fine using Microsoft Explorer.

**Comment by hierynomus** [comment]
The PATH_NOT_COVERED status indeed means that dfs should be enabled. The NPE needs some investigation. I'll try to have a look next week

**Comment by hierynomus** [comment]
Do you have some more logging for the NPE? Wonder what code path it went through

**Comment by Spookyguy** [comment]
No, i'm sorry. The above is all i got. Meanwhile i found another solution. [spring-integration-smb](https://github.com/spring-projects/spring-integration-extensions/tree/main/spring-integration-smb) works fine.

**Comment by MKGF** [comment]
I noticed that the error is coming from DiskEntry.java in line 133. 

`if (response.getFileAttributes().contains(FILE_ATTRIBUTE_DIRECTORY)) {`

And I also noticed that when trying to do DiskShare.list(path) I got a list of FileIdBothDirectoryInformation in which, surprisingly, a lot of values were empty when one would expect something in there.

I hope it helps.
