### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by palevi67** [hierynomus/smbj#657]
Is java8 requiered for smbj? I get this exception:

Exception in thread "Thread-11" java.lang.UnsupportedClassVersionError: com/hierynomus/msdtyp/AccessMask : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at ...

$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK Client VM (build 24.95-b01, mixed mode, sharing)

**Comment by hierynomus** [comment]
Yes, Java8 is the minimum supported Java version. Please bear in mind that even Java8 is already officially no longer supported, let alone Java1.7.

**Comment by mctunes** [comment]
Sorry to jump into an old issue. Is Java 11 supported?

**Comment by bangert** [comment]
java8 has (security) support til 2030 - https://endoflife.date/java

https://github.com/hierynomus/smbj/blob/master/build.gradle#L43C1-L43C1
