### ISSUE TITLE
Recurring instances of error "PipeShare has already been closed "

### ISSUE THREAD

**Issue by manutripathi82** [hierynomus/smbj#660]
Hi @hierynomus and @pepijnve 
I have been testing SMBJ for sometime on a single threaded system and it was working fine, but when I deployed it against a heavily loaded multithreaded system, I can see multiple instances of below error 
I checked the code to see any place where the share/session is being disconnected by mistake, but there is none such code area. I initialize the session and connect the share once and allow all the threads to utilize that same instance of share object.

Here's the code for initialization (I am using version 0.11.1)
```
SmbConfig config = SmbConfig.builder().withDfsEnabled(true).withSecurityProvider(new BCSecurityProvider()).build();
client = new SMBClient(config);
connection = client.connect(server);
AuthenticationContext context = new AuthenticationContext("user","pass".toCharArray(), "domain");
session = connection.authenticate(context);
if (session == null || session.getConnection() == null || !session.getConnection().isConnected()) {
	return false;
} else {
        share = (DiskShare) session.connectShare(sharePath);
        if (share != null && share.isConnected()) {
	        log.info("{}", "Connection to share successful");
                return true;
        } else {
	        log.error("{}", "Connection to share failed");
                return false;
        }
}
```
The issue happens on calls like
```
FileAllInformation fileInfo = this.share.getFileInformation(file.getAbsolutePath());
and
List<FileIdBothDirectoryInformation> fileList = this.share.list(fileDirPath);
and
FileStreamInformation stream = share.getFileInformation(file.getAbsolutePath(),FileStreamInformation.class);
```
So there's no definite API which is throwing this error, it is happening randomly to any of the above.

Here's the error stack
```
com.hierynomus.smbj.common.SMBRuntimeException: PipeShare has already been closed
	at com.hierynomus.smbj.share.Share.send(Share.java:382) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.Share.ioctlAsync(Share.java:356) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.Share.ioctlAsync(Share.java:336) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.getReferral(DFSPathResolver.java:437) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.sendDfsReferralRequest(DFSPathResolver.java:427) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.step6(DFSPathResolver.java:261) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.step5(DFSPathResolver.java:222) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.step2(DFSPathResolver.java:141) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.step1(DFSPathResolver.java:124) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.start(DFSPathResolver.java:112) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:100) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:105) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:65) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:151) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:258) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:231) ~[smbj-0.11.1.jar:?]
```

Strangely post receiving if I check for connection status using 
```
private boolean isConnected() {
         return session != null && session.getConnection() != null && session.getConnection().isConnected()
		&& share != null && share.isConnected();
}
```
This always gives TRUE.

Is there any configuration to enable session to support heavy load like max concurrent connection etc.. or this problem is somewhat common in such scenarios ?

**Comment by nddipiazza** [comment]
:+1:
