### ISSUE TITLE
Re-using Connections and/or Sessions

### ISSUE THREAD

**Issue by amcwilliams-r7** [hierynomus/smbj#664]
Hi folks,

I have a few questions about recommended use of the library. I am trying to diagnose an intermittent issue we see where there is a Timeout while waiting for a Connection to authenticate to provide a Session. e.g:

```
T1629982048799 Caused by: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired

T1629982048799 	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:29)

T1629982048799 	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:23)

T1629982048799 	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:43)

T1629982048799 	at com.hierynomus.smbj.connection.Connection.sendAndReceive(Connection.java:305)

T1629982048799 	at com.hierynomus.smbj.connection.Connection.initiateSessionSetup(Connection.java:244)

T1629982048799 	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:181)
```

1. Can multiple Connections between the client and a single server exist at the same time? 
2. Is it recommended to re-use Connections for multiple Sessions?
3. Should the Sessions be closed off before another one is opened or can they exist in parallel on the same Connection?
4. Is it recommended to re-use Sessions for multiple DiskShares?
5. Can a DiskShare be re-used or should it be closed off after a single action e.g. listing files?

Sorry for the many questions but I am trying to get to grips with what the best practice is for using the library.

**Comment by vrr6** [comment]
Hi @amcwilliams-r7 
The default timeout is 60 seconds, either you try to increase or check why its taking more than 60 seconds to receive message.
1. SMB connections are managed with try -- catch block so multiple connection to single server is fine I am using 10 threads using same SMB client for making connection.
2. SMB client already does that.
3. since the connections are opened with try catch block it will be automatically closed.
4. if you have having multiple diskshares from same server then smbj is already managing it.

if you could not find why timeout is happening then paste your code, we will analyse.

Disclaimer: I am not a contributer to SMBJ, but have good experience it its usage.

Thanks,
 R Ramarajan.

**Comment by vrr6** [comment]
do you issue still exist? can you close this if clarification provided is sufficient.
else share your comments.

Thanks,
R Ramarajan.

**Comment by amcwilliams-r7** [comment]
@vrr6 
Thanks for your answers. We are still working on fixing this. 
I think it may be that we are not handling sessions well in our implementation. I will feedback to you when we have some answers.

**Comment by KushalP47** [comment]
@rokkakasu  @amcwilliams-r7
I had a question regarding connection reuse. Is it possible to reuse a single connection for multiple sessions? For example, my use case involves reading thousands of files from an SMB server. Currently, I’m creating a new session—and consequently a new connection—for each file read. This means thousand separate connections are being established. I’m wondering if this overhead (especially the RTT from setting up each connection) could be reduced by reusing a single connection across multiple sessions, at least until it becomes invalid or times out?
