### ISSUE TITLE
JNI error has occurred

### ISSUE THREAD

**Issue by katfood182** [hierynomus/smbj#667]
Getting error below. Does smbj use JNI?

server : Linux 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 04:04:22 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
java : java version "1.8.0_161"

error: Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/hierynomus/msdtyp/AccessMask
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.hierynomus.msdtyp.AccessMask
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by katfood182** [comment]
Error in my code
