### ISSUE TITLE
Different server found for same hostname (com.hierynomus.protocol.transport.TransportException)

### ISSUE THREAD

**Issue by guydavis** [hierynomus/smbj#672]
From [Jenkins Jira 66736](https://issues.jenkins.io/browse/JENKINS-66736), where latest Jenkins ec2-plugin using this smbj library is failing to connect Windows agent instance in AWS EC2.

Agent launches and begins to connect, but then log on master/controller shows error below and eventually Windows agent connection times out as failure.  No Windows agents are thus available to perform build tasks.

```
{{2021-09-26 14:28:22.740+0000 [id=3752]  INFO    c.h.smbj.connection.Connection#close: Closed connection to 10.134.37.223
2021-09-26 14:28:22.740+0000 [id=3901]  INFO    c.h.smbj.transport.PacketReader#run: Thread[Packet Reader for 10.134.37.223,5,main] stopped.
2021-09-26 14:28:22.740+0000 [id=3752]  WARNING h.plugins.ec2.win.WinConnection#pingFailingIfSSHHandShakeError: Failed to verify connectivity to Windows agent
com.hierynomus.protocol.transport.TransportException: Different server found for same hostname '10.134.37.223', disconnecting...
        at com.hierynomus.smbj.connection.SMBProtocolNegotiator.initializeOrValidateServerDetails(SMBProtocolNegotiator.java:232)
        at com.hierynomus.smbj.connection.SMBProtocolNegotiator.negotiateDialect(SMBProtocolNegotiator.java:83)
        at com.hierynomus.smbj.connection.Connection.connect(Connection.java:141)
        at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:96)
        at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:71)
        at hudson.plugins.ec2.win.WinConnection.pingFailingIfSSHHandShakeError(WinConnection.java:136)
        at hudson.plugins.ec2.win.EC2WindowsLauncher.connectToWinRM(EC2WindowsLauncher.java:189)
        at hudson.plugins.ec2.win.EC2WindowsLauncher.launchScript(EC2WindowsLauncher.java:52)
        at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:295)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)}}
```

The issue seems tied to this [method ](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/connection/SMBProtocolNegotiator.java#L220) where the cached server is being validated and coming back as [invalid from here](https://github.com/hierynomus/smbj/blob/5c42b8fe64c371f50a5c56a3c521db6e06292fd7/src/main/java/com/hierynomus/smbj/server/Server.java#L76).  Any tips on how to debug the source of invalid server cached state?

This seems to be regression in 1.64 version of the plugin as nothing in our environment has changed since this was [validated as working with version 1.61](https://issues.jenkins.io/browse/JENKINS-61006?focusedCommentId=410167&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-410167).

While this seems to be a Jenkins issue, I was hoping you could point us in the right direction on how to better use the smbj library.  Thanks in advance!

**Comment by vrr6** [comment]
Hi @guydavis 
Your issue is similar to mine.

https://github.com/hierynomus/smbj/issues/644 you need to catch the exception and remove the server from the server list.
using client.getServerList().unregister(<serverName>)
please close the ticket if my answer satisfies you.

Thanks,
R Ramarajan.
