### ISSUE TITLE
How to list the local files and copy the local files into remote file server

### ISSUE THREAD

**Issue by mariaprabudass** [hierynomus/smbj#675]
I have tried to list the files in the local path using the library smbj, But unable to list & copy the local files to the remote file server. I am getting the error. Shared the Error Log for reference.

My requirement is to change the "jcifs library" to "smbj library", the below sample code has been written for that.

SmbConfig cfg = SmbConfig.builder()
                .withMultiProtocolNegotiate(true)
                .withSigningRequired(false)
                .withDfsEnabled(false)
                .build();
        
            final String Local_SHARE_NAME = "/"; 
            final String LOCAL_PATH = "home//usename//myfolder";
            SMBClient client = new SMBClient(cfg);

            try (Connection connection = client.connect("Remote_Server_IP")) { //x.x.x.x
                AuthenticationContext ac = new AuthenticationContext("user", "pwd".toCharArray(), "Domainname");
                Session session = connection.authenticate(ac);

                try (DiskShare share = (DiskShare) session.connectShare(Local_SHARE_NAME)) {
                    for (FileIdBothDirectoryInformation f : share.list(LOCAL_PATH)) {
                        System.out.println("File : " + f.getFileName());
                    }
                }

            }

**Comment by hierynomus** [comment]
If you take a look at the examples, you will see that share and path names in the SMB world are always separated with `\` and never with `/`.

**Comment by mariaprabudass** [comment]
Share examples of how to connect the local system and read a list of files and copy the files into a remote server.

**Comment by hierynomus** [comment]
https://github.com/hierynomus/smbj/blob/5c42b8fe64c371f50a5c56a3c521db6e06292fd7/src/it/groovy/com/hierynomus/smbj/SMB2FileIntegrationTest.groovy#L117

**Comment by mariaprabudass** [comment]
I have tried using Java. I got a "Connection refused" error to connect the local(127.0.0.1) system. What is wrong with the below code. I don't know why authenticate is required to connect local desktop.

**Code:**
```
 SmbConfig smbConfig = SmbConfig
      .builder()
      .withMultiProtocolNegotiate(true)
      .withDialects(SMB2Dialect.SMB_3_0).withEncryptData(true)
      .withTransportLayerFactory(new DirectTcpTransportFactory<>())
      .withSecurityProvider(new BCSecurityProvider())
      .withSigningRequired(true)
      /*.withEncryptData(true)*/.build();

    SMBClient client = new SMBClient(smbConfig);
    Connection connection = client.connect("127.0.0.1");
    Session session = connection.authenticate(new AuthenticationContext("smbj", "smbj".toCharArray(), null));
            
            try (DiskShare share = (DiskShare) session.connectShare("/")) {
                for (FileIdBothDirectoryInformation f : share.list("home//username//foldername//")) {
                    System.out.println("File : " + f.getFileName());
                }
            }
```

**Error:**
Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:607)
	at com.hierynomus.protocol.commons.socket.ProxySocketFactory.createSocket(ProxySocketFactory.java:87)
	at com.hierynomus.protocol.commons.socket.ProxySocketFactory.createSocket(ProxySocketFactory.java:63)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.connect(DirectTcpTransport.java:88)
	at com.hierynomus.smbj.connection.Connection.connect(Connection.java:139)
	at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:96)
	at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:71)

**Comment by mariaprabudass** [comment]
My requirement is to list the files present in the folder in local desktop and then the listed file should be copied to a remote server.
The above code has been written to list the file in the local desktop. What could be the issue in the above code?
Searched for the example code and didn't find any.
Is authentication required to connect the local directory?if yes what could be the credentials, Is it user credentials?
```
connection = client.connect("127.0.0.1")
session = connection.authenticate(new AuthenticationContext("smbj", "smbj".toCharArray(), null))
```

**Comment by mariaprabudass** [comment]
> https://github.com/hierynomus/smbj/blob/5c42b8fe64c371f50a5c56a3c521db6e06292fd7/src/it/groovy/com/hierynomus/smbj/SMB2FileIntegrationTest.groovy#L117

My requirement is to list the files present in the folder in local desktop and then the listed file should be copied to a remote server.
The code has been written to list the file in the local desktop. What could be the issue in the above code?
Searched for the example code and didn't find any.
Is authentication required to connect the local directory? if yes what could be the credentials, Is it user credentials?

```
connection = client.connect("127.0.0.1")
session = connection.authenticate(new AuthenticationContext("smbj", "smbj".toCharArray(), null))
```

**Comment by hierynomus** [comment]
The exception that you're getting indicates that locally you do not have an SMB server running. I think you should use the regular java.io.File to obtain the file from the local filesystem and then use a `java.io.FileInputStream` to copy the data to a remote SMB File.

**Comment by hierynomus** [comment]
Did this answer your question? If so please close the ticket.

**Comment by kaushikramabhotla** [comment]
Hello @hierynomus ,

I am a beginner, trying to copy some files from a local system to a remote server. I tried sftp, but that wont work in my case. Can you pin point me any code snippet that does this task using smb ?

If this is what you were referring to, I have a few doubts in this snip : 

 ```
   SMBClient client = new SMBClient();

    try (Connection connection = client.connect("SERVERNAME")) {
        AuthenticationContext ac = new AuthenticationContext("USERNAME", "PASSWORD".toCharArray(), "DOMAIN");
        Session session = connection.authenticate(ac);

        // Connect to Share
        try (DiskShare share = (DiskShare) session.connectShare("SHARENAME")) {
            for (FileIdBothDirectoryInformation f : share.list("FOLDER", "*.TXT")) {
                System.out.println("File : " + f.getFileName());
            }
        }
    }
```

what is a SHARENAME and FOLDER in this case ?

**Comment by vrr6** [comment]
Please raise ticket only if there is an issue, if you want to learn already
enough examples provided and lots of solved tickets which contains examples
you can use.
Thanks
R Ramarajan
