### ISSUE TITLE
java.io.EOFException when closing the session

### ISSUE THREAD

**Issue by Dudeplayz** [hierynomus/smbj#700]
I am connecting to a samba server on debian. I have a cache for open sessions to reuse them. When they are not accessed for a specific amount of time (atm. 5min) they are closed. When this happens an exception is thrown. There can be shares open at the moment of access, but if I understood the code correctly these should be closed too.

```console
2022-03-09 13:21:09 [ForkJoinPool.commonPool-worker-5] INFO  Session - Logging off session 3443769887 from host files.xxx
2022-03-09 13:21:42 [Packet Reader for files.xxx] INFO  DirectTcpPacketReader - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:72) ~[smbj-0.11.5.jar:?]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59) ~[smbj-0.11.5.jar:?]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48) ~[smbj-0.11.5.jar:?]
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70) ~[smbj-0.11.5.jar:?]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48) [smbj-0.11.5.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.EOFException: EOF while reading packet
	... 6 more
2022-03-09 13:21:42 [Packet Reader for files.xxx] INFO  Connection - Closed connection to files.xxx
```

**Comment by nielsm5** [comment]
We're encountering the same problem. It's not blocking but looks sloppy. It seems that the PacketReader is unaware of the shutdown, and throws an exception (causing it to shutdown).

```
10:12:24,150 INFO  SMBSessionBuilder.establish():120[] Successfully authenticated frankframework on localhost, session is 281474976710657
10:12:24,150 INFO  Session.connectTree():120[] Connecting to \\localhost\home on session 281474976710657
...
...
...
10:12:24,202 INFO  Session.logoff():233[] Logging off session 281474976710657 from host localhost
10:12:24,202 INFO  SMBClient.close():123[] Going to close all remaining connections
10:12:24,202 INFO  PacketReader.run():53[] PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:72) ~[smbj-0.12.1.jar:0.12.1]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59) ~[smbj-0.12.1.jar:0.12.1]
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48) ~[smbj-0.12.1.jar:0.12.1]
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:70) ~[smbj-0.12.1.jar:0.12.1]
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:48) [smbj-0.12.1.jar:0.12.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.io.EOFException: EOF while reading packet
	... 6 more
10:12:41,272 INFO  Connection.close():186[] Closed connection to localhost
```
