### ISSUE TITLE
File and Directory Rename does not work on a DFS Share

### ISSUE THREAD

**Issue by vjorge** [hierynomus/smbj#709]
Hi,
I am using **SMBJ  0.11.5** and smbj dialects {**SMB2Dialect.SMB_3_0 ,SMB2Dialect.SMB_3_0_2,SMB2Dialect.SMB_3_1_1**}

I have **DFS** enabled , when creating a file or directory, it works, the DFSPathResolver does the **work** and the File and Folder are created **successfuly**.

But when trying to **rename** a File or Directory it throws the following error:

```
Exception in thread "main" com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for \\dfsServer\ShareLink\EMCServerShare\FolderOrFileToRename
	at com.hierynomus.smbj.share.Share.receive(Share.java:380)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:359)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:156)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:75)
	at com.hierynomus.smbj.share.DiskShare$2.apply(DiskShare.java:109)
	at com.hierynomus.smbj.share.DiskShare$2.apply(DiskShare.java:105)
	at com.hierynomus.smbj.paths.DFSPathResolver.step12(DFSPathResolver.java:389)
	at com.hierynomus.smbj.paths.DFSPathResolver.step6(DFSPathResolver.java:282)
	at com.hierynomus.smbj.paths.DFSPathResolver.step5(DFSPathResolver.java:231)
	at com.hierynomus.smbj.paths.DFSPathResolver.step2(DFSPathResolver.java:150)
	at com.hierynomus.smbj.paths.DFSPathResolver.step1(DFSPathResolver.java:133)
	at com.hierynomus.smbj.paths.DFSPathResolver.start(DFSPathResolver.java:121)
	at com.hierynomus.smbj.paths.DFSPathResolver.resolve(DFSPathResolver.java:109)
	at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:105)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:65)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:151)
	at SmbDirectory.renameTo(SmbDirectory.java:177)
```
If I connect directly to the EMC Server and Share  the rename works. From what I understand the rename function is not using the DFSPathResolver properly.

Any way of solving this issue without manually  performing a DFS resolve?
Many thanks

**Comment by hierynomus** [comment]
What is the target you're renaming to? Will it reside on the same DFS? Or on a different path on another DFS (or the original target?)

**Comment by hierynomus** [comment]
Can you provide some sample code? I don't see the `DiskEntry#rename` function in the stackstrace?

**Comment by vjorge** [comment]
Hi hierynomus,
Many thanks for you help.
The code works without problems, it was my mistake, the error above was created because I was defined the wrong AccessMask for both file and folder, and by mistake pasted the wrong stack in this issue.
Please delete this issue, it was not even a real problem but a stupid coding error.
My apologies and many thanks for the great library.
