### ISSUE TITLE
ClassCastException in TargetInfo.java (ntlm)

### ISSUE THREAD

**Issue by bubbleguuum** [hierynomus/smbj#712]
I've seen this crash report form a user. This is probably fairly rare and specific to a SMB server or setup:

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
at com.hierynomus.ntlm.messages.TargetInfo.writeTo(TargetInfo.java:88)
at com.hierynomus.ntlm.functions.NtlmFunctions.getNTLMv2ClientChallenge(NtlmFunctions.java:196)
at com.hierynomus.smbj.auth.NtlmAuthenticator.authenticate(NtlmAuthenticator.java:103)
at com.hierynomus.smbj.connection.SMBSessionBuilder.processAuthenticationToken(SMBSessionBuilder.java:178)
at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:141)
at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
```

**Comment by hierynomus** [comment]
Thanks for reporting, I've updated the cast to be correct.

**Comment by l00251692** [comment]
I also met this exception，is there any plan to update a release version to cover this issue ? Seeing the latest version is still on v0.11.5, Thanks

**Comment by rongway777** [comment]
Also, is there any plan to release a new version soon?
