### ISSUE TITLE
Null Pointer when opening DFS link

### ISSUE THREAD

**Issue by abhisheksardana** [hierynomus/smbj#717]
Hello @hierynomus,

We have observed NPE while opening DFS link.

Caused by: java.lang.NullPointerException
    at com.hierynomus.smbj.share.DiskShare.getDiskEntry(DiskShare.java:133)
    at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
    at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:151)
    at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:258)
    at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:231)

We have observed this behavior for some of the DFS paths only. I tried to debug the issue and below are some of the observations.

- Getting NPE for DFS path //somehost/dfsshare/dfslink but working fine for //SOMEHOST/dfsshare/dfslink (only difference is the case). dfslink point to //server1/folder

- When the library tries to resolve the share  //somehost/dfsshare/dfslink (getting NPE for this path), the actual path and the target path are the same hence it does not reroute and nested session has not been created. The final path remains //somehost/dfsshare/dfslink after the resolution for which the "fileAttributes" are null, hence getting NPE.

- When the library tries to resolve the share  //SOMEHOST/dfsshare/dfslink (working fine), the actual path and the target path are different because of the case only so it reroutes and create a nested session. When a nested session is created a new dfs referral request has been sent as referral cache is null for the nested session. This time it resolves the path properly and after the resolution the final path is //server1/folder and for that "fileattributes" are not null and request is successful.

`private SMB2CreateResponseContext resolveAndCreateFile(final SmbPath path,
            final SMB2ImpersonationLevel impersonationLevel, final Set<AccessMask> accessMask,
            final Set<FileAttributes> fileAttributes, final Set<SMB2ShareAccess> shareAccess,
            final SMB2CreateDisposition createDisposition, final Set<SMB2CreateOptions> createOptions) {
        try {
            SMB2CreateResponseContext target = resolver.resolve(session, path, new PathResolver.ResolveAction<SMB2CreateResponseContext>(){
                @Override
                public SMB2CreateResponseContext apply(SmbPath target) {
                    DiskShare resolvedShare = rerouteIfNeeded(path, target);
                    return resolvedShare.createFileAndResolve(target, impersonationLevel, accessMask, fileAttributes,
                            shareAccess, createDisposition, createOptions);                }
            });

            return target;
        } catch (PathResolveException pre) {
            throw new SMBApiException(pre.getStatus().getValue(), SMB2MessageCommandCode.SMB2_CREATE,
                    "Cannot resolve path " + path, pre);
        }
    }`

We are not sure of this behavior. Any idea about it?

**Comment by abhisheksardana** [comment]
Yes, its seems similar to #697. Can you please run by changing the case of the hostname. If you are getting the issue with hostname in lowercase then try to run it with hostname in upper case or vice versa. For us that's the reason and this is why we are not getting this error for every DFS share.

**Comment by abhisheksardana** [comment]
Hi @hierynomus,

We have debug it further and below is our analysis.

When the library tries to resolve the dfs link path e.g. //somehost/dfsshare/dfslink it makes an IO request which fails with STATUS_PATH_NOT_COVERED. As per the documentation **the client
MUST look up the path used for the I/O operation i.e //somehost/dfsshare/dfslink in ReferralCache** but instead it is looking for dfs path prefix i.e. //somehost/dfsshare in the referral cache. Due to cache hit library does not issue a new DFS link
referral request and the final path remains //host/dfs/link which should not be the case ideally.

Ideally it should look up the path used for the I/O operation i.e //somehost/dfsshare/dfslink in ReferralCache which will be a cache miss and in that case library should issue a dfs link referral request, process the response and update the referral cache with the correct entry  //somehost/dfsshare/dfslink -> //server1/folder

```
public <T> T resolve(Session session, SMB2Packet responsePacket, final SmbPath smbPath,
            final ResolveAction<T> action) throws PathResolveException {
        // If the server does not support DFS, short circuit this path resolution.
        if (!session.getConnection().getConnectionContext().supportsDFS()) {
            return wrapped.resolve(session, responsePacket, smbPath, action);
        }

        if (smbPath.getPath() != null && responsePacket.getHeader().getStatusCode() == NtStatus.STATUS_PATH_NOT_COVERED.getValue()) {
            logger.info("DFS Share {} does not cover {}, resolve through DFS", smbPath.getShareName(), smbPath);
            return start(session, smbPath, new ResolveAction<T>() {
                @Override
                public T apply(SmbPath target) {
                    logger.info("DFS resolved {} -> {}", smbPath, target);
                    return action.apply(target);
                }
            });
        } else if (smbPath.getPath() == null && NtStatus.isError(responsePacket.getHeader().getStatusCode())) {
            logger.info("Attempting to resolve {} through DFS", smbPath);
            return start(session, smbPath, action);
        }
        return wrapped.resolve(session, responsePacket, smbPath, action);
    }
```

[MS-DFSC] section 3.1.5.1

> ### 3.1.5.1 I/O Operation to Target Fails with STATUS_PATH_NOT_COVERED
> When an I/O operation that is issued to a link target fails with STATUS_PATH_NOT_COVERED
> (0xC0000257), the client MUST fail the original I/O request.
>
> When an I/O operation issued to a DFS root target server in step 8 of section 3.1.4.1 fails with
> STATUS_PATH_NOT_COVERED (0xC0000257), it indicates that the portion of the DFS namespace
> accessed by the client is not contained in the DFS root target server.
>
> **To identify the DFS link targets that contain the required portion of the DFS namespace, the client
> MUST look up the path used for the I/O operation in ReferralCache. On a cache hit, the resulting
> ReferralCache entry MUST be used in further processing.**
>
> Otherwise, the client MUST obtain the file attributes of the DFS link as specified in [MS-CIFS] section
> 3.2.4.12 or [MS-SMB2] section 3.2.4.8 based on the protocol transport.
>
> If the file attributes include FILE_ATTRIBUTE_REPARSE_POINT, the client MUST issue a DFS link
> referral request, as specified in section 3.1.4.2, providing as parameters "LINK", the DFS root target
> server specified by the TargetHint of the ReferralCache entry corresponding to the DFS namespace,
> UserCredentials, MaxOutputSize, and Path. The Path parameter MUST be set to the path in the
> I/O operation issued to the DFS root target in step 8 of section 3.1.4.1. The client MUST process the
> DFS referral response as specified in section 3.1.5.4.3, which will update the ReferralCache.<9> The
> resulting ReferralCache entry, if any, MUST be used in further processing.

Any inputs will be really helpful.

**Comment by manish-pai** [comment]
When referring to the [MS-DFSC], one thing that is not clear is when do we resolve the link if the referral cache has an entry for DFS_ROOT. 

For example, in this case where the path is //host/dfs/link, and referral cache already has an entry for DFS_ROOT ie //host/dfs, then in step 8, the I/O operation should fail with STATUS_PATH_NOT_COVERED. Now since  ReferralCache entry indicates root targets, we need to go to 3.5.1.1

As per documentation of 3.1.5.1
---<snippet>
3.1.5.1 I/O Operation to Target Fails with STATUS_PATH_NOT_COVERED
When an I/O operation that is issued to a link target fails with STATUS_PATH_NOT_COVERED
(0xC0000257), the client MUST fail the original I/O request.
When an I/O operation issued to a DFS root target server in step 8 of section 3.1.4.1 fails with
STATUS_PATH_NOT_COVERED (0xC0000257), it indicates that the portion of the DFS namespace
accessed by the client is not contained in the DFS root target server.
_To identify the DFS link targets that contain the required portion of the DFS namespace, the client
MUST look up the path used for the I/O operation in ReferralCache._ On a cache hit, the resulting
ReferralCache entry MUST be used in further processing.
Otherwise, the client MUST obtain the file attributes of the DFS link as specified in [MS-CIFS] section
3.2.4.12 or [MS-SMB2] section 3.2.4.8 based on the protocol transport.
If the file attributes include FILE_ATTRIBUTE_REPARSE_POINT, the client MUST issue a DFS link
referral request, as specified in section 3.1.4.2
---<snippet>
What is not clear here is that we will hit the cache every time as there is an entry for DFS_ROOT. I guess, here cache hit check should be for the entire path and not partial path.

**Comment by turcsanyip** [comment]
@hierynomus Any chance to fix this?

**Comment by l-k-test** [comment]
I can confirm analysis of @turcsanyip .

This is a fragment from the logs (\\<host>\<share>\<subdir> is mentioned for the very first time):

`

    637  [main] INFO  com.hierynomus.smbj.paths.DFSPathResolver  - Starting DFS resolution for \\<host>\<share>\<subdir>

     637  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[1]: ResolveState{path=DFSPath{[<host>, <share>, <subdir>]}, resolvedDomainEntry=false, isDFSPath=false, hostName='null'}

     637  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[2]: ResolveState{path=DFSPath{[<host>, <share>, <subdir>]}, resolvedDomainEntry=false, isDFSPath=false, hostName='null'}

     637  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[2]: cache lookup for DFSPath{[<host>, <share>, <subdir>]} returned \<host>\<share->DFSPath{[<host>, <share>]}(ROOT), [TargetSetEntry[DFSPath{[<host2>, <share2>]},targetSetBoundary=false]]

     637  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[3]: ...

     637  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[8]: ...
`

The fourth line is where the problem is.

Sometimes execution continues like this, and the problem is **not** reproduced:

`

    641  [main] INFO  com.hierynomus.smbj.paths.DFSPathResolver  - DFS Share <share> does not cover \\<host>\<share>\<subdir>, resolve through DFS

     642  [main] INFO  com.hierynomus.smbj.paths.DFSPathResolver  - Starting DFS resolution for \\<host>\<share>\<subdir>

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[1]: ResolveState{path=DFSPath{[<host>, <share>, <subdir>]}, resolvedDomainEntry=false, isDFSPath=false, hostName='null'}

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[2]: ResolveState{path=DFSPath{[<host>, <share>, <subdir>]}, resolvedDomainEntry=false, isDFSPath=false, hostName='null'}

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[2]: cache lookup for DFSPath{[<host>, <share>, <subdir>]} returned null

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[5]: ...

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[6]: ...
`

The fifth line is what should have been the case in the fragment 1 above.
Of course a separate question is: why is it null now!?

Sometimes execution continues like this, and the problem **is** reproduced:

`

     641  [main] INFO  com.hierynomus.smbj.paths.DFSPathResolver  - DFS Share <share> does not cover \\<host>\<share>\<subdir>, resolve through DFS

     642  [main] INFO  com.hierynomus.smbj.paths.DFSPathResolver  - Starting DFS resolution for \\<host>\<share>\<subdir>

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[1]: ResolveState{path=DFSPath{[<host>, <share>, <subdir>]}, resolvedDomainEntry=false, isDFSPath=false, hostName='null'}

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[2]: ResolveState{path=DFSPath{[<host>, <share>, <subdir>]}, resolvedDomainEntry=false, isDFSPath=false, hostName='null'}

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[2]: cache lookup for DFSPath{[<host>, <share>, <subdir>]} returned \<host>\<share->DFSPath{[<host>, <share>]}(ROOT), [TargetSetEntry[DFSPath{[<host2>, <share2>]},targetSetBoundary=false]]

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[3]: ...

     642  [main] TRACE com.hierynomus.smbj.paths.DFSPathResolver  - DFS[8]: ...
`

Again, see the fifth line.


Just adding return null; between lines 229 and 230 in the code snipped posted by @turcsanyip above fixed the problem for me.

**Comment by BastienPoP** [comment]
I ran into the same issue when resolving a DFS path inside a folder that itself came from a DFS resolution. Without the patch, navigating directories would almost always throw a NullPointerException. After forking the library and applying the patch from this thread, the NPE is gone and DFS resolution works correctly even with nested DFS paths.
