### ISSUE TITLE
ResolveAction<T> in DFSPathResolver

### ISSUE THREAD

**Issue by kadirchisty** [hierynomus/smbj#724]
I am trying to call resolve method of DFSPathResolver but getting nullpointer. Could you pls let me know how to pass ResolveAction<T> argument here?

SmbPath resolved = new DFSPathResolver(PathResolver.LOCAL).resolve(ds.getTreeConnect().getSession(), responsePacket, smbPath, null);

Error:
java.lang.NullPointerException: null
	at com.hierynomus.smbj.paths.DFSPathResolver$2.apply(DFSPathResolver.java:83) ~[smbj-0.11.1.jar:?]

**Comment by hierynomus** [comment]
There should be no need to call the method externally normally. If you enable DFS it should be transparent.

**Comment by kadirchisty** [comment]
Hi,
I have enabled DFS in smbconfig. But library is failing to rename the files in DFS paths with below error message.

com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_PATH_NOT_FOUND (0xc000003a): SetInfo failed for SMB2FileId{persistentHandle=39 f9 b4 0c 5c 00 00 02}
	at com.hierynomus.smbj.share.Share.receive(Share.java:397) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:377) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.Share.setInfo(Share.java:203) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskShare.setFileInformation(DiskShare.java:330) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskEntry.setFileInformation(DiskEntry.java:85) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskEntry.rename(DiskEntry.java:127) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskEntry.rename(DiskEntry.java:122) ~[smbj-0.11.1.jar:?]
	at com.hierynomus.smbj.share.DiskEntry.rename(DiskEntry.java:118) ~[smbj-0.11.1.jar:?]

**Comment by JozefDropco** [comment]
Hi @hierynomus , 
I found the reason why its not working as you said DFS should be transparent unfortunately it isnt in case of rename. When SMBJ is sending rename to server the srcFile is already resolved to actual server where the file exists, unfortunately the target file name has to be resolved too but its not. It simply passed to  FileRenameInformation and then encoded to buffer in FileInformationFactory without any touch of DFSPathResolver. Therefore this issue is popping up. Is it possible to resolve the targetFileName in elegant way?

**Comment by kadirchisty** [comment]
@JozefDropco 

You got it right. Rename is working fine. Thanks!!
