### ISSUE TITLE
SMBApiException: STATUS_CANNOT_DELETE (0xc0000121): SetInfo failed for SMB2FileId{persistentHandle=ee 46 00 00 48 00 00 00}

### ISSUE THREAD

**Issue by vrr6** [hierynomus/smbj#726]
Hi @hierynomus ,

when the file in share location is a read only file we are unable to delete the file after processing it 
in command prompt we can delete the file by issuing del /f Test.txt_  but we are not having any force option or any other way to delete a read only file even though we have full permission on the folder

com.hierynomus.mssmb2.SMBApiException: STATUS_CANNOT_DELETE (0xc0000121): SetInfo failed for SMB2FileId{persistentHandle=ee 46 00 00 48 00 00 00}
	at com.hierynomus.smbj.share.Share.receive(Share.java:380)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:359)
	at com.hierynomus.smbj.share.Share.setInfo(Share.java:191)
	at com.hierynomus.smbj.share.DiskShare.setFileInformation(DiskShare.java:330)
	at com.hierynomus.smbj.share.DiskShare.deleteOnClose(DiskShare.java:437)
	at com.hierynomus.smbj.share.DiskEntry.deleteOnClose(DiskEntry.java:231)
	at com.hierynomus.smbj.share.DiskShare.rm(DiskShare.java:427)

**Comment by vrr6** [comment]
kindly help us to get the solution.

Thanks,
R Ramarajan.

**Comment by vrr6** [comment]
Hi @hierynomus  issue more similar to https://github.com/hierynomus/smbj/issues/234 and hence closing it.
