### ISSUE TITLE
Can't access SMB share using kerberos ticket

### ISSUE THREAD

**Issue by Tomiwa-Ot** [hierynomus/smbj#733]
I'm trying to access an smb share in an active directory environment (windows server 2019) using the kerberos ticket gotten after authentication using the Krb5LoginModule. What's the issue or is there another way of going about this?

```java
import java.io.IOException;
import java.net.MalformedURLException;
import java.security.PrivilegedActionException;
import java.security.PrivilegedExceptionAction;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.logging.Logger;

import javax.security.auth.Subject;
import javax.security.auth.callback.Callback;
import javax.security.auth.callback.CallbackHandler;
import javax.security.auth.callback.NameCallback;
import javax.security.auth.callback.PasswordCallback;
import javax.security.auth.callback.UnsupportedCallbackException;
import javax.security.auth.kerberos.KerberosPrincipal;
import javax.security.auth.login.AppConfigurationEntry;
import javax.security.auth.login.Configuration;
import javax.security.auth.login.LoginContext;
import javax.security.auth.login.LoginException;

import org.ietf.jgss.GSSCredential;
import org.ietf.jgss.GSSException;
import org.ietf.jgss.GSSManager;
import org.ietf.jgss.GSSName;
import org.ietf.jgss.Oid;

import com.hierynomus.smbj.SMBClient;
import com.hierynomus.smbj.auth.GSSAuthenticationContext;
import com.hierynomus.smbj.connection.Connection;
import com.hierynomus.smbj.session.Session;
import com.hierynomus.smbj.share.DiskShare;
import com.hierynomus.smbj.share.Share;
import com.sun.security.auth.module.Krb5LoginModule;

public class SMBKerberos {
	
	private static String NAME = "Administrator";

    private static String PWD = "";

    private static String KDC = "";
    
    private static String REALM = "";

	public static void main(String[] args) throws LoginException, GSSException, PrivilegedActionException, IOException  {
		
		System.setProperty("java.security.krb5.kdc", KDC);
	    System.setProperty("java.security.krb5.realm", REALM);
	    HashMap<String, String> loginParams = new HashMap<String, String>();
	    loginParams.put("principal", NAME);
	    LoginContext loginContext = new LoginContext(NAME, null, 
				new UsernameAndPasswordCallbackHandler(NAME, PWD),
				new KerberosLoginConfiguration(loginParams));
	    loginContext.login();
	    Subject subject = loginContext.getSubject();
	    KerberosPrincipal krbPrincipal = subject.getPrincipals(KerberosPrincipal.class).iterator().next();

	    Oid spnego = new Oid("1.3.6.1.5.5.2");
	    Oid kerberos5 = new Oid("1.2.840.113554.1.2.2");

	    final GSSManager manager = GSSManager.getInstance();


	    final GSSName name = manager.createName(krbPrincipal.toString(), GSSName.NT_USER_NAME);
	    Set<Oid> mechs = new HashSet<Oid>(Arrays.asList(manager.getMechsForName(name.getStringNameType())));
	    final Oid mech;
	    if (mechs.contains(kerberos5)) {
	        mech = kerberos5;
	    } else if (mechs.contains(spnego)) {
	        mech = spnego;
	    } else {
	        throw new IllegalArgumentException("No mechanism found");
	    }

	    GSSCredential creds = Subject.doAs(subject, new PrivilegedExceptionAction<GSSCredential>() {
	        public GSSCredential run() throws GSSException {
	            return manager.createCredential(name, GSSCredential.DEFAULT_LIFETIME, mech, GSSCredential.INITIATE_ONLY);
	        }
	    });



	    GSSAuthenticationContext auth = new GSSAuthenticationContext(
	        krbPrincipal.getName(),
	        krbPrincipal.getRealm(),
	        subject,
	        creds
	    );

	    SMBClient client = new SMBClient();
	    Connection connection = client.connect(REALM);
	    Session session = connection.authenticate(auth);
	    DiskShare share = (DiskShare) session.connectShare("samba");
	    System.out.println(share.toString());


	}
	
	public static void login(Subject subject) throws LoginException {
		System.setProperty("java.security.krb5.kdc", KDC);
        System.setProperty("java.security.krb5.realm", REALM);
        
        Map state = new HashMap();
        state.put("javax.security.auth.login.name", NAME);
        state.put("javax.security.auth.login.password", PWD.toCharArray());
        
        Map option = new HashMap();
        option.put("debug", "false");
        option.put("tryFirstPass", "true");
        option.put("useTicketCache", "true");
        option.put("doNotPrompt", "false");
        option.put("storePass", "true");
        option.put("useKeyTab", "true");
	    option.put("keyTab", "mykeytab");

        Krb5LoginModule loginModule = new Krb5LoginModule();
        loginModule.initialize(subject, null, state, option);
        
        if(loginModule.login()){
            loginModule.commit();
        }
        
	}

}

class CustomLoginConfiguration extends Configuration {

    //define a map of params you wish to pass and fill them up
    Map<String, String> params = new HashMap<String, String>();
    //the map contains entries similar to one you have in login.conf
    private AppConfigurationEntry configEntry = new AppConfigurationEntry(
        "com.sun.security.auth.module.Krb5LoginModule",
        AppConfigurationEntry.LoginModuleControlFlag.REQUIRED,
        params
    );

    public CustomLoginConfiguration(Map<String, String> params) {
        this.params.putAll(params);
    }

    @Override
    public AppConfigurationEntry[] getAppConfigurationEntry(String name) {
        return new AppConfigurationEntry[]{configEntry};
    }
}

class UsernameAndPasswordCallbackHandler implements CallbackHandler {

	private final String user;
	private final String password;

	public UsernameAndPasswordCallbackHandler(String user, String password) {
		this.user = user;
		this.password = password;
	}

	public void handle(Callback[] callbacks) throws IOException, UnsupportedCallbackException {
		for (Callback callback : callbacks) {
			if (callback instanceof NameCallback) {
				NameCallback nc = (NameCallback) callback;
				nc.setName(user);
			} else if (callback instanceof PasswordCallback) {
				PasswordCallback pc = (PasswordCallback) callback;
				pc.setPassword(password.toCharArray());
			} else {
				throw new UnsupportedCallbackException(callback, "Unknown Callback");
			}
		}
	}
}

class KerberosLoginConfiguration extends Configuration{

//	private final static Logger logger = LogUtil.getLogger(KerberosLoginConfiguration.class);
	//define a map of params you wish to pass and fill them up
	private Map<String, String> params = new HashMap<String, String>();
	
	private String ibmJavaKrb5LoginModuleClass = "com.ibm.security.auth.module.Krb5LoginModule";
	private String oracleJavaKrb5LoginModuleClass = "com.sun.security.auth.module.Krb5LoginModule";
	
	public KerberosLoginConfiguration(Map<String, String> params) {
		this.params.putAll(params);
	}

	@Override
	public AppConfigurationEntry[] getAppConfigurationEntry(String name) {
		AppConfigurationEntry configEntry = null;
		configEntry = new AppConfigurationEntry(oracleJavaKrb5LoginModuleClass,
				AppConfigurationEntry.LoginModuleControlFlag.REQUIRED, params);
		return new AppConfigurationEntry[]{configEntry};
	}
}
```

```
// Exception in thread "main" com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.security.PrivilegedActionException: com.hierynomus.protocol.transport.TransportException: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7)))
// 	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:114)
// 	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
// 	at SMBKerberos.main(SMBKerberos.java:89)
// Caused by: com.hierynomus.protocol.transport.TransportException: java.security.PrivilegedActionException: com.hierynomus.protocol.transport.TransportException: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7)))
// 	at com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticate(SpnegoAuthenticator.java:72)
// 	at com.hierynomus.smbj.connection.SMBSessionBuilder.processAuthenticationToken(SMBSessionBuilder.java:178)
// 	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:107)
// 	... 2 more
// Caused by: java.security.PrivilegedActionException: com.hierynomus.protocol.transport.TransportException: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7)))
// 	at java.security.AccessController.doPrivileged(Native Method)
// 	at javax.security.auth.Subject.doAs(Unknown Source)
// 	at com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticate(SpnegoAuthenticator.java:66)
// 	... 4 more
// Caused by: com.hierynomus.protocol.transport.TransportException: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7)))
// 	at com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession(SpnegoAuthenticator.java:108)
// 	at com.hierynomus.smbj.auth.SpnegoAuthenticator.access$000(SpnegoAuthenticator.java:42)
// 	at com.hierynomus.smbj.auth.SpnegoAuthenticator$1.run(SpnegoAuthenticator.java:68)
// 	at com.hierynomus.smbj.auth.SpnegoAuthenticator$1.run(SpnegoAuthenticator.java:66)
// 	... 7 more
// Caused by: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7)))
// 	at sun.security.jgss.spnego.SpNegoContext.initSecContext(Unknown Source)
// 	at sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
// 	at sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
// 	at com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession(SpnegoAuthenticator.java:92)
// 	... 10 more
// Caused by: GSSException: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7))
// 	at sun.security.jgss.krb5.Krb5Context.initSecContext(Unknown Source)
// 	at sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
// 	at sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
// 	at sun.security.jgss.spnego.SpNegoContext.GSS_initSecContext(Unknown Source)
// 	... 14 more
// Caused by: KrbException: Server not found in Kerberos database (7)
// 	at sun.security.krb5.KrbTgsRep.<init>(Unknown Source)
// 	at sun.security.krb5.KrbTgsReq.getReply(Unknown Source)
// 	at sun.security.krb5.KrbTgsReq.sendAndGetCreds(Unknown Source)
// 	at sun.security.krb5.internal.CredentialsUtil.serviceCredsSingle(Unknown Source)
// 	at sun.security.krb5.internal.CredentialsUtil.serviceCreds(Unknown Source)
// 	at sun.security.krb5.internal.CredentialsUtil.serviceCreds(Unknown Source)
// 	at sun.security.krb5.internal.CredentialsUtil.acquireServiceCreds(Unknown Source)
// 	at sun.security.krb5.Credentials.acquireServiceCreds(Unknown Source)
// 	... 18 more
// Caused by: KrbException: Identifier doesn't match expected value (906)
// 	at sun.security.krb5.internal.KDCRep.init(Unknown Source)
// 	at sun.security.krb5.internal.TGSRep.init(Unknown Source)
// 	at sun.security.krb5.internal.TGSRep.<init>(Unknown Source)
// 	... 26 more
```

**Comment by cliviu** [comment]
Hi,  can anybody share some advice for using Kerberos with ticketCache under Windows? Thank you!
