### ISSUE TITLE
STATUS_LOGON_FAILURE (0xc000006d): Authentication failed for 'amber' using com.hierynomus.smbj.auth.NtlmAuthenticator@8e0c3e4

### ISSUE THREAD

**Issue by XuQK** [hierynomus/smbj#735]
I searched for relevant information on the Internet, and looked at all related issues, and none of them matched my situation.

This SMB service is enabled on my Mac computer, and the settings are as follows:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2867860/188865048-b6351d59-bde3-4c69-89ad-55aa3a2a9a36.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/2867860/188865072-ed5ad130-77b4-4765-959f-ef53c349beac.png">

I can use mature SMB tools to connect to this service, but I can't use smbj. My connection code is as follows:
```kotlin
val client = SMBClient()
val connection = client.connect("10.0.100.49", 445)
val ac = AuthenticationContext("amber", "password".toCharArray(), null)
val session = connection.authenticate(ac)
```
The third parameter of AuthenticationContext I have tried "DOMAIN", null, empty string, none of them work.

The log is as follows:
```
2022-09-07 19:18:10.381 1679-3360/ W/System.err: [DefaultDispatcher-worker-3] INFO com.hierynomus.smbj.connection.PacketEncryptor - Initialized PacketEncryptor with Cipher << AES_128_CCM >>
2022-09-07 19:18:10.383 1679-3360/ W/System.err: [DefaultDispatcher-worker-3] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: 10.0.100.49
2022-09-07 19:18:10.685 1679-1679/ E/AndroidRuntime: FATAL EXCEPTION: main
Process: , PID: 1679
com.hierynomus.mssmb2.SMBApiException: STATUS_LOGON_FAILURE (0xc000006d): Authentication failed for 'amber' using com.hierynomus.smbj.auth.NtlmAuthenticator@ff6986
at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:144)
at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:142)
at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
at .utils.net.smb.TfSmbClient.connect-IoAF18A(TfSmbClient.kt:35)
at .ui.home.network.smb.SmbConnectViewModel$connectToSmb$2.invokeSuspend(SmbConnectViewModel.kt:137)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@89149e0, Dispatchers.Main.immediate]
2022-09-07 19:18:10.744 1679-1679/ I/Process: Sending signal. PID: 1679 SIG: 9
```

I've been trying all day, but with little success, frustrated.

**Comment by XuQK** [comment]
All I can do is try various SMBConfig combinations, I also tried what you said, but it didn't work.
I just turned to an issue that I missed before, it seems to be related to my problem, I noticed that you didn't comment on the solution, why?
I'll try the solution in this issue tomorrow (about 14 hours later) and see if it helps.

**Comment by XuQK** [comment]
The #698 not work for me. sad.

**Comment by XuQK** [comment]
0.10.0 work for me，but https://github.com/hierynomus/smbj/issues/698#issuecomment-1072309114 step3 not work for me.

**Comment by XuQK** [comment]
This pcap file, may help you.
[DumpFile01.pcap.zip](https://github.com/hierynomus/smbj/files/9523407/DumpFile01.pcap.zip)

**Comment by XuQK** [comment]
I tried some commit, `3dfc55362bb1f3216ba83e5467ecc73f279d2566` is work fine, but in next `0b6a5236b9c78c35151f1f3815931d68ec4bff86`, I got the `STATUS_LOGON_FAILURE (0xc000006d)` fail.

**Comment by olivierrivard** [comment]
I had the same issue and rolling back to version 0.10.0 fixed the issue.

**Comment by hierynomus** [comment]
This is now fixed on master.
