### ISSUE TITLE
how to move(not copy) a file from one directory to another another directory inside same remote windows machine

### ISSUE THREAD

**Issue by satya081** [hierynomus/smbj#741]
I have a requirement where I need to transfer/move the file from one directory to another directory with in same remote windows machine.

could you please share me the code to do that?

**Comment by satya081** [comment]
any update on this?

**Comment by NilsHult** [comment]
Use rename. 

```
InetAddress address = InetAddress.getByName("my.server.org");
AuthenticationContext auth = new AuthenticationContext("NilsHult", "secret".toCharArray(), "MYDOMAIN");
SmbConfig config = SmbConfig.builder().withEncryptData(true).build();

try (SMBClient client = new SMBClient(config)) {
	try (Connection connection = client.connect(address.getHostAddress())) {
		try (Session session = connection.authenticate(auth)) {

			try (DiskShare share = (DiskShare) session.connectShare("my-share")) {
				try (File file = share.openFile("/temp-folder/test.txt",
						EnumSet.of(AccessMask.DELETE, AccessMask.GENERIC_WRITE), (Set<FileAttributes>) null,
						SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_CREATE,
						(Set<SMB2CreateOptions>) null)) {

					try (OutputStream out = file.getOutputStream()) {
						out.write(((String) "test").getBytes("utf-8"));
						out.flush();
					}
							
					file.rename("/target-folder/test.txt");
				}
			}
		}
	}
}
```

**Comment by satya081** [comment]
@NilsHult we have to write same content as present in the file but you have mentioned below
try (OutputStream out = file.getOutputStream()) {
						**out.write(((String) "test").getBytes("utf-8"));**
						out.flush();
					}

**Comment by satya081** [comment]
@NilsHult i was trying to implement your solution i am getting below error

com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_NAME_INVALID (0xc0000033): SetInfo failed for SMB2FileId{persistentHandle=31 88 00 00 2f 00 00 00}
	at com.hierynomus.smbj.share.Share.receive(Share.java:380)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:359)
	at com.hierynomus.smbj.share.Share.setInfo(Share.java:191)
	at com.hierynomus.smbj.share.DiskShare.setFileInformation(DiskShare.java:330)
	at com.hierynomus.smbj.share.DiskEntry.setFileInformation(DiskEntry.java:89)
	at com.hierynomus.smbj.share.DiskEntry.rename(DiskEntry.java:132)
	at com.hierynomus.smbj.share.DiskEntry.rename(DiskEntry.java:127)

**Comment by berkanaslan** [comment]
> @NilsHult i was trying to implement your solution i am getting below error
> 
> com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_NAME_INVALID (0xc0000033): SetInfo failed for SMB2FileId{persistentHandle=31 88 00 00 2f 00 00 00} at com.hierynomus.smbj.share.Share.receive(Share.java:380) at com.hierynomus.smbj.share.Share.sendReceive(Share.java:359) at com.hierynomus.smbj.share.Share.setInfo(Share.java:191) at com.hierynomus.smbj.share.DiskShare.setFileInformation(DiskShare.java:330) at com.hierynomus.smbj.share.DiskEntry.setFileInformation(DiskEntry.java:89) at com.hierynomus.smbj.share.DiskEntry.rename(DiskEntry.java:132) at com.hierynomus.smbj.share.DiskEntry.rename(DiskEntry.java:127)

Same error. Any solution available for it?
