### ISSUE TITLE
transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 75 >> as transport is disconnected

### ISSUE THREAD

**Issue by netskill** [hierynomus/smbj#751]
When running about 100 SMBClient to write file into sharefolder, got the exception. 
At the code position 'session =connection.authenticate(auth);' throw the exception.
Can you help to give some suggestion?

com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 72 >> as transport is disconnected
        at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:114)
        at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
        at cifs.threadsKrb5.CIFSThreadKrb5.run(CIFSThreadKrb5.java:174)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 72 >> as transport is disconnected
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68)
        at com.hierynomus.smbj.connection.Connection.send(Connection.java:234)
        at com.hierynomus.smbj.connection.Connection.sendAndReceive(Connection.java:242)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.initiateSessionSetup(SMBSessionBuilder.java:197)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:126)
        at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)

**Comment by netskill** [comment]
Tun on the Debug and got the following exception.

2023-02-15 18:50:59 [ T-65:333844 ] - [ DEBUG ] Granted 1 (out of 510) credits to SMB2_SESSION_SETUP with message id << 2 >>

com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 2 >> as transport is disconnected
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:114)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
	at cifs.threadsKrb5.CIFSThreadKrb5.run(CIFSThreadKrb5.java:174)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hierynomus.protocol.transport.TransportException: Cannot write SMB2_SESSION_SETUP with message id << 2 >> as transport is disconnected
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.write(DirectTcpTransport.java:68)
	at com.hierynomus.smbj.connection.Connection.send(Connection.java:234)
	at com.hierynomus.smbj.connection.Connection.sendAndReceive(Connection.java:242)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.initiateSessionSetup(SMBSessionBuilder.java:197)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:126)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
	... 3 more
