### ISSUE TITLE
STATUS_ACCESS_DENIED(3221225506/3221225506): Could not connect to <smb drive folder path>

### ISSUE THREAD

**Issue by kadirchisty** [hierynomus/smbj#803]
After activating SMB data-in-transit encryption on smb shares, we are facing below error from SMBJ jar. 

STATUS_ACCESS_DENIED(3221225506/3221225506): Could not connect to <SMB share folder path>
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Could not connect to <SMB share folder path>
	at com.hierynomus.smbj.session.Session.connectTree(Session.java:169) ~[smbj-0.6.0.jar:0.6.0]
	at com.hierynomus.smbj.session.Session.connectShare(Session.java:139) ~[smbj-0.6.0.jar:0.6.0]

Recommendation is to use SMB 3.0 protocol.

Any help on how we can make use of SMB 3.0 protocol with smbj jar is much appreciated.

**Comment by hierynomus** [comment]
What is the `SmbConfig` you're using?

**Comment by kadirchisty** [comment]
Hi @hierynomus,

SmbConfig.builder().withDfsEnabled(true).withMultiProtocolNegotiate(true).build();

**Comment by kadirchisty** [comment]
@hierynomus - Please let's know incase of any updates

**Comment by hierynomus** [comment]
Have you tried adding `withEncryption(true)` to the SmbConfig?

**Comment by kadirchisty** [comment]
@hierynomus Thanks for quick response. With above change in smbjConfig and upgrading to latest smbj library version, it is connecting without issues.
