### ISSUE TITLE
java.lang.NoClassDefFoundError: com.hierynomus.smbj.auth.NtlmAuthenticator$$ExternalSyntheticLambda1 when using smbj

### ISSUE THREAD

**Issue by courville** [hierynomus/smbj#807]
Hi, first thank you for your work on smbj that I use in my open-source Android video player application https://github.com/nova-video-player/aos-AVP

I noticed that on my crashnalytics sentry backend, on my user base there are quite some errors related to:
```
java.lang.NoClassDefFoundError: com.hierynomus.smbj.auth.NtlmAuthenticator$$ExternalSyntheticLambda1
    at com.hierynomus.smbj.auth.NtlmAuthenticator.authenticate(SourceFile:120)
    at com.hierynomus.smbj.auth.NtlmSealer.authenticate(SourceFile:69)
    at com.hierynomus.smbj.connection.SMBSessionBuilder.processAuthenticationToken(SourceFile:190)
    at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SourceFile:151)
    at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SourceFile:119)
    at com.hierynomus.smbj.connection.Connection.authenticate(SourceFile:202)
    at com.archos.filecorelibrary.smbj.SmbjUtils.getSmbConnection(SourceFile:105)
    at com.archos.filecorelibrary.smbj.SmbjUtils.getSmbShare(SourceFile:115)
    at com.archos.filecorelibrary.smbj.SmbjFile2.fromUri(SourceFile:154)
    at com.archos.filecorelibrary.MetaFile2Factory.getMetaFileForUrl(SourceFile:39)
    at com.archos.mediacenter.filecoreextension.upnp2.MetaFileFactoryWithUpnp.getMetaFileForUrl(SourceFile:33)
    at com.archos.mediaprovider.video.NetworkScannerServiceVideo.doScan(SourceFile:400)
    at com.archos.mediaprovider.video.NetworkScannerServiceVideo.handleMessage(SourceFile:314)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:135)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```
Code is located there: https://github.com/nova-video-player/aos-FileCoreLibrary/blob/v6.1/src/com/archos/filecorelibrary/smbj/SmbjUtils.java

It happens with smbj 0.13.0 and I am not able to reproduce myself the error on my setup.
Please let me know if I am doing something wrong.

**Comment by courville** [comment]
Note that I can reproduce now on old android phone emulator API21.
